### ISSUE TITLE
Cart Search?

### ISSUE THREAD

**Issue by InfiniteDevelopment** [Crinsane/LaravelShoppingcart#100]
![screen shot 2015-08-18 at 11 49 58 am](https://cloud.githubusercontent.com/assets/1442229/9334926/4c2519ae-459f-11e5-9f89-07e162353b44.png)

I get this when using cart search. I am trying to use it to get the rowid back of a specific item ID...

**Comment by Crinsane** [comment]
Please show your code.

**Comment by InfiniteDevelopment** [comment]
I have fixed it. I found the rowID and I am happy now. I just have to figure out how to delete one item from the cart now lol. 

You can close this one bro! :) 

Good work on this BTW. I love the support.

**Comment by Crinsane** [comment]
Ok, glad you figured it out!
