### ISSUE TITLE
Remove from cart throws an exception

### ISSUE THREAD

**Issue by junkystu** [Crinsane/LaravelShoppingcart#101]
The `remove()` function returns null rather than boolean true when removing items. After passing it a non existing rowid, it throws an `Gloudemans\Shoppingcart\Exceptions\ShoppingcartInvalidRowIDException` exception with empty message rather than return false.

**Comment by it-can** [comment]
I am also experiencing this error in Laravel 5.1.12

**Comment by lbodden** [comment]
can confirm not working in laravel 5.1.16

**Comment by Crinsane** [comment]
Please supply me the code that doesn't work. Because I've just tested it and everything is ok.

New Laravel installation version 5.1.17:

Add a new item to the cart:

```php
Route::get('/', function () {
    Cart::add('293ad', 'Product 1', 1, 9.99, ['size' => 'large']);
});
```

When I next dump the content of the cart `dd(Cart::content());` I get one item in the cart with rowId: 0f6524cc3c576d484150599b3682251c

Next remove the item from the cart:

```php
Route::get('delete', function () {
	Cart::remove('0f6524cc3c576d484150599b3682251c');
});
```

Item is removed, no exception thrown...

**Comment by junkystu** [comment]
@Crinsane I've used pretty much the same code as you with the same version of Laravel, new install. When I dd the content, I get the item with its rowId. 

    Route::get('/', function () {
        Cart::add('293ad', 'Product 1', 1, 9.99, ['size' => 'large']);
        dd(Cart::content());
    });

    Route::get('delete', function () {
        // Cart::get('0f6524cc3c576d484150599b3682251c');
        Cart::remove('0f6524cc3c576d484150599b3682251c');
    });

On the delete page I get the exception `ShoppingcartInvalidRowIDException in Cart.php line 191`. If I dump `Cart::get('0f6524cc3c576d484150599b3682251c')`, I get back null. 

It looks like the item is somehow not found but either way, I think the delete function should not throw an exception if the item is not found given that `get()` does not throw an exception.
![testing local-delete](https://cloud.githubusercontent.com/assets/7740675/10117040/ee8f8e26-6440-11e5-9eb9-1b6a2fc32bd9.png)

**Comment by Crinsane** [comment]
Try to first do the `Cart::add()` and no `dd()`. Then comment the `Cart::add()` and uncomment the `dd()`
Now you should see content, and a rowId. Now you should be able to delete it.

When you perform a `dd()` method, it will make the script die instantly, so the session is not written.

**Comment by junkystu** [comment]
@Crinsane , yes, that seems to be what's happening. However, if you refresh the delete page, you will still see an exception because you are trying to remove and ID that no longer exists in the cart content. The issue is that an exception is thrown and it's not documented. The documentation says:

    /**
     * Remove a row from the cart
     *
     * @param  string  $rowId The rowid of the item
     * @return boolean
     */
But `remove()` always returns `null` upon successfully removing an item or throws an exception if the item is not found.

**Comment by Crinsane** [comment]
Aaah I see. Could you send a pull request with the updated docblocks?

**Comment by junkystu** [comment]
I would rather update it so that it returns boolean. Please let me know if you'd like me to do that.

**Comment by Crinsane** [comment]
You can give it a shot

**Comment by junkystu** [comment]
I gave it a go! I've noticed some inconsistencies in other docblocks so I'll update those too when I get the chance.

**Comment by Harrrrry** [comment]
I feel the same problem,
ShoppingcartInvalidRowIDException in Cart.php line 191. 
Can any one suggest me a solution

**Comment by Crinsane** [comment]
@Harrrrry What problem? What code? How can I reproduce this? 
Can't give a suggestion if you don't give us anything to work with.

**Comment by Harrrrry** [comment]
@Crinsane I updated my question with complete code, please take a look.

**Comment by junkystu** [comment]
@Crinsane @Harrrrry my pull request has fixed this issue.

**Comment by Harrrrry** [comment]
@junkystu thanks, i will check.

**Comment by junkystu** [comment]
@Crinsane Why wasn't the pull request merged in? Does anything require changing?
