### ISSUE TITLE
Add Custom Data

### ISSUE THREAD

**Issue by andiaziz** [Crinsane/LaravelShoppingcart#102]
Hello :)
I just want to ask about cart feature.

When I use CodeIgniter Cart Library, it allow us to add custom data on the Cart
https://ellislab.com/codeigniter/user-guide/libraries/cart.html
I can add the Product URL, so on the Cart page, it will clickable on the Product Title.

Is that possible with this package?
Thanks

**Comment by redkowloon** [comment]
Hi, 

you can add custom data per item basis using option
