### ISSUE TITLE
Call to a member function add() on a non-object

### ISSUE THREAD

**Issue by angelrdgz** [Crinsane/LaravelShoppingcart#106]
This is my code:

Cart::add(array('id' => '293ad', 'name' => 'Product 1', 'qty' => 1, 'price' => 9.99, 'options' => array('size' => 'large')));
return Redirect::to('items')->with('message','Se agrego el articulo al carrito de compras');

I'm already use your example code.

**Comment by Crinsane** [comment]
Which Laravel version and please give me the full stack trace

**Comment by angelrdgz** [comment]
Laravel 4.2  but I already had used your library before and it worked perfectly . Now I get this error

**Comment by Crinsane** [comment]
I still need more code and a stacktrace to debug this.
