### ISSUE TITLE
How to get $rowId if i have $id product

### ISSUE THREAD

**Issue by muhghazaliakbar** [Crinsane/LaravelShoppingcart#108]
i tried ```Cart::search(['id] => $id);``` but i cant get rowId from item

**Comment by Crinsane** [comment]
`Cart::search(['id' => $id]);` is indeed the way to go. If it's not working I really need more information to help you.

**Comment by muhghazaliakbar** [comment]
sorry, my mistake :D 
my requested $id is null, i forget to recheck

**Comment by abr4xas** [comment]
Hey @Crinsane 

```php
Cart::search(['id' => $id]);
```

isn't work


```
Type error: Argument 1 passed to Gloudemans\Shoppingcart\Cart::search() 
must be an instance of Closure, array given, called in ... 
```

**Comment by ayvazyan10** [comment]
> Hey @Crinsane
> 
> ```
> Cart::search(['id' => $id]);
> ```
> 
> isn't work
> 
> ```
> Type error: Argument 1 passed to Gloudemans\Shoppingcart\Cart::search() 
> must be an instance of Closure, array given, called in ... 
> ```

Try this:

\Cart::search(function ($cartItem, $rowId) {
return $cartItem->id == 5;
});
