### ISSUE TITLE
array_key_exists()

### ISSUE THREAD

**Issue by pl38** [Crinsane/LaravelShoppingcart#110]
Hi,

I building a site using the cart and I wonder is anyone could help with this, Laravel 5.1.20 is the version I'm using and the latest stable version of the cart.

I can add to the cart without any issues but the I try to increment the qty I get the error:

ErrorException in Collection.php line 993
at HandleExceptions->handleError('2', 'array_key_exists(): The first argument should be either a string or an integer', '***/vendor/laravel/framework/src/Illuminate/Support/Collection.php', '993', array('key' => array('ada83f008e1c11d75d04493ac9ef115a')))

My code is this:

        if (isset($productId) && $method == 'plus') {
            $rowId = Cart::search(array('id' => "$productId"));
            // $cart = Cart::content();// dumps the cart as expected
            // dd($rowId);
            // the above returns the correct $row id
            // returns array:1 [▼
            //   0 => "ada83f008e1c11d75d04493ac9ef115a"
            // ]
            $rowSelected   = Cart::get($rowId);<- error here when calling get on an existing rowId
            dd($rowSelected);<- never gets this far
            Cart::update($rowId, array("qty "=>""));
        }

Any thoughts greatly appreciated...

**Comment by Crinsane** [comment]
One of the first things that comes to my mind is watch out with those `dd()` methods. While helpful, they can give problems with sessions being reset or not written. So quickly checking the content of the cart with `dd()`, going back to your editor, commenting out the function and refreshing the page, could mean the cart is empty at the second try.

Also, have you tried setting the new qty by simply passing the new qty as the second parameter for the `Cart::update()` method? So `Cart::update($rowId, $newQty);`

**Comment by pl38** [comment]
Hi Crinsane,

yes that sorted it, thank you - and just in case it helps anyone else here is what I did:

    public function edit(Request $request)
    {
        // dd($request->product_id);//->product_id->increment
        $productId = $request->product_id;
        $method = $request->method;
        //increment the quantity
        if (isset($productId) && $method == 'plus') {
            $rowId = Cart::search(array('id' => "$productId"));
            $rowId = $rowId[0];
            $item = Cart::get($rowId);
            Cart::update($rowId, $item->qty + 1);
        }

        //decrease the quantity
        if (isset($productId) && $method == 'minus') {
            $rowId = Cart::search(array('id' => "$productId"));
            $rowId = $rowId[0];
            $item = Cart::get($rowId);
            Cart::update($rowId, $item->qty - 1);
        }

        //decrease the quantity to 0 to turn off
        if (isset($productId) && $method == 'del') {
            $rowId = Cart::search(array('id' => "$productId"));
            $rowId = $rowId[0];
            $item = Cart::get($rowId);
            Cart::remove($rowId);
        }
        $cart = Cart::content();
        return view('order/basket', compact('cart'));
    }

**Comment by ruhinacse14** [comment]
what is $method here? how do you put link in it?button?Can you please specify me.
