### ISSUE TITLE
PHP Fatal error: Call to undefined method Gloudemans\Shoppingcart\Facades\Cart::isDeferred()

### ISSUE THREAD

**Issue by andersonmadeira** [Crinsane/LaravelShoppingcart#111]
I followed the instructions in the main README.md file for Laravel 5 and when I try to create a controller I get the following errors:

    $> php artisan make:controller --plain CartController

    PHP Fatal error:  Call to undefined method Gloudemans\Shoppingcart\Facades\Cart::isDeferred() in /.../vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php on line 119
                                                                               
    [Symfony\Component\Debug\Exception\FatalErrorException]                      
    Call to undefined method Gloudemans\Shoppingcart\Facades\Cart::isDeferred()  
                                                                               
Is this a bug or I did something wrong?

btw I'm using  ```Laravel 5.1``` and ```PHP 5.5.9-1ubuntu4.12```

**Comment by andersonmadeira** [comment]
I feel so embarrassed to assume my silly mistake, but here it goes: I put the facade instead of the serviceprovider in my config/app.php. I think you guys should delete this issue as it does not feature a problem/error/bug in the library. Thanks.

**Comment by DhanapalMadheswaran** [comment]
i m getting 
Call to undefined method Gloudemans\Shoppingcart\Cart::total() 
like this 
what is the issue?

**Comment by Crinsane** [comment]
Please create a new issue with a code sample

**Comment by DhanapalMadheswaran** [comment]
${{ Cart::total() }}

i put like this only 
but it getting
 Call to undefined method Gloudemans\Shoppingcart\Cart::total() error:
/////Service Providers.../
Gloudemans\Shoppingcart\ShoppingcartServiceProvider::class

///Class Aliases////////////
'Cart' => Gloudemans\Shoppingcart\Facades\Cart::class,

//////////composer //////////
"gloudemans/shoppingcart": "~1.3"

**Comment by Crinsane** [comment]
Please create a new issue.
