### ISSUE TITLE
it seems that cart::add is not adding but overwriting

### ISSUE THREAD

**Issue by ShaitAtComodo** [Crinsane/LaravelShoppingcart#114]
also when page is refreshed the cart is gone

**Comment by mzmmlds** [comment]
it depends, if you pass same id then the cart will update its qty and subtotal , try passing with different id.

**Comment by ShaitAtComodo** [comment]
yes, i use different id.

**Comment by mzmmlds** [comment]
can we see what you have done so far?

**Comment by ShaitAtComodo** [comment]
just installed it
and testing it in the controller
    public function index()
    {
        Cart::add(212, 32, 12, 12, array(12));
        dd(Cart::content());
    }
than changing the is to 213
when refreshing only the new one is appearing.
then remove the add function and getting empty array!

**Comment by mzmmlds** [comment]
Try this one, it working fine in my machine.

Cart::add([
                'id'    => $product_id,
                'name'  => 'XYZ',
                'qty'   => 1,
                'price' => 10.00
            ]);

**Comment by ShaitAtComodo** [comment]
no ,  I am sorry no change

**Comment by Crinsane** [comment]
The problem is the `dd()` method, the PHP script will die so Laravel doesn't write the session.

**Comment by ShaitAtComodo** [comment]
yes correct, sorry...
