### ISSUE TITLE
Searching products in loop

### ISSUE THREAD

**Issue by mzmmlds** [Crinsane/LaravelShoppingcart#115]
Lets say i have 10 products with their respective ids, if i add a loop to search all the products in shopping cart the rowId always empty. Example Code : 

loop(product_id)
   return Cart::search(['id' =>product_id]);
loopends

the search is working without loop that is only for one product.

**Comment by Crinsane** [comment]
I will need a bit more code to really test this.

**Comment by mzmmlds** [comment]
ok, consider if i have 10 products on my page , now i want to check with the cart for each product.

$products = [10,20,30,35,45,46,47,48,49,50];

foreach($products as $product)
       $checkinCart = Cart::search(['id' => $product->id]);
       
       if(!is_null($checkinCart)){
              $getQty = Cart::get($checkinCart[0]); 
              return $getQty['qty'];
       } 
       
       return 0;
endforeach

I hope you are clear now.

**Comment by mzmmlds** [comment]
this issue is because of datatypes , if the datatype in cart is string then we need to pass id as string. Solved it :)
