### ISSUE TITLE
Is there a way to store cart in users cookie (~forever)?

### ISSUE THREAD

**Issue by pupadupa** [Crinsane/LaravelShoppingcart#116]
Hi,

Is there a way to store cart in user's cookies forever? 
I don't want to store session forever or change session driver to cookie, but I want to store cart in cookies forever (or for a long time).
So, is there a way to change cart's storage to cookies?

**Comment by Crinsane** [comment]
There's currently no build in way to achieve this, so you'd have to write this functionality yourself.
