### ISSUE TITLE
Problem with adding more than 2 options in Cart

### ISSUE THREAD

**Issue by huyle2607** [Crinsane/LaravelShoppingcart#117]
Hi!
In my cart, I want to have more than 1 option fields. For example: 
```
Cart::add(
 ....
 ....
'options' => array([
                            'image' => 'img.jpg',
                            'sale_price' => '100'
                             ])  
)
```
When I try to get 2 options out Laravel said that those are Undefined Index. Are there any solutions?

**Comment by Crinsane** [comment]
I need more code to debug this

**Comment by Crinsane** [comment]
Seems to work perfectly fine: https://github.com/Crinsane/LaravelShoppingcart/blob/f5f15c73a21fe8bd0752b6320d20a14819322cda/tests/CartTest.php#L79
