### ISSUE TITLE
FatalErrorException in CartController.php line 15: Class 'App\Http\Controllers\Cart' not found

### ISSUE THREAD

**Issue by mbijker** [Crinsane/LaravelShoppingcart#118]
I'm sorry I'm pretty new to Laravel but can't get this to work.
The error I'm getting is:

FatalErrorException in CartController.php line 15: Class 'App\Http\Controllers\Cart' not found

My CartController.php:
'''
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class CartController extends Controller
{
    public function addToCart()
    {
        Cart::add('192ao12', 'Product 1', 1, 9.99);
        Cart::add('1239ad0', 'Product 2', 2, 5.95, array('size' => 'large'));

        return 'Added';
    }

    public function viewCart()
    {
        return view('pages.cart');
    }

}
'''

I think I need to add a 'use' but how exactly?

Thanks in advance

**Comment by Crinsane** [comment]
You indeed have to use the Cart namespace. Simply "use Cart;"

**Comment by vpa24** [comment]
thanks

**Comment by brindhabrindha** [comment]
thanks

**Comment by lexpope** [comment]
Thanks, that was helpful...

**Comment by hoa-kidnav** [comment]
thanks
