### ISSUE TITLE
Not working! 

### ISSUE THREAD

**Issue by renege** [Crinsane/LaravelShoppingcart#120]
@Crinsane why is this not working:

This is a Controller function called by a get-link ```/cart/{{ $product->id }}```
```
public function cart(Product $product)
    {
        Cart::add($product->id, $product->title, 1, $product->price);
        return redirect()->back();
    }
```
In the View I have this:
```
@foreach(Cart::content() as $cart)
{{ var_dump($cart) }} // nothing dumped
@endforeach
```

```
Gloudemans\Shoppingcart\CartCollection Object ( [items:protected] => Array ( ) ) 1
```

**Comment by David-Kurniawan** [comment]
Okay, so I figured out that routes need to be added within the "web" middleware group like this:
```
Route::group(['middleware' => 'web'], function () {
	Route::get('tours/{id}/{slug}', 'ToursController@detail');
	Route::post('tours/addtocart', 'ToursController@addtoCart');
});
```

**Comment by leamasuero** [comment]
@David-Kurniawan  @Crinsane , I'm facing the same problem ( Laravel Framework version 5.2.29): cart is empty on every request. Session is not working as expected. On the other hand, "web" middleware is enabled by default on laravel 5.2:
https://laravel.com/docs/master/middleware#middleware-groups

**Comment by leamasuero** [comment]
LaravelShoppingCart **is working ok**. The problem was related to the way Laravel is handling the session:

http://stackoverflow.com/questions/29346743/laravel-5-session-doesnt-work
