### ISSUE TITLE
How to store items in user session?

### ISSUE THREAD

**Issue by huyle2607** [Crinsane/LaravelShoppingcart#122]
Could anybody show me how to store items in cart in user session, please? 
For example, User A has 2 items in cart. Then user A logouts and user B logins, cart will show user B's cart which is empty. And when user A logins again, his cart still has 2 items. Is there anyway to do that?

'Cause when I logout and login with different account, cart still keeps the same items from the last person.
Thanks a lots.

**Comment by WayneHarris** [comment]
Hi @huyle2607  

Laravel sessions are based on the browser/cookie, not the user logged in. So when you add cart items they're in the 'main' cart instance in the session, the next user will see the same cart unless you clear it when they log out or the session expires.

If you only show carts to the user when logged in you could set the cart instance to the users ID and retrieve, the matching cart when logged in. This would lead to more than one cart in a session, but you control who sees what cart based on the instance id you gave it.

```
Cart::instance('user-id-main')->add($newItem);

$cart = Cart::instance('user-id-main')->content();

```
See: [Cart Instance](https://github.com/Crinsane/LaravelShoppingcart#instances)

This would not work if you let users create a cart when logged out. Hope it gives you some ideas on how to handle the cart sessions.

**Comment by huyle2607** [comment]
@WayneHarris  Thank you very much! Your answer is very helpful!
