### ISSUE TITLE
new attributes 

### ISSUE THREAD

**Issue by doctorde** [Crinsane/LaravelShoppingcart#127]
Is it possible to add new attribute  on each row ?
Cart::add(array('id' => $product_id,'uuid'=>$uuid, 'name' => $product->title, 'qty' => 1, 'price' => $price ,'options' => array('size' => $size,'colour' => $colour) ));

**Comment by Crinsane** [comment]
You can add the id, name, qty and price. All other 'options' you can add to the options array.
