### ISSUE TITLE
Cart duration before auto expire/empty ?

### ISSUE THREAD

**Issue by cjmling** [Crinsane/LaravelShoppingcart#129]
Does the duration controlled by "lifetime" in config/session.php  ?

**Comment by Jeemusu** [comment]
Yep, it uses the Laravel session so will use whatever driver and settings your using in your Laravel app.

**Comment by Crinsane** [comment]
As said above, it uses the Laravel session. So yes. :-)

**Comment by jaublanc-bobbies** [comment]
Hello,

I would like to know if is it possible to run a timer for 10min when we add an item to a cart ? At the end of the timer, the cart should be expire/empty. 

How can I do that ?

Thanks,

**Comment by Crinsane** [comment]
The cart uses the default Laravel session. If you want other logic you'll have to implement that yourself.

**Comment by jaublanc-bobbies** [comment]
How can I set the session just for the cart ?

**Comment by Crinsane** [comment]
You can't. You'll have to create the logic for clearing the cart after a certain time yourself.
