### ISSUE TITLE
cart update not working on different routes. 

### ISSUE THREAD

**Issue by banerjeeaditya** [Crinsane/LaravelShoppingcart#132]
Hi I am facing a weird problem in which I update the cart in one route but it doesnt reflect the updates in the cart on the other route. 

for example I have a route name cart/revalidate and have a method name getIndex in which I am updating the cart. The code is -: 

foreach($saleprice as $key => $value){
    		$row = Cart::instance($cookie)->get($key);
    		$row->options['sale_price'] = $value;
    		$row->options['store_id'] = $storeId;
    		$row->price = $value;
    		$x = Cart::instance($cookie)->update($key, $row->toArray());
    	}

now when I output the $row in this I could see that the cart has been update but I have another route named cart/view 

just print_r the cart instance and I see that the cart has not update 

        $cartData = Cart::instance($cookie)->content();
        echo "<pre>";
        print_r($cartData);
        die;

Please assist. 
Thank You

**Comment by Crinsane** [comment]
I need more code to debug this. But watch out with `die` or `dd()`, because they will destroy the Laravel session (which the cart uses)
