### ISSUE TITLE
[Laravel 5.2] Class 'Cart' not found

### ISSUE THREAD

**Issue by dasaco** [Crinsane/LaravelShoppingcart#133]
Hello,

Version: Laravel 5.2

I'm getting Class 'Cart' not found, when trying to use it in Controller, that has use Cart in it's header

In config/app.php I have both Provider and Facade 

Provider:
Gloudemans\Shoppingcart\ShoppingcartServiceProvider::class,

Facade:
'Cart'      => Gloudemans\Shoppingcart\Facades\Cart::class,

In routes I use 'web' middleware correctly.

In composer.json I have

"require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.2.*",
        "laravelcollective/html": "5.2.*",
        "filp/whoops": "^2.0",
        "gloudemans/shoppingcart": "~1.3"
    },

Any ideas on how to solve this issue?

Thank you

**Comment by dasaco** [comment]
Also tried various ways of writing facade and provider in app.php, nothing works

Done composer dump-autoload and composer update

Directory exists in vendor folder, it is there

**Comment by lukepolo** [comment]
Did you reference it via \Cart or just Cart.

If you did the later make sure to include it.

use Cart;

**Comment by dasaco** [comment]
Hello, thank you for your answer

But I tried this already, doesn't seem to work either

**Comment by MrLenh** [comment]
I'm facing this issue too, did you fix it?

**Comment by wapnen** [comment]
hello have you found the solution to this problem

**Comment by eberkund** [comment]
Post your source code, it is definitely working

**Comment by sampat-rebelute** [comment]
Hello i am also facing the same issue i.e. Cart not found on server.

**Comment by DavidPrologo** [comment]
I've got the same issue, my friend told me that's the php version 7.0 which must be updated to at least 7.1. But the server's using 7.0

**Comment by fahruroze** [comment]
I fix this issue with include on CartController -> use Cart;

**Comment by nipun21** [comment]
I have fixed this issue by adding in config\app.php

Provider:
Gloudemans\Shoppingcart\ShoppingcartServiceProvider::class,

aliases:
'Cart' => Gloudemans\Shoppingcart\Facades\Cart::class,


in app\Http\Controller\Your-Controller-file.php

use Cart;

**Comment by danducdao** [comment]
you right. it fixed

**Comment by bumbummen99** [comment]
The package automatically registers the alias. Did you use it as `\Cart` or `Cart`?

https://github.com/bumbummen99/LaravelShoppingcart/issues/77

**Comment by abdulrehman3725** [comment]
> Hello,
> 
> Version: Laravel 5.2
> 
> I'm getting Class 'Cart' not found, when trying to use it in Controller, that has use Cart in it's header
> 
> In config/app.php I have both Provider and Facade
> 
> Provider:
> Gloudemans\Shoppingcart\ShoppingcartServiceProvider::class,
> 
> Facade:
> 'Cart' => Gloudemans\Shoppingcart\Facades\Cart::class,
> 
> In routes I use 'web' middleware correctly.
> 
> In composer.json I have
> 
> "require": {
> "php": ">=5.5.9",
> "laravel/framework": "5.2._", "laravelcollective/html": "5.2._",
> "filp/whoops": "^2.0",
> "gloudemans/shoppingcart": "~1.3"
> },
> 
> Any ideas on how to solve this issue?
> 
> Thank you

Your problem worked for me.

**Comment by moizfyaa** [comment]
It's also not helpfull
