### ISSUE TITLE
Cart Details Gone when refresh withsame browser

### ISSUE THREAD

**Issue by githubhasib** [Crinsane/LaravelShoppingcart#135]
Suppose My domain name is www.xyz.com
now I am visit www.xyz.com from my browser. After visit I add 4 product into cart list.Now I am hit on my browser same tab with www.xyz.com then cart list gone.

But I think It should exist before browser close or not delete by hand.

I am using laravel 5.2

**Comment by Crinsane** [comment]
Think this is an issue with your code.
