### ISSUE TITLE
not working with laravel 5.2

### ISSUE THREAD

**Issue by charanjeet5ingh** [Crinsane/LaravelShoppingcart#137]
cart is not working with laravel 5.2, all the data loss when I refresh the page, Please tell the solution for this.

**Comment by Crinsane** [comment]
Wrap your routes in the web middleware

**Comment by charanjeet5ingh** [comment]
i used it but it is giving TokenMismatchException error please help me with that

**Comment by Crinsane** [comment]
That exception has nothing to do with the package. Probably you're not sending through the csrf token from the place where you add an item to the cart.

**Comment by charanjeet5ingh** [comment]
yeah thank you by the way it worked like charm thank for you help sir
