### ISSUE TITLE
Why I cant change subtotal from update method?

### ISSUE THREAD

**Issue by Soufraz** [Crinsane/LaravelShoppingcart#140]
When I tried to update the subtotal from update method, the setted value in update method is overriding.
Cause in the method updateRow() inside Shoppingcart/Cart.php, after the foreach, there is an if that recalculates the value of subtotal with quantity * price.
But, if I need change de subtotal after apply some discount per item? What I need to do?
I think that, if I am trying to change de subtotal, this math (quantity * price) needs to be ignoring.
Is there a business rule that explains this?

**Comment by Soufraz** [comment]
Why closed? @Crinsane

**Comment by Crinsane** [comment]
Sorry, forgot to comment. I've done a majpr rewrite which makes subtotal a calculated field, so it can't be set either way. Also, adding discount to a product is a feature that will be implemented in the next commit.

**Comment by wolle404** [comment]
@Crinsane is there any progress for this?
