### ISSUE TITLE
Search always return false.

### ISSUE THREAD

**Issue by permatis** [Crinsane/LaravelShoppingcart#145]
when I wanted to make searching to get RowID always return false.
``` php 
$id = \Cart::search([ 'id' => $request->get('id') ]);
dd($id);
```
always show `false`, but if ` $request->get('id')` change with 1 show `true`.
And then i change `search` function in `CartRowCollection` class for comparison with == conditional or use `strcmp` function.

``` php
$found = (strcmp($this->{$key}, $value) == 0) ? true : false;
```
Its work.

**Comment by Crinsane** [comment]
Problem seems to be with the type difference (string vs int).
In the next release this shouldn't be a problem anymore.

**Comment by ChadTaljaardt** [comment]
when is the next release scheduled?

**Comment by Crinsane** [comment]
Aiming for next week
