### ISSUE TITLE
Not fully updated yet?

### ISSUE THREAD

**Issue by RileyDavidson** [Crinsane/LaravelShoppingcart#151]
I installed using composer as said, but the new features (such as Tax and Subtotal) don't exist. Did I make a mistake when setting it up or has the second version not been officially released yet?

**Comment by Crinsane** [comment]
For now you'll have to use dev-master for version 2. Will tag it probably today or tomorrow.

**Comment by rap2hpoutre** [comment]
👍

**Comment by leamasuero** [comment]
Hello @Crinsane . Any update on this? I'm using this cart and I need to use taxes features. I expect to require a new version instead of working with de dev-master one. Thanks!
