### ISSUE TITLE
Error using Cart

### ISSUE THREAD

**Issue by andersonmadeira** [Crinsane/LaravelShoppingcart#152]
Whenever I try to use Cart facade, I get the following error:

ReflectionException in Container.php line 741:
Class cart does not exist

in Container.php line 741
at ReflectionClass->__construct('cart') in Container.php line 741
at Container->build('cart', array()) in Container.php line 631
at Container->make('cart', array()) in Application.php line 674
at Application->make('cart') in Container.php line 1163
at Container->offsetGet('cart') in Facade.php line 151
at Facade::resolveFacadeInstance('cart') in Facade.php line 120
at Facade::getFacadeRoot() in Facade.php line 205
at Facade::__callStatic('count', array()) in PageController.php line 38
at Cart::count() in PageController.php line 38
at PageController->home(object(Request))

What's wrong? I followed all the install instructions in the main readme file.

**Comment by ChadTaljaardt** [comment]
have you added the 'use Cart;' at the top?

**Comment by Crinsane** [comment]
Which version are you on?

**Comment by andersonmadeira** [comment]
Yes, i added "use Cart;". Version 1.3
Em 31 de mai de 2016 02:43, "Rob Gloudemans" <notifications@github.com>
escreveu:

**Comment by mucyomiller** [comment]
@Crinsane it's in laravel v5.2.39 actually latest i don't where bug originated by whenever you try to use Cart facade in your controller it's throw FatalErrorException  Class 'Cart' not found even if we have added use Cart;

**Comment by Crinsane** [comment]
Can't reproduce, seems to work perfectly fine, so must be something in your app

https://github.com/Crinsane/LaravelShoppingcart/issues/156#issuecomment-226988559

**Comment by mucyomiller** [comment]
@Crinsane  i found that this error on our project is caused by forgeting to clear old cached configuration
whenever any other person meet this error be sure to clear old config cache 
php artisan config:cache or register this package serviceprovider straight in routes.php
App::register('Gloudemans\Shoppingcart\ShoppingcartServiceProvider'');

**Comment by kaloraat** [comment]
@mucyomiller 
It works if i add it in routes/web.php:
`App::register('Gloudemans\Shoppingcart\ShoppingcartServiceProvider');`
But why it does not work after registering in config/app service providers. I dont understand.

I did `php artisan config:cache` too.

**Comment by fendiseptiawan0709** [comment]
@kaloraat 
Thank you very much. It works for me.
Currently using Laravel 5.4 and shopping cart 2.3
