### ISSUE TITLE
Cannot add zero price.

### ISSUE THREAD

**Issue by Grukdon** [Crinsane/LaravelShoppingcart#153]
Not sure if this is by design, but I cannot add an item with a price of 0.00 (or any form of zero) since the update.

In the constructor of CartItem.php 
"if(empty(0.00)..." is evaluated to true, throwing the InvalidArgumentException.

So no freebies?

**Comment by Crinsane** [comment]
Feel free to send a PR. 🙂

**Comment by Crinsane** [comment]
Merged
