### ISSUE TITLE
Realease please

### ISSUE THREAD

**Issue by rap2hpoutre** [Crinsane/LaravelShoppingcart#157]
Using master in production is too dangerous ;) Any release date?

**Comment by Crinsane** [comment]
Version 2 is released

**Comment by rap2hpoutre** [comment]
Thank you ! 😃

**Comment by Mastergalen** [comment]
Is there a changelog?

Are there any breaking changes?

**Comment by Crinsane** [comment]
No and yes. 😉 I will do my best to create a changelog and update the docs asap!

**Comment by Mastergalen** [comment]
Awesome, much appreciated
