### ISSUE TITLE
Instructions for using Buyable and Tax configurations are missing

### ISSUE THREAD

**Issue by santoshachari** [Crinsane/LaravelShoppingcart#158]
Hey @Crinsane , 

Thanks for this extension. Just wanted to update that how to use Buyable Interface and setting Taxes isn't clear from the instructions. Can add more to it when you find time? Thanks!

Also I notice that you have code for restoring the cart from database. Nice!. :). How to implement that?

**Comment by Crinsane** [comment]
Hi @santoshachari,

Documentation is indeed not yet up to date with the current version, will try to update asap.
For now, for the restoring functionality, have a look at the test file, methods:

it_can_store_the_cart_in_a_database
it_can_restore_a_cart_from_the_database
