### ISSUE TITLE
Cart::search documentation out of date with 2.0.2

### ISSUE THREAD

**Issue by garrensweet** [Crinsane/LaravelShoppingcart#159]
We've recently updated from 1.2 to 2.0.2 and have noticed there are some significant changes (and improvements +1), however, we've noticed the documentation is a bit off.

For instance, the `Cart::search` example shows you passing in an array, but you've changed it in 2.0.2 to use a `Closure` instead:

    public function search(Closure $search)
    
This results in errors because previously (and according to the documentation), you supposed to pass in an array:

    Cart::search(array('id' => 1, 'options' => array('size' => 'L')));

**Comment by Crinsane** [comment]
Yes you're totally correct, the documentation is out of date. Please feel free to submit a PR to update the documentation!

**Comment by Crinsane** [comment]
Documentation has been updated!
