### ISSUE TITLE
Cart::search function consistency in 2.0.2

### ISSUE THREAD

**Issue by garrensweet** [Crinsane/LaravelShoppingcart#160]
In 2.0.2, the cart has moved to use the `Illuminate\Support\Collection` factory, which is great!

The problem is that the `search` function is not reliable in it's return:

    if($found->count() === 1) return $found->first();

    return $found;

What happens is that we either get an instance of `CartItem` or we get an instance of `Illuminate\Support\Collection`. Due to this, we have to check the instance of the class that we're returned in our code manually. 

Instead, I propose that an instance of `Illuminate\Support\Collection` is always returned. This way, we're sure of what we're getting back from the search and if we want the first item, we can call ->first() ourselves.

**Comment by Crinsane** [comment]
Hmm yes, I get what you mean. This might indeed be better... Feel free to submit a PR so I can push the change for the next tag.
