### ISSUE TITLE
Wiki needs missing info

### ISSUE THREAD

**Issue by gauravojha** [Crinsane/LaravelShoppingcart#163]
Hi,

Good software is rendered hard to use without sufficient info on it.
In your readme or the wiki, nowhere could I find some of the most obvious questions I have:
1. is this cart session safe? that is the items are preserved throughout one session?
2. is this cart user safe? (if it is session safe, then it is user safe I guess)
3. if the cart is not session or user safe, what happens if two different users add a product with the same 'id'?
4. is there no way to allocate the 'id' automatically? 

Please consider updating your Readme.

Regards
Gaurav

**Comment by Jeemusu** [comment]
1. The cart is preserved throughout the session. Obviously this will depend on how your session is set up in Laravel and the session driver you are using.
2. Yes
3. See 1 + 2.
4 : Could you describe a use case for automatically adding the id?

**Comment by gauravojha** [comment]
@Jeemusu 

From what I perceived (I may be wrong though), to add an item to cart, the "id" has to be passed as the first argument right? So what is this id? I mean if a user clicks on say "Add to Cart" for a prodcut with product id 2, so will this id=2 be passed as the first argument? I mean it is a fault on my end, but I am unable to clearly understand what this id is :(

**Comment by Crinsane** [comment]
@gauravojha The id is just the "identifier" you use in your application to identify the product that you add to the cart. Could be a simple integer id, could be a uuid, it really doesn't matter, as long as it's the unique "identifier" you use to identify the product.

**Comment by Crinsane** [comment]
The other questions are correctly answered by @Jeemusu. This package uses the session component of Laravel.

**Comment by gauravojha** [comment]
@Crinsane 
Thank you very much. Just one last thing. If this uses the session component, then if my session.php has a 'lifetime' of 120 minutes, so does that mean that once the user logs out, the cart will hold the items only for 120 minutes, and after that will destroy the cart, since the session exists no more?

**Comment by gauravojha** [comment]
I am reopening this issue. I have two sample users. I added an item using one of the users. Logged out. Then I logged in using the second user account. I can still view the items in the shopping cart. And I am pretty sure that both the accounts are different, as one is an account having admin privileges and the other is not.
