### ISSUE TITLE
Can not calculate the numbers above 1000

### ISSUE THREAD

**Issue by spacedyevest** [Crinsane/LaravelShoppingcart#166]
Hi, I run into issue with tax

Here is my code.

$tax = Cart::tax();
$cart_total = Cart::total();
$a = ($cart_total+$tax);

The result of $a is total price in cart plus $tax (I set tax = 3 in .../config/cart.php) and it work fine with number under 1000 but if the number is above or equal 1000 it run into issue.

e.g.
Total price is 100 the result of $a is 3 that is correct.
Total price is 1000 the result of $a is 31 that isn't correct.
The result I want is 1003.

**Comment by gauravojha** [comment]
Are you sure you are adding the items correctly? I wrote a simple code like

`   public function addToCart(Request $request, Product $product)
    {
        $this->validate($request, [
            'inputLength' => 'required|numeric|min:1',   
        ]);
        $contentOld = Cart::content();
        Debugbar::info($contentOld);
        Cart::destroy();
        Cart::add(['id'=>1, 'name'=>"Test", 'qty'=>1, 'price'=>1001]);
        $contentNew = Cart::content();
        $total = Cart::total();
        $tax = Cart::tax();

        Debugbar::info($contentNew);
        Debugbar::info($total);
        Debugbar::info($tax);
        return "Hi";
    }`

I can see the correct output as 
1,001.00
30.03

**Comment by spacedyevest** [comment]
Here is my full code

```
public function index(Request $request)
    {
		//add cart product
		if ($request->get('tmode') == 'addproduct')
		{
	        $product_id = $request->product_id;
	        $product = Product::find($product_id);
	        Cart::add(['id' => $product_id,
							'name' => $product->name,
							'qty' => 1,
							'price' => $product->price
						]
					);
					return redirect('/product');
    	}

	    //increment the quantity
	    if ($request->get('rowid') && ($request->get('increment')) == 1)
		{
			$row_id = $request->rowid;
			$item = Cart::get($row_id);

	        Cart::update($row_id, $item->qty + 1);
			return redirect('/product');
	    }

	    //decrease the quantity
	    if ($request->get('rowid') && ($request->get('decrease')) == 1)
		{
			$row_id = $request->rowid;
			$item = Cart::get($row_id);

	        Cart::update($row_id, $item->qty - 1);
			return redirect('/product');
	    }

		//clear cart
		if ($request->get('tmode') == 1)
		{
			Cart::destroy();
			return redirect('/product');
		}

		$tax = Cart::tax();
		echo $tax.'<br>';
		$cart_total = Cart::total();
		echo $cart_total.'<br>';
		$a = 0;
		$a = ($cart_total+$tax);
		echo $a.'<br>';
		$plustax=0;
		$cart = Cart::content();
		$products = Product::all();
        return view('product.main')
				->with('products',$products)
				->with('cart',$cart)
				->with('cart_total',$cart_total)
				->with('subtax',$plustax);
    }
```
Even if I use this code.

```
$vat = 3;
$newtotal = ($vat/100)*$cart_total;
echo $newtotal;
```

The result of $newtotal work fine with 1-999 but if it 1000 or more the result is 0.03.

**Comment by Crinsane** [comment]
I think there is something wrong with your code, because when I test this out like this:

```php
/** @test */
    public function it_can_calculate_all_values_for_a_price_above_one_thousand()
    {
        $cart = $this->getCart();

        $item = $this->getBuyableMock(1, 'First item', 1001.00);

        $cart->add($item, 2);

        $cartItem = $cart->get('027c91341fd5cf4d2579b49c4b6a90da');

        $cart->setTax('027c91341fd5cf4d2579b49c4b6a90da', 19);

        $this->assertEquals(1001.00, $cartItem->price);
        $this->assertEquals(1191.19, $cartItem->priceTax);
        $this->assertEquals(2002.00, $cartItem->subtotal);
        $this->assertEquals(2382.38, $cartItem->total);
        $this->assertEquals(190.19, $cartItem->tax);
        $this->assertEquals(380.38, $cartItem->taxTotal);

        $this->assertEquals(2002.00, $cart->subtotal);
        $this->assertEquals(2382.38, $cart->total);
    }
```

Everything checks out and the test passes.
