### ISSUE TITLE
how can the cart be available in another page

### ISSUE THREAD

**Issue by mikimaine** [Crinsane/LaravelShoppingcart#168]
after i add item to the cart , it is available in that page but not available in another page. 

For example if i add one product to the cart and the i wanna see what products are inside the cart it says there is no item in the product .....

how can i solve this, or am i missing something?

**Comment by gauravojha** [comment]
By another page do you mean a blade? 

Inside any blade, you can use something like {{ Cart::content()->count() }} to view the contents. The example I provide for example, shows the no. of items in the cart

**Comment by mikimaine** [comment]
i mean when i add to the cart i used this 
```
 $product = $this->product->eagerLoadWhere('product_translations',\Input::get('id'));
        Cart::add(['id'=>\Input::get('id'),'name'=> $product->product_translations[0]->name,'qty'=>1,'price'=>$product->price]);
         dd(Cart::content());
```
it shows me the product i have added but when i go to another controller method and do 
` dd(Cart::content());  `
it shows that the cart is empty  when i do this in blade  {{ Cart::content()->count() }}  it shows 0


in general the cart is only available in the added method at one time only ..... 
i guess the cart is not stored in the session.

**Comment by Crinsane** [comment]
It's the `dd()` method. This prevent the Laravel session to be written
