### ISSUE TITLE
Problems with Cart::associate()

### ISSUE THREAD

**Issue by joaomisturini** [Crinsane/LaravelShoppingcart#169]
Hello!

I'm trying to associate a model to a cart item like this:
`Cart::associate('Produtos', 'App')->add(...);`

However, the associate method throws an InvalidRowIDException, with the message "The cart does not contain rowId Produtos."

Is this a bug? Or I'm doing something wrong in my code?

**Comment by Crinsane** [comment]
Which version are you on?

**Comment by joaomisturini** [comment]
I'm on version 2.0

**Comment by Crinsane** [comment]
Okay, that sorry on my behalf, the documentation must be updated. In v2.0 the functionality was changes. You can either associate a model to the cartitem by making the model implement Buyable and use the model to add the item `Cart::add(Product::find(1), 1);` Or you can use the associate method where you first specify the rowId of the item and then the full FQN of the model, so something like:

```php
$cartItem = Cart::add('123abc', 'Product1', 1, 10.00);
Cart:associate($cartItem->rowId, \App\Product::class); // Or just Cart:associate($cartItem->rowId, 'App\Product');
```
