### ISSUE TITLE
copy between two cart instances

### ISSUE THREAD

**Issue by dipit2007** [Crinsane/LaravelShoppingcart#171]
Hi, I want to copy cart item from wishlist instance to actual cart instance.  Please help me.

Cart::instance('wishlist');

$rowId = $request->input('rowid');
          
$item = Cart::get($rowId);

Cart::remove($rowId);

Cart::instance('cart');

Cart::add($item,1);

But its not working. Whats wrong in above code?

**Comment by matbeard** [comment]
`Cart::add()` expects an array, but `Cart::get()` returns an object (with any options as a nested object), so you can't use it to add an item. Where you're currently attempting `Cart::add($item,1);` you should try something like:

`Cart::add($item->id, $item->name, $item->qty, $item->price, (array)$item->options)`

**Comment by dipit2007** [comment]
Thanks a lot.
