### ISSUE TITLE
Cart::search() must be an instance of Closure, array given

### ISSUE THREAD

**Issue by yourking** [Crinsane/LaravelShoppingcart#176]
So what I understand you can't search with an array parameter like it said in the example?

**Comment by Crinsane** [comment]
No, the documentation is out of date. You will have to pass the search method a closure, just like the search method on a regular Collection

**Comment by yourking** [comment]
Yes, i found it. Thank you

**Comment by stocksph** [comment]
just wondering how to pass the search method a closure?
as ive been stuck on the cart search method and it gives me an error "must be an instance of Closure, array given,"

any help is highly appreciated.
