### ISSUE TITLE
how to user find method 

### ISSUE THREAD

**Issue by tapos007** [Crinsane/LaravelShoppingcart#177]
new version find can not work please suggest me how it will be used

**Comment by mateusjatenee** [comment]
Do you mean the `search` method? You have to pass a closure.

**Comment by mateusjatenee** [comment]
@tapos007 https://laravel.com/docs/5.1/collections#method-search

**Comment by Crinsane** [comment]
@tapos007 I've updated the documentation for version 2. Please review it and see if this will clear things up for you.

**Comment by tapos007** [comment]
thanks Crinsane
