### ISSUE TITLE
search() must be an instance of Closure

### ISSUE THREAD

**Issue by stocksph** [Crinsane/LaravelShoppingcart#180]
I have this code to delete an item

$rowId = Cart::search(array('id' => Request::get('product_id')));
Cart::remove($rowId[0]);

but it gives me this error 

"Argument 1 passed to Gloudemans\Shoppingcart\Cart::search() must be an instance of Closure, array given, called in "

the code of deleting an item is not working, can someone guide or post it here the proper code to delete an item from the cart ?

any help is highly appreciated.

**Comment by djaca** [comment]
Are you using button or form to remove item from cart content?

**Comment by Crinsane** [comment]
@stocksph I've updated the documentation for version 2. Please review it and see if this will clear things up for you.

**Comment by stocksph** [comment]
@Crinsane Hi, thanks for responding to my concern. I was wondering where to find the documentation of version 2?

Looking forward to hear from you soon.

**Comment by Gameonn** [comment]
How to check whether the search result is empty or not?

`Collection {#296
  #items: array:1 [
    "5b9ea6f643e315f2af49fccf278f6c0d" => CartItem {#266
      +rowId: "5b9ea6f643e315f2af49fccf278f6c0d"
      +id: "9"
      +qty: 1
      +name: "Right"
      +price: 2.0
      +options: CartItemOptions {#267
        #items: array:3 [
          "artist_id" => "5"
          "artist_name" => "So Simple"
          "song_cover" => "http://52.33.48.169/photos/thumb/music/1472648567OK4w0CpOK3RLDCXyhXiRJ7G4gtBnED/png"
        ]
      }
      -associatedModel: null
      -taxRate: 21
    }
  ]
}`

**Comment by Crinsane** [comment]
Just check if the returned collection is empty or not.

**Comment by Gameonn** [comment]
@Crinsane Thanks for your response, I have checked the result count which solved my problem.

**Comment by ruhinacse14** [comment]
what's wrong with this code 
$rowId = Cart::search(function($key, $value) { 
                return $key->id == $request->product_id; });
i'm getting error like Undefined variable: request when i'm using laravel 5.2

**Comment by Crinsane** [comment]
You need to pass the request into the closures function scope with the use keyword.

**Comment by ruhinacse14** [comment]
after using this $rowId = Cart::search(function($key, $value) use($request){
                return $key->id == $request->product_id; 
}); 
i can't able to access this Cart::get($rowId[0]);
$rowId[0] return as Undefined offset: 0. 
where $rowId is 027c91341fd5cf4d2579b49c4b6a90da

**Comment by jaublanc-bobbies** [comment]
Same error. Can you solved this issue ?

**Comment by Crinsane** [comment]
@jaublanc-bobbies What is your code? What is the error? Need more information to help you.

**Comment by jaublanc-bobbies** [comment]
`$rowId = Cart::search(function($cartItem, $rowId) use($request){
	        	return $cartItem->id == $request->id_product;
	        });
$item = Cart::get($rowId[0]);`

My error is "Undefined offset: 0"

**Comment by Crinsane** [comment]
@jaublanc-bobbies Have you checked the actual content of the `$rowId` value?

**Comment by jaublanc-bobbies** [comment]
Yes it's a collection with items but I don't understand how use it with get() ?

**Comment by Crinsane** [comment]
You should be to use a Collection as an array. So that shouldn't be the problem. 
I can't seem to be able to reproduce this problem though....

**Comment by jaublanc-bobbies** [comment]
I'm sorry but I don't understand how can I get the qty value with my rowId variable ??

**Comment by Crinsane** [comment]
If you have the actual rowId hash, you can just use the `get($rowId)` method 
https://github.com/Crinsane/LaravelShoppingcart#cartget

**Comment by jaublanc-bobbies** [comment]
Now I get this error "array_key_exists(): The first argument should be either a string or an integer"

**Comment by Crinsane** [comment]
Can you send me a dump of the content of the rowId variable?

**Comment by jaublanc-bobbies** [comment]
Collection {#482 ▼
  #items: array:1 [▼
    "027c91341fd5cf4d2579b49c4b6a90da" => CartItem {#451 ▼
      +rowId: "027c91341fd5cf4d2579b49c4b6a90da"
      +id: "1"
      +qty: "1"
      +name: "Paris -> Lyon"
      +price: 49.0
      +options: CartItemOptions {#452 ▶}
      -associatedModel: null
      -taxRate: 21
    }
  ]
}

**Comment by Crinsane** [comment]
Ah ok, the key is actually not numeric.

Instead of `$rowId[0]` try `$rowId->first()`

**Comment by jaublanc-bobbies** [comment]
Same error with array_key_exists() ...

**Comment by Crinsane** [comment]
forget the `get` method. Look what the search method is returning. It's returning you the actual CartItem. So you don't have to fetch it again. `$rowId->first()` already gives you the CartItem, so you have access to the qty.

**Comment by jaublanc-bobbies** [comment]
Thanks a lot ! Finally working !!!

**Comment by TheNak976** [comment]
Hi, I followed this fix, but now I have this error:

`"Cannot use object of type Gloudemans\Shoppingcart\CartItem as array"`

here is my code:
`
        $item = ShopItem::where('item_code_id', '=', $id)->first();

        $item_in_cart = Cart::search(function ($cartItem, $rowId) use ($id) {
            return $cartItem->id == $id;
        });
        
        $rowId = $item_in_cart->first()->rowId;
        $content_in_cart = Cart::content();

        $newQt = $content_in_cart[$rowId]['qty'] - $item->item_quantity;

        if ($newQt <= 0) {
            Cart::remove($rowId);
        } else {

            Cart::update($rowId, $content_in_cart[$rowId]['qty'] - $item->item_quantity); //update quantity of specific item
        }
`
Can you help me please...
