### ISSUE TITLE
Model association not working as expected

### ISSUE THREAD

**Issue by santoshachari** [Crinsane/LaravelShoppingcart#181]
I see that the when we use `associate` method, it throws an error for missing second argument. The method does work when we associate to a cartItem: 

```
Cart::instance('subscriptions')->add($itemId, $_product_name, 1, $item->price, ['date' => $date, 'sessionId' => $sessionId, 'sessionName' => $sessionName])->associate('Subscription');
```

However the following doesn't work: 
```
foreach($content as $row)
{
    echo 'You have ' . $row->qty . ' items of ' . $row->subscription->name . ' with description: "' . $row->subscription->description . '" in your cart.';
}
```

**Comment by djaca** [comment]
Try namespace for second argument...

**Comment by Crinsane** [comment]
Which version are you using? I've updated the documentation for version 2, so please review it to see if anything has changed for you.
