### ISSUE TITLE
Config tax

### ISSUE THREAD

**Issue by absemetov** [Crinsane/LaravelShoppingcart#183]
Hello!
How to set tax=0?
Config file not generate.

**Comment by djaca** [comment]
Try to create manually...

cart.php
```
return [
    'tax' => 0,
];
```

**Comment by absemetov** [comment]
I create this file, in /config dir.

**Comment by absemetov** [comment]
Works fine, I readded Item, tax update

**Comment by filipveschool** [comment]
http://packalyst.com/packages/package/lutforrahman/ilacart

http://packalyst.com/packages/package/bnet/laravel-cart

Based or Built on the crinsane/shoppingcart package. These work also very good

**Comment by absemetov** [comment]
thanks

**Comment by Valonix** [comment]
I can`t undestand where i need to edit tax to 0. Can you help me?
