### ISSUE TITLE
Multiple taxes

### ISSUE THREAD

**Issue by filipveschool** [Crinsane/LaravelShoppingcart#192]
Hi,

I was wondering if  it is possible to Use multiple tax values?

Because in my country (Belgium) for example,

You have tax for books and different tax for pc's just an example.

Is this possible? Also is iT possible to configure taxes per country?

**Comment by Crinsane** [comment]
I believe you can set the tax rate after you added an item to the cart.

`Cart::add($item)->setTaxRate($yourTax);`
