### ISSUE TITLE
Can I get the count of many items from different Cart::instance ?

### ISSUE THREAD

**Issue by RichardOey** [Crinsane/LaravelShoppingcart#193]
how can i get all counts of the items from many instances ?
For example, 
I have to instance
Cart::instance('shop_id_7')->count()
Cart::instance('shop_id_8')->count()

but i should count it automatically and I can't write the name of the instance because i will get the instances name from database

**Comment by Crinsane** [comment]
Only way to do this currently is just loop over all instances and add the counts of all instance together.

**Comment by RichardOey** [comment]
Thank u mabro.. I will try
Thank u mabrooo
