### ISSUE TITLE
add items in array.

### ISSUE THREAD

**Issue by ilhamsabar** [Crinsane/LaravelShoppingcart#194]
i want add array in Cart item but not showed.

i try this code. 
Cart::add(['id' => $product_id, 'name' => $product->nama_barang, 'qty' => 1, 'price' => $product->harga_barang, 'image' => $product->foto_barang, 'brand' => $product->Brand_produk]);

**Comment by Crinsane** [comment]
Please supply me with more info, what version are you on, what is the output, did you get an error? etc.

**Comment by ilhamsabar** [comment]
not showed eror just not showed output this array data

**Comment by ilhamsabar** [comment]
i want ask again.
how to update qty in array data ?

**Comment by Crinsane** [comment]
Okay, well, first off, you have attributes in your array that are not supported by the package. `image` and `brand` are keys the package doesn't process. 

Next, what do you mean with 'no output'? What are you trying to output, how are you doing this?

I need more information to help you. Just saying "it doesn't do anything" isn't helping.

**Comment by ilhamsabar** [comment]
ok forget this.  
how to update quantity in array ? with ajax. 
my code 

@foreach($data as $ky => $row)
<select>
<option value=$row->rowid></option>

**Comment by Crinsane** [comment]
Like the documentation says: `Cart::update($rowId, $newQuantity);`
