### ISSUE TITLE
Update Properties

### ISSUE THREAD

**Issue by claudiusnascimento** [Crinsane/LaravelShoppingcart#195]
@Crinsane , Hi!

When a item cart is removed, the Cart instance dont update the $total property.

Ex:

item_1.price == $10;
item_2.price == $10;

total = $20;

Cart::remove(item_1.rowid);

total continues $20.

**Comment by claudiusnascimento** [comment]
@Crinsane , sorry. I get the kingpabel shopping card version.

Anyway, i fixed the issue puting this methods befere the return in remove() method:

$this->setTotal();
$this->setSubTotal();
 $this->setDiscount();

Can i close the issue or you hava some words?
Thanks

**Comment by Crinsane** [comment]
Since you're using another version, please contact that repo with the problem.
