### ISSUE TITLE
Model Relation Issue.

### ISSUE THREAD

**Issue by Wolrab1** [Crinsane/LaravelShoppingcart#197]
I'm using the model relation but I get the following error when trying to output data via the model on the view.

**Add to cart function**
```
 public function addItem(Request $request)
    {
        $product = Product::FindOrFail($request->item);

        Cart::add($product->id, $product->title, $request->quantity, $product->price)->associate('Product');

        return back();
    }
```

**Output in my view**

```
@foreach(/Cart::content() as $b)
    <tr>
       <td>
             {{ $b->model->title }}
       </td>
     <td>
@endforeach
```

**I get the error** 

> FatalErrorException in CartItem.php line 274:
> Class 'Product' not found

I'm using Laravel 5.1

My product model

```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use Buyable;
    
	public function categories()
    {
        return $this->belongsToMany('App\SubCategory', 'product_subcategory', 'product_id', 'category_id');
    }

}
```

**Comment by Crinsane** [comment]
You must provide to full namespace for the model for the `associate()` method. So in your case: `->associate('App\Product');`

**Comment by AntoineDessauges** [comment]
Same problem here but this solve my case. I think you should specify it in the description cause I try the same than Wolrab1. 
Thx for you work :) !

**Comment by AntoineDessauges** [comment]
Okay my bad this don't work but for pepole who search answer I found a solution here : https://github.com/Crinsane/LaravelShoppingcart/issues/169
