### ISSUE TITLE
Support for Laravel 5.3?

### ISSUE THREAD

**Issue by mpash** [Crinsane/LaravelShoppingcart#198]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework 5.3.x-dev

There seems to be no support for the 5.3 framework. I don't think much has changed in 5.2->5.3 in regards to this package. Is there anyway I can get this to work with 5.3?

Thanks!

**Comment by Crinsane** [comment]
I'll fix this in the composer.json soon. Thanks for the headsup

**Comment by mpash** [comment]
Thanks for the update! Let me know if you want me to test it out when you do update to 5.3.

**Comment by hassanazimi** [comment]
Thank for this nice package it works perfectly. Any easy ideas for handling the request asynchronously ?

**Comment by darylgeyerii** [comment]
@Crinsane any update on the Laravel 5.3 compatibility yet?

**Comment by mpash** [comment]
@darylgeyerii Support has been added.

**Comment by lolchaps** [comment]
help please, trying to install on fresh copy laravel 5.3

![cart](https://cloud.githubusercontent.com/assets/7602944/18071800/299ce2a2-6e8b-11e6-9219-abe0bf4a25e2.png)

**Comment by mpash** [comment]
Can you please attach a copy of your `composer.json` file? @lolchaps

**Comment by lolchaps** [comment]
@mpash
```
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.6.4",
        "laravel/framework": "5.3.*",
        "laravelcollective/html": "5.3.*"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~5.0",
        "symfony/css-selector": "3.1.*",
        "symfony/dom-crawler": "3.1.*"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "classmap": [
            "tests/TestCase.php"
        ]
    },
    "scripts": {
        "post-root-package-install": [
            "php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ],
        "post-install-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postInstall",
            "php artisan optimize"
        ],
        "post-update-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postUpdate",
            "php artisan optimize"
        ]
    },
    "config": {
        "preferred-install": "dist"
    }
}
```

**Comment by mpash** [comment]
@lolchaps You'll have to wait for Packagist to accept the changes for this package. Currently it is pulling in the old version that only supports ```illuminate/support: 5.1.*|5.2.*
illuminate/session: 5.1.*|5.2.*
illuminate/events: 5.1.*|5.2.*``` @Crinsane  can you update this? https://packagist.org/packages/gloudemans/shoppingcart

**Comment by darylgeyerii** [comment]
I am using the following in my composer.json file for now until a new version is released.

"gloudemans/shoppingcart": "dev-master"

**Comment by mpash** [comment]
@darylgeyerii That's a good quick fix for now. I've tried reaching out on twitter to @Crinsane so we'll just have to wait.

**Comment by lukepolo** [comment]
I tend to watch other packages that deal with carts, I feel bad for this package for the lack of a timely interaction . This is why I made my own version (with more features IMO) and would not usually do this but a month later this should have been done in 10 minutes, you should take a look at LaraCart.
#207 
And suggest @Crinsane to find a maintainer

**Comment by Crinsane** [comment]
Version 2.2.0 has been tagged which will work for Laravel 5.3

@lukepolo Great that you feel you have to promote your own package on here. And great that you have all the time in the world to maintain your packages, good for you! Laravel 5.3 has been for less then 2 weeks, so it can happen that no version for 5.3 has been tagged yet.

**Comment by mpash** [comment]
That's the thing with open source. You just have to be patient. We are all working towards making packages greater for Laravel so I encourage some patience and kindness moving forward.
