### ISSUE TITLE
Why have to use foward slash when adding to providers: "\Gloudemans\Sho..." - when namespace is declared without it, inside the composer.json?

### ISSUE THREAD

**Issue by vedtam** [Crinsane/LaravelShoppingcart#200]
Hi,

I am a bit confused, why do we use forward slash when declaring the provider:

> \Gloudemans\Shoppingcart\ShoppingcartServiceProvider::class

when in the src/composer.json we have it without:

>   "Gloudemans\\Shoppingcart\\": "src/"

Thanks!
vedtam

**Comment by Crinsane** [comment]
It's actually not needed, I believe in the past is was the way all service providers where specified, but you can just remove the leading slash, it makes no difference whatsoever.
