### ISSUE TITLE
Identifier after remove 

### ISSUE THREAD

**Issue by ujwaldhakal** [Crinsane/LaravelShoppingcart#201]
There are no identifier are remove like true or false after the instance is being deleted from the cart.

**Comment by Crinsane** [comment]
There is not much to 'identify'. If you pass an invalid/unknown rowid, a exception will be thrown, otherwise, the item is just pulled out of the cart content and discarded. No real need to or way to tell if this was successful, because we can be sure it was.

**Comment by ankitabhatti05** [comment]
@Crinsane I got the error of **Column not found: 1054 Unknown column 'identifier' in 'where clause' (SQL: select exists** at time of storing cart to the database.

I'm using this syntax **Cart::instance('shopping')->store(Auth::user()->id)**

Please help
