### ISSUE TITLE
How to use search()

### ISSUE THREAD

**Issue by chiennguyen93** [Crinsane/LaravelShoppingcart#212]
get $rowID from  $id. how?
$cart->search(function ($cartItem, $rowId) {
    return $cartItem->id === 1;
});

**Comment by Crinsane** [comment]
Exactly, if you want to search for a given id, just do:

```php
$cart->search(function ($cartItem, $rowId) {
    return $cartItem->id === 1;
});
```

Which will return you an array of rowIds of the result

**Comment by warmwhisky** [comment]
That just gives me Undefined variable: cart. It would be great to know how to set up $cart for the search

**Comment by Crinsane** [comment]
@warmwhisky There is nothing for you to setup. `search()`  is just a method you can call on the cart instance. So either you inject it, and do `$cart->search()` or you use the facade `Cart::search()`

**Comment by jefersonqlemos** [comment]
I want to do a search within an instance, only it does not return items! If you can help, I appreciate it.

Cart::instance('shopping')->search(function ($cartItem ,$rowId )
