### ISSUE TITLE
How get list of instances?

### ISSUE THREAD

**Issue by FubuBy** [Crinsane/LaravelShoppingcart#219]
How get list of instances?

**Comment by mateusjatenee** [comment]
Hi @FubuBy, not sure if you're still interested on this.  

Not sure how Rob's time is right now and his interest, and how I needed some immediate functions for my company I forked this project. It has the method you want (`Cart::instances()`). 

https://github.com/mateusjatenee/laravelshoppingcart

**Comment by FubuBy** [comment]
@mateusjatenee, thank you

**Comment by Crinsane** [comment]
If someone feels like submitting a PR for this, feel free to do so :)
