### ISSUE TITLE
How display count of items in view?

### ISSUE THREAD

**Issue by FubuBy** [Crinsane/LaravelShoppingcart#220]
I add items in cart, example 5 items. But when I reload page then display 0 items in view. I use Blade.
`{{ Cart::count() }}`
But when I add new items, then started from 5, but in displaied 0.
How display the number in the view?

**Comment by Crinsane** [comment]
I need more code to debug this

**Comment by leonfather** [comment]
I get this issue too. {{ Cart::count() }} show 0 in view

**Comment by Crinsane** [comment]
@leonfather Please open a new issue and give me steps to reproduce this.
