### ISSUE TITLE
Only two items 

### ISSUE THREAD

**Issue by Valonix** [Crinsane/LaravelShoppingcart#223]
Why i can add only two items in my cart? 
I press add product and in response see only two previos items. If i delete one, i can add another one. Some limit? 

` class CartController extends Controller
{
    /**
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function add(Request $request)
    {
        $product = Product::find($request->id);
        
        if(empty($request->quantity)){
            $quantity = 1;
        }else{
            $quantity = $request->quantity;
        }
        return response()->json(Cart::add($product->id, $product->title, $quantity, $product->price));
    }

    public function remove($rowId)
    {
        return response()->json(Cart::remove($rowId));
    }

    public function content()
    {
        return response()->json(Cart::content());
    }

    public function total()
    {
        return response()->json(Cart::total());
    }

    public function destroy()
    {
        return response()->json(Cart::destroy());
    }

    public function update(Request $requests)
    {
        return response()->json(Cart::update($requests->rowId, $requests->qty));
    }

} `

**Comment by Crinsane** [comment]
There should not be a limit or anything. Which session driver are you using?

**Comment by Crinsane** [comment]
And the response of the add method is not the cart content.

**Comment by Valonix** [comment]
I don`t know. i`v use Laragon 2.1.0.

**Comment by Valonix** [comment]
About response it doesn`t matter, the main goal is to save in backend. Other stuff in Angular app.

**Comment by Valonix** [comment]
Any idea? Earlier all works fine. I created backend side and frontend (Angular). Then i started to create markup from PSD and while I've working with checkout page i found this. =(

**Comment by Valonix** [comment]
If i use SESSION_DRIVER=file all works fine. Weird...

**Comment by bumbummen99** [comment]
https://github.com/Crinsane/LaravelShoppingcart/issues/48#issuecomment-50444846
