### ISSUE TITLE
How to change tax value?

### ISSUE THREAD

**Issue by kvlknctk** [Crinsane/LaravelShoppingcart#225]
my country using 0.18 tax. but laravelshopping cart used presumably 0.21.  i need to change tax value but there are not config file. 

thanx for reply.

**Comment by webwizo** [comment]
You can write `php artisan vendor:publish`.
You will find `cart.php` file into `config` folder

**Comment by quetool** [comment]
I have the same issue as kvlknctk but when ir run "php artisan vendor:publish" i get 

```
[ErrorException]                                               
The use statement with non-compound name 'Cart' has no effect 
```

**Comment by quetool** [comment]
@kvlknctk you have a /vendor/gloudemans/shoppingcart/src folder, inside of it is there a "cart.php" where you can change tax value and many oders things!

**Comment by webwizo** [comment]
We don't chnage values under vendor folder. If you update your package all values will be rest.

**Comment by quetool** [comment]
so what i have to do?

**Comment by webwizo** [comment]
`php artisan vendor:publish` should have worked. I am already using it and vendor:publish worked.

**Comment by quetool** [comment]
I'm gettin this error...

<img width="1369" alt="captura de pantalla 2016-10-11 a las 16 18 15" src="https://cloud.githubusercontent.com/assets/14978705/19284938/67d4bd42-8fce-11e6-8dd3-932cbaa6e56f.png">

Even when i do php artisan migrate

**Comment by webwizo** [comment]
Did you setup Cart alias into config/app.php?

Maybe Cart class not found.

**Comment by quetool** [comment]
Yes 

`'Cart' => Gloudemans\Shoppingcart\Facades\Cart::class,`

**Comment by quetool** [comment]
Maybe i should change for ?

`'Cart' => Gloudemans\Shoppingcart\Src\Facades\Cart::class`

**Comment by webwizo** [comment]
Well, it seems you did great 👍 

Look, when I wrote vendor:publish.

![Uploading Screenshot 2016-10-12 00.24.53.png…]()

**Comment by quetool** [comment]
Look, if i search for Cart.php this is what i found.

<img width="570" alt="captura de pantalla 2016-10-11 a las 16 27 56" src="https://cloud.githubusercontent.com/assets/14978705/19285309/e6152b96-8fcf-11e6-8753-8ba2c65fc9e9.png">

Maybe i am including the alias with a wrong path?

**Comment by webwizo** [comment]
No, Src is a folder path, but your class has NAMESPACE `namespace Gloudemans\Shoppingcart\Facades` so you have to call class by Namespace not folder source.

**Comment by quetool** [comment]
OK i did it, 

<img width="1324" alt="captura de pantalla 2016-10-11 a las 16 33 11" src="https://cloud.githubusercontent.com/assets/14978705/19285484/6ea7df8a-8fd0-11e6-96ac-672a2a9b5626.png">

i was adding "use Cart;" in a Controller, i don't know why, maybe I pasted there accidentally! Thanks!

**Comment by webwizo** [comment]
Good, you have figured it out 👍

**Comment by quetool** [comment]
Can you help me with this? https://github.com/Crinsane/LaravelShoppingcart/issues/229

**Comment by ChrisWMichel** [comment]
I want the admin user to be able to change the sales tax. This is what I added cart.php config:
'tax' => \DB::table('business_info')->select('sales_tax')->first(),

When refreshing the page to test it I get an error: 
Class 'DB' not found

Is there a better route to take in handling this type of function?

**Comment by Crinsane** [comment]
You can't access the db in the configuration. I guess right now you best option is to set the config in you AppServiceProvider or something at runtime with Config::set()

**Comment by ChrisWMichel** [comment]
Thank you.

**Comment by jahidhasanshuvo** [comment]
'tax' => \Illuminate\Support\Facades\DB::table('products')->value('tax'),

**Comment by jahidhasanshuvo** [comment]
is there any way that the tax value will be dynamic? I mean for different product tax value will be counted from respective product tax column.

**Comment by pakideveloper** [comment]
> You can write `php artisan vendor:publish`.
> You will find `cart.php` file into `config` folder

Thanks bhai jan

**Comment by DOKOLO823** [comment]
great
