### ISSUE TITLE
Cart gettin cleared on refresh

### ISSUE THREAD

**Issue by quetool** [Crinsane/LaravelShoppingcart#229]
Hi! i am new with this, but i have a question:

I saw when i restart, my Cart instance is getting cleared, is that normal? I mean, how can i do if I want to persist Cart instance between pages?

**Comment by webwizo** [comment]
Let me try first, I didn't notice :)

**Comment by webwizo** [comment]
OMG, it has cleared.

It shouldn't have cleared :(

**Comment by quetool** [comment]
I was crashing my head since this morning on this :S

**Comment by webwizo** [comment]
I'm figuring it out, thanks for pointing me out. I am working on a huge project, it could be my nightmare too :)

**Comment by quetool** [comment]
Im sorry! :( let me know!

**Comment by webwizo** [comment]
I checked, sometime it works between pages and sometimes cart cleared. I didn't find anything unusual code that cleared the session.

I think session is expiring too soon.

**Comment by webwizo** [comment]
It is happening sometimes, but I couldn't figure it out.

I checked the package code, I didn't find anything regarding session clear or empty cart.

**Comment by Crinsane** [comment]
@quetool did you use the `dd()` function anywhere while testing this? Because that will destroy the session.

**Comment by webwizo** [comment]
Oh, that's interesting. Thanks :)

**Comment by quetool** [comment]
@Crinsane nop, i never use dd()

**Comment by Crinsane** [comment]
@quetool So basically, you add something to the cart, you go to the cart overview page, and once you refresh it, it's empty?

**Comment by quetool** [comment]
@Crinsane yeah! that's right!

**Comment by quetool** [comment]
I mean, refreshing i just for explanation, but if you surf the site it happens too, I mean, if you click on a link to continue shopping for example...

**Comment by quetool** [comment]
I tried every type of session driver but nothing changes...

```
<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Default Session Driver
    |--------------------------------------------------------------------------
    |
    | This option controls the default session "driver" that will be used on
    | requests. By default, we will use the lightweight native driver but
    | you may specify any of the other wonderful drivers provided here.
    |
    | Supported: "file", "cookie", "database", "apc",
    |            "memcached", "redis", "array"
    |
    */

    'driver' => env('SESSION_DRIVER', 'database'),
```

**Comment by Crinsane** [comment]
I can't seem to reproduce this. Could you have a look at your session id and see if it changes with each request. Add something like `var_dump(Session::getId())` somewhere and see if it changes (because it should not)

**Comment by quetool** [comment]
Nop! it doesn't change!

**Comment by Crinsane** [comment]
I guess I need your code so I can debug this. Because I can't reproduce it.

**Comment by quetool** [comment]
I installed on localhost (with XAMPP) Laravel Framework version 5.2.45 and it is working just great! (with the deafult Laravel layout)

I do not know why with Laravel 5.3.18 it is happening this issue...
is there a way to uninstall your LaravelShoppingCart, clean laravel and reinstall it?

**Comment by quetool** [comment]
@Crinsane where can I send you the access to my server? because i can not figured it out!

**Comment by quetool** [comment]
@Crinsane maybe you wanna kill me but i figured out! I was including `<?php echo Cart::destroy(); ?>` in a header. I am ashamed! :(

**Comment by Crinsane** [comment]
Lol. Well, it happens. 😋 Long day? 😉

Glad you solved it!

**Comment by quetool** [comment]
Yes! i found it with grep :P

`grep -rnw '/var/www/laravel/' -e "Cart:"`
