### ISSUE TITLE
Cart::add returns NULL if a model is associated

### ISSUE THREAD

**Issue by Goldenblum** [Crinsane/LaravelShoppingcart#231]
`$cartadd = Cart::instance('cart')->add($product->id, $product->name, 1, $product->price, $attributes)->associate('\App\Modules\Products\Http\Models\Product');

        return json_encode($cartadd);`

If I associate the model to my Cart, the add does not return the last added item as it should.

`$cartadd = Cart::instance('cart')->add($product->id, $product->name, 1, $product->price, $attributes);

        return json_encode($cartadd);`

Removing the association fixes the issue and the correct information is returned.

Is this a bug?

**Comment by Crinsane** [comment]
Fixed by 143d51b22b365068b2308bb3732eadffb4df266c
