### ISSUE TITLE
how to setting database connection?

### ISSUE THREAD

**Issue by nevergear** [Crinsane/LaravelShoppingcart#235]

**Comment by neutt22** [comment]
i also would like to know since when a user logs out, the cart data disappears, too. Cart data should be stored in a file or database.

**Comment by Crinsane** [comment]
The cart is saved in the session. There is are methods for storing and restoring the cart to/from a database. See the documentation.

**Comment by neutt22** [comment]
Rookie question: where do i find the docs other than readme? Id really like to integrate this to my proj.

**Comment by nevergear** [comment]
on config/cart.php how to setting this `
    'database' => [

        'connection' => null,

        'table' => 'shoppingcart',

    ],` to save cart into database?

**Comment by neutt22** [comment]
@nevergear I've already done that part and `php artisan migrate` saw the table on my db but it's not getting populated with the cart items.

**Comment by michelmelo** [comment]
I have the same problem. I can not write to the database
