### ISSUE TITLE
Taxes Config

### ISSUE THREAD

**Issue by closerdesign** [Crinsane/LaravelShoppingcart#239]
Currently, I´m using the component with a Laravel 5.3 installation. However, as a result that I´m deploying using envoyer, every time I deploy the app composer update the config file of the module with the default value for taxes: 21.

Is there any way to manage that configuration from the app?

Thanks!

**Comment by Crinsane** [comment]
Publish the config to your app

**Comment by closerdesign** [comment]
Thanks for the answer!

I'm not sure what you mean. Is there any link in the documentation that you can provide me?

Thanks again!

**Comment by abr4xas** [comment]
Hey @closerdesign run this: `php artisan vendor:publish` :smile:

**Comment by closerdesign** [comment]
Awesome! Thanks!
