### ISSUE TITLE
Is this package compatible with LARAVEL 5.3 ??

### ISSUE THREAD

**Issue by cyberwolf888** [Crinsane/LaravelShoppingcart#244]
Can i use this package in laravel 5.3?

**Comment by eberkund** [comment]
Yes

**Comment by cyberwolf888** [comment]
@eberkund But when i use Cart::add() this package wont store my cart.
When i call Cart::content(); give me null value.
I'm trying to use session to store my cart.

**Comment by Crinsane** [comment]
Yes it works with Laravel 5.3 So it's probably something in your code or configuration.
