### ISSUE TITLE
Generate Invoices from Shopping Cart items

### ISSUE THREAD

**Issue by schuesslerf** [Crinsane/LaravelShoppingcart#245]
Whats a plugin that integrates nicely with your shopping cart to generate invoices after payment? Is there anything you can suggest?

**Comment by Crinsane** [comment]
I can't really. I think generating invoices is actually really something specific to your app.  Also there are a lot of steps between simply putting stuff in a cart session (this package) and generating an invoice. Checkout, payment, storing the order etc.
