### ISSUE TITLE
Non taxable products

### ISSUE THREAD

**Issue by ElectroWAR** [Crinsane/LaravelShoppingcart#248]
Hi, 
How to calculate cart total with non taxable or different tax (17.5%, 20%)  items. 

Thank you

**Comment by eberkund** [comment]
You can [set the tax rate](https://github.com/Crinsane/LaravelShoppingcart/blob/master/src/CartItem.php#L232-L243) on a `CartItem`

**Comment by core45** [comment]
Would be cool it it was in the documentation...

**Comment by Crinsane** [comment]
@core45 feel free to send a PR...
