### ISSUE TITLE
Support Twig Dynamic Properties

### ISSUE THREAD

**Issue by jonathandey** [Crinsane/LaravelShoppingcart#249]
I'm using this package as part of an OctoberCMS plugin. Both the plugin and this package work really well but OctoberCMS uses Twig for templates and the dynamic properties on the the CartItem model don't work with Twig.

According to Twigs documentation, to support dynamic methods the model must have an `__isset()` magic method as well as the `__get()` method, see: http://twig.sensiolabs.org/doc/recipes.html#using-dynamic-object-properties

Do you have any plans to add this Twig support?

**Comment by Crinsane** [comment]
No plans for this
