### ISSUE TITLE
Adding toJson method for CartItem

### ISSUE THREAD

**Issue by rorc** [Crinsane/LaravelShoppingcart#251]
Its very useful for process cart with Vue.js and pass CartItem to component:
`<cart-item :data="{{ $item->toJson() }}"></cart-item>`

And would be nice adding `__toString` method :)

Thanks =)

**Comment by Crinsane** [comment]
Not going to add this right now sorry, if you want this just do `cart-item :data="{{ json_encode($item->toArray()) }}"></cart-item>`
