### ISSUE TITLE
Add method has

### ISSUE THREAD

**Issue by rorc** [Crinsane/LaravelShoppingcart#254]
Hi)

Now its very inconvenience write all time:
```
$inCart = Cart::search(function($item) use ($product) {
    return $product->id == $item->id;
})->count();
```
Need shortcut `Cart::has($product)`

**Comment by eberkund** [comment]
What is your use case for this?

**Comment by rorc** [comment]
For iterate products and show button "already in cart" => go to checkout order, else "add to cart"

**Comment by Crinsane** [comment]
Feel free to submit a PR I can look at
