### ISSUE TITLE
Qty field is String not Number

### ISSUE THREAD

**Issue by matbeard** [Crinsane/LaravelShoppingcart#255]
If you do a die-dump of the cart content, you notice that the `qty` property is a String rather than an Integer.

This usually isn't a problem with PHP, but I'm serialising the collection and using it with an Ajax call. I know I can use `parseInt` as a simple fix, but I'd like to know why `qty` is returned as a String.

Thanks

**Comment by Crinsane** [comment]
I can't seem to recreate this.
