### ISSUE TITLE
got error when store to database

### ISSUE THREAD

**Issue by imansetyawan** [Crinsane/LaravelShoppingcart#256]
![39](https://cloud.githubusercontent.com/assets/21375700/20699799/cfad1f0c-b63b-11e6-88a3-33be01cfa55d.JPG)
![38](https://cloud.githubusercontent.com/assets/21375700/20699800/d096550a-b63b-11e6-9112-953e5023f4c7.JPG)
![40](https://cloud.githubusercontent.com/assets/21375700/20699808/dff087e6-b63b-11e6-842d-5e474afcc150.JPG)

plese help

**Comment by Crinsane** [comment]
I need more information to help you. What class is the code form? What is the line where the exception is thrown? etc. etc.

**Comment by imansetyawan** [comment]
get error when I execute addToCart method

**Comment by imansetyawan** [comment]
are you have example how to store it to database? @Crinsane
