### ISSUE TITLE
Cart contents contains incorrect tax information

### ISSUE THREAD

**Issue by eberkund** [Crinsane/LaravelShoppingcart#257]
When a Cart Item with a quantity greater than one is in the cart, the toArray method sets the value of the tax equal to the price of a single item multiplied by the tax rate. What is the purpose of having `$cartItem->tax` and `$cartItem->taxTotal`? Why not preferable just use taxTotal in this case? @Crinsane

**Comment by webdevwdc** [comment]
hello

**Comment by Crinsane** [comment]
hi

**Comment by Crinsane** [comment]
@eberkund I think we should just add the taxTotal to the toArray method. Feel free to create a PR :)
