### ISSUE TITLE
Cannot use object of type Gloudemans\Shoppingcart\CartItem as array

### ISSUE THREAD

**Issue by imansetyawan** [Crinsane/LaravelShoppingcart#258]
When I execute checkout get error like this. please help @Crinsane 
![42](https://cloud.githubusercontent.com/assets/21375700/20840798/06b8b330-b8e4-11e6-82ae-0e36363d351e.JPG)

and this is my Controller
![43](https://cloud.githubusercontent.com/assets/21375700/20840818/140129c8-b8e4-11e6-9ab7-d80a536fbe07.JPG)

**Comment by tuxdalinuxpenguin** [comment]
Take a look at line 79 "$cart['id']", I am guessing you probably had the oh crap moment already.

**Comment by Polly3919** [comment]
Maybe change the .env file 's' CACHE_DRIVER ?
...
CACHE_DRIVER=array
....
