### ISSUE TITLE
Events are not firing

### ISSUE THREAD

**Issue by erivas3649** [Crinsane/LaravelShoppingcart#259]
Hi, I'm using Laravel 5.3 and the events are not firing... Am i missing some configuration?
On my EventServiceProvider i've added some listeners like

`protected $listen = [
        'cart.add' => [
            'App\Listeners\CartAddedListener'
        ],
        'cart.update' => [
            'App\Listeners\CartUpdatedListener'
        ]
];`

Thanks in advance!

**Comment by cwprogger** [comment]
I faced the same problem. The thing is that event names in package documentation are misspelled. You should use ** cart.added** instead of **cart.add**, **cart.updated** instead of **cart.update**, etc.

**Comment by Crinsane** [comment]
Feel free to submit a PR @cwprogger 🙂
