### ISSUE TITLE
rowid or rowId?

### ISSUE THREAD

**Issue by Bulmer** [Crinsane/LaravelShoppingcart#264]
I have just recently upgraded from fac172e to 3ec0cef and came across this bug that was very difficult to trace. In the former version the Cart property was 'rowid' and it worked with no errors, but with the later version 'rowId' was needed (note capital 'I'). Was there a property name change here or was there a change within PHP that I missed?

**Comment by clemquinones** [comment]
i think it would be better if he uses snake_case,

**Comment by Bulmer** [comment]
I agree clemquinones, i'm just wondering when the change was made..
