### ISSUE TITLE
Persisting and restoring a Cart to/from the Database

### ISSUE THREAD

**Issue by kevosomi** [Crinsane/LaravelShoppingcart#265]
This is a great package and I really appreciate the work that has gone into it. Just a quick one, how do I persist the Cart to the database and restore it as need be? I can do it the long way of course, but why do it while probably there's some Laravel Magic in this package to do that easily! Let me know. Thanks in advance!

**Comment by kevosomi** [comment]
Found a solution in the package I believe its a case of missing documentation
In the cmd run php artisan vendor:publish
A migration file will be published. 
Run migration the have a function similar to the one below.
`public function storeCart($identifier){
Cart::store($identifier);
}`
Whenever a user hits the function above, their Cart will be saved to the database.
To restore the Cart to your session have the following function
`public function restoreCart($identifier){
Cart::restore($identifier);
}`
That's it. Good luck and happy coding!

**Comment by joeainsworth** [comment]
Thanks. I'm going to take a look at this!

**Comment by Braunson** [comment]
Any updates on the docs for this, just noticed the migration but no docs..

**Comment by Crinsane** [comment]
Docs are updated

**Comment by sath26** [comment]
the restore function returns null. although data are stored using store function. why? is it may be because i stored in the wrong way.
`  public function addItem($id)
    {
        $product=Product::find($id);

        $wishlist=Cart::add($id,$product->name,1,$product->price,['size'=>'medium']);

        Cart::instance('wishlist')->store($id);
        return back();
    }`
` public function index()
    {
        // $cartItems=Cart::content();
        $cartItems= Cart::restore('wishlist');
        return view('cart.index',compact('cartItems'));
    }`

one is to add and another is to retrieve. when i retrieve it returns null

**Comment by gram-o-phone** [comment]
I used this trait to have DB store/update functionality and have timestamps as well. It's helpful to have persistent cart for un/registered users, garbage collection for old carts etc.

    <php
    namespace App\Http\Controllers\Traits;

    use Gloudemans\Shoppingcart\Facades\Cart;

    Trait CartTrait
    {
        protected function storeCart ($uuid, $instance='default') {

            $created_at = null;
            if ( \DB::table('shoppingcart')->where('identifier', '=', $uuid)->where('instance', '=', $instance)->count() ) {
                $cartRow = \DB::table('shoppingcart')->where('identifier', '=', $uuid)->where('instance', '=', $instance)->first();
                $created_at = $cartRow->created_at;

                DB::table('shoppingcart')->where('identifier', '=', $uuid)->where('instance', '=', $instance)->delete();
            }

            Cart::instance($instance)->store($uuid);
            DB::table('shoppingcart')->where('identifier', '=', $uuid)->where('instance', '=', $instance)->update(
                [
                    'created_at' => $created_at ? $created_at : date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s")
                ]
            );
        }
    }
