### ISSUE TITLE
Invalid Price Format

### ISSUE THREAD

**Issue by vevionservices** [Crinsane/LaravelShoppingcart#267]
Hello,

The Price Format of the $cart->add is invalid.

It shows 9.5 instead of 9.50, where can i change it ?

Regards

**Comment by Polly3919** [comment]
Maybe.. Use this ?
str_pad(string,length,pad_string,pad_type)

<? $price=9.5; ?>
<table>
<th>{{ str_pad($i,4, '0',STR_PAD_RIGHT) }}</th>
</table>

**Comment by Crinsane** [comment]
How are you echoing it? Give some code so I can recreate the problem.

**Comment by abr4xas** [comment]
Maybe you can change this:

```php
'decimals' => 2,
```
To:

```php
'decimals' => 0,
```

In: [cart.php#L59](https://github.com/Crinsane/LaravelShoppingcart/blob/master/config/cart.php#L59)
