### ISSUE TITLE
Problems with store cart method

### ISSUE THREAD

**Issue by abr4xas** [Crinsane/LaravelShoppingcart#268]
Hi there, i have a little problem with `Cart::store()` perhaps, i don't know how to use it but, this is what i'm doing:

1) Add a product to my cart like:

```php
Cart::add([
      'id' => '293ad',
      'name' => 'Product 1',
      'qty' => 2,
      'price' => 9.99,
      'options' => [
          'size' => 'large'
     ]
]);
```

2) This is what i get using `Cart::content();`

```json
{
    "0f6524cc3c576d484150599b3682251c": {
        "rowId": "0f6524cc3c576d484150599b3682251c",
        "id": "293ad",
        "name": "Product 1",
        "qty": 2,
        "price": 9.99,
        "options": {
            "size": "large"
        },
        "tax": 2.0979,
        "subtotal": 19.98
    }
}
```

At this point everything works nice :+1:  :+1: 

Following [Getting and using $rowId](https://github.com/Crinsane/LaravelShoppingcart/wiki/Getting-and-using-$rowId)

```php
$id    = '293ad';
$rows  = Cart::content();
$rowId = $rows->where('id', $id)->first()->rowId;
```

Output: `0f6524cc3c576d484150599b3682251c` 

Using store method works nice using:

`Cart::store($rowId)` 

But in my data base have this:

![image](https://cloud.githubusercontent.com/assets/405484/21746476/b10a0902-d51c-11e6-84a5-61f2bccdb71f.png)

So, searching in [/src/Cart.php](https://github.com/Crinsane/LaravelShoppingcart/blob/master/src/Cart.php) the storage method uses `$content = $this->getContent()`  and `getContent()` says:

> Get the carts content, if there is no cart content set yet, return a new empty Collection

I don't understand why get a empty collection.

Can you help me with this?? :smiley:  :smiley:

**Comment by Polly3919** [comment]
Oops.. 20 days ago..
Did you solve the problems yet??

**Comment by abr4xas** [comment]
@Polly3919 nope :disappointed:

**Comment by Polly3919** [comment]
Hmm.. take a look :P
Cart::store($identifier)
$identifier -> is the cart's name

When I use function " Cart::add() " , it's basically save the items in the cart('default')
So when I want to store the cart('default') , I'll use " Cart::store('default') "

When I want to save the item to another cart , I'll use
Cart::instance('preferbuy') -> add('......');
Cart::store('preferbuy');

**Comment by Crinsane** [comment]
Yes, the add method will just add the item to the cart (store it in the session). The store method can be used to store the content of the cart in the database. And can be later retrieved by the unique identifier you pass to the store method.
