### ISSUE TITLE
LaravelShoppingcart Tax

### ISSUE THREAD

**Issue by devmahmed** [Crinsane/LaravelShoppingcart#272]
i don't wan't **tax** how can i remove

**Comment by Polly3919** [comment]
Modify it at /config/cart.php
you'll see 
[ 'tax' => 20]
change it to 0

**Comment by devmahmed** [comment]
<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Default tax rate
    |--------------------------------------------------------------------------
    |
    | This default tax rate will be used when you make a class implement the
    | Taxable interface and use the HasTax trait.
    |
    */

    'tax' => 21,

    /*
    |--------------------------------------------------------------------------
    | Shoppingcart database settings
    |--------------------------------------------------------------------------
    |
    | Here you can set the connection that the shoppingcart should use when
    | storing and restoring a cart.
    |
    */

    'database' => [

        'connection' => null,

        'table' => 'shoppingcart',

    ],

    /*
    |--------------------------------------------------------------------------
    | Destroy the cart on user logout
    |--------------------------------------------------------------------------
    |
    | When this option is set to 'true' the cart will automatically
    | destroy all cart instances when the user logs out.
    |
    */

    'destroy_on_logout' => false,

    /*
    |--------------------------------------------------------------------------
    | Default number format
    |--------------------------------------------------------------------------
    |
    | This defaults will be used for the formated numbers if you don't
    | set them in the method call.
    |
    */

    'format' => [

        'decimals' => 2,

        'decimal_point' => '.',

        'thousand_seperator' => ','

    ],

];

**Comment by devmahmed** [comment]
'tax' => 21,

i change this to 0 but not working

**Comment by devmahmed** [comment]
Its work thank you so much :)

**Comment by devmahmed** [comment]
if i want tax come from database so what can i do?

**Comment by Polly3919** [comment]
If u want wax come from database... 
The different tax is due to the Customers or the Products ?

**Comment by devmahmed** [comment]
I want customer change by own

**Comment by devmahmed** [comment]
For diffrent product or for all products

**Comment by Polly3919** [comment]
If u want to have different tax for each product then I'll prefer to ...
1. Add a new column named 'tax' in the database.
2. Add the Tax value in the additional place like ['size']

**Comment by devmahmed** [comment]
So how i calculate tax in cart

**Comment by devmahmed** [comment]
I want like i create diffrent tax when i add new product so its ask me wich tax you want to apply for this product in select drop down

**Comment by Polly3919** [comment]
1. If you add a new column in databse , you'll see what you just add in the create page.
2. So to add into cart , just modify the price you display.
Steps:
Step1 : Get the [Price],[Tax] value out of the database
Step2: Add to the cart with [Price] * [Tax]

**Comment by abr4xas** [comment]
@Polly3919 I do not agree to:

`Add the Tax value in the additional place like ['size']`

You can use: [setTax($rowId, $taxRate)](https://github.com/Crinsane/LaravelShoppingcart/blob/master/src/Cart.php#L330) to add the new tax to the item :smile:

**Comment by Polly3919** [comment]
@abr4xas  Thanks man :D

I'm still new in laravel , just trying to grow myself up by solving others questions.

Thank  you for the nice solution
