### ISSUE TITLE
Problem with Laravel 5.4

### ISSUE THREAD

**Issue by imranali1** [Crinsane/LaravelShoppingcart#273]
Hi, I've just updated Laravel to 5.4 & getting following error while adding `Gloudemans\Shoppingcart\ShoppingcartServiceProvider::class, `
to config/app.php file.

`FatalThrowableError in ShoppingcartServiceProvider.php line 14: Call to undefined method Illuminate\Foundation\Application::share()
`
Let me know if there's a quick fix?

**Comment by imranali1** [comment]
I've updated "LaravelShoppingCart" to 2.3 & it seems to be working fine now.
Thanks.

**Comment by SttephyBlz** [comment]
Thank you so much, this post helped a lot.
