### ISSUE TITLE
 Whoops, looks like something went wrong.  1/1 FatalErrorException in web.php line 31: Class 'App\Movie' not found

### ISSUE THREAD

**Issue by jaleeskhan** [Crinsane/LaravelShoppingcart#275]
I face this problem in my first laravel project 

Whoops, looks like something went wrong.

1/1
FatalErrorException in web.php line 31:
Class 'App\Movie' not found

while I create class in model

    <?php
    namespace App;
    use Illuminate\Database\Eloquent\Model;
    // laravel knows that since model is named Movie,
    // its database table name is "movies"
    class Movie extends Model
     {
	
    }
    ?>

**Comment by Crinsane** [comment]
This has nothing to do with this package.
