### ISSUE TITLE
Need help with quantity purchase

### ISSUE THREAD

**Issue by imranali1** [Crinsane/LaravelShoppingcart#276]
Hi,
I just wanted to know if its possible to add price per quantity basis.

Example: For each product if user purchase 2 per quantity price will be less than normal price.
If there's a discount on 2 qty purchase & user purchase 3 in a row, this way price will be calculated as discount for 2 & 1 with normal price.

I know there's way to update price using update method but how to calculate product sub-total this way?

I hope you understand the problem.

Please let me know if this is possible with current version?

Thanks a lot.

**Comment by Crinsane** [comment]
This is not possible with the current version of the package I'm afraid. So you'll have to write your own logic for this.

**Comment by imranali1** [comment]
Just one more question please. 

Let me know if its possible to update/set each product sub-total?

I know we can update each product price but is there anyway we can update product sub-total as well?

Thanks a lot.
