### ISSUE TITLE
How add one item twice with different options.

### ISSUE THREAD

**Issue by rakibulalam** [Crinsane/LaravelShoppingcart#282]
adding same product id twice in a different option. but it's by default merge the product in one row. But I want to add item different concern.

**Comment by Crinsane** [comment]
Adding two products with different options should add two rows.

**Comment by rakibulalam** [comment]
The user wants to purchase the same product with the different options. How do I manage it? When user add one item twice with different options. Cart showing only one item.

**Comment by Crinsane** [comment]
@rakibulalam I think you have some mistake in your code, because this has always been possible. Give me description how I can reproduce your problem on a fresh Laravel install.
