### ISSUE TITLE
Timestamps are not saved on stored carts

### ISSUE THREAD

**Issue by phaberest** [Crinsane/LaravelShoppingcart#283]
HI! I see you added `$table->nullableTimestamps();` in the `shoppingcart` table migration that comes with the package, but in fact they are always null.

Is there some additional configuration I didn't see?

I'm using stored carts to let the customer care see what's in the user cart and it may be useful to let them see timestamps, not essential though.

**Comment by Crinsane** [comment]
I just think that's something I've overlooked actually. 
So you didn't miss any configuration, it's just not setting the timestamps ;)

**Comment by MIDHUMARTIN** [comment]
I am not able to add items above price 885.Any reason
