### ISSUE TITLE
Hi Artisans, How I can get cart id in products page

### ISSUE THREAD

**Issue by IrsyadAdl** [Crinsane/LaravelShoppingcart#287]
Hi Artisans. I wanna build some logic inside of my products page. I wanna change the button when user has been clicked on that product. So my question is. How I know the data information of carted in my products page. For example: I wanna check if the product has the same id with the added cart. I will change the button color.

Just like this.

```
<button class="btn btn-{{ $product->id == $cart_item->id ? 'success' : 'default' }}
```
I look a round of it. But I am still can't do this. Anyone can help me. I will really apreciated that :)

Thanks 👍

**Comment by Crinsane** [comment]
I think your looking for the Cart::search method. That way you can search for the Product with the given ID and if you get something back (meaning it is in the cart) change the color of the button.

**Comment by IrsyadAdl** [comment]
But. This is in the product page. How I can get the rowId from it.

**Comment by Crinsane** [comment]
You don't need a rowId. With the search method you can just use the id, or name or whatever. You just want to know if the product with a given id (the one that you're viewing) is in the cart.

**Comment by IrsyadAdl** [comment]
Can you give me the example

**Comment by Crinsane** [comment]
Example of the search method is in the readme. It'll return a collection. So you can check if it's empty (product not in the cart) or not empty (product in the cart at least once)
