### ISSUE TITLE
How do I change 269,000.00 to 269000

### ISSUE THREAD

**Issue by irsyadadl** [Crinsane/LaravelShoppingcart#288]
Because the default format of the subtotal is have a comma, so I can't be increase the value. I have a couple shipping that I want to increase to subtotal. Later I will do something like this.
```
{{ Cart::subtotal() + 250000 }}
```
The way I need just get rid of the comma, (259000)

**Comment by IrsyadAdl** [comment]
Solve. I used strtr function php to do this.
```php
{{  strtr(Cart::total(), ',', '.') }}
```

**Comment by IrsyadAdl** [comment]
### Solved

This is what I did.
```
{{  preg_replace('/\s+/', '', strtr(Cart::total(), ',', " ")) }}
```

**Comment by garethdaine** [comment]
Ideally, this shouldn't output any cart totals, tax, subtotals as strings with commas.

**Comment by cwprogger** [comment]
Hi.
You can globally tune numbers format in the package config file `config\cart.php`:
```
'format' => [
    'decimals' => 0,
    'decimal_point' => '',
    'thousand_seperator' => ''
],
```

To publish the config file you can use this artisan command:
```
php artisan vendor:publish --provider="Gloudemans\Shoppingcar\ShoppingcartServiceProvider" --tag=config
```

Another way is to specify those settings as parameters of `total()` and `subtotal()` methods:
```
{{ Cart::total(0, '', '') }}
```
