### ISSUE TITLE
How to make Cart instance of my Model

### ISSUE THREAD

**Issue by IrsyadAdl** [Crinsane/LaravelShoppingcart#289]
I am trying to insert saveMany itu my db. But the erros was come like.
```php
Type error: Argument 1 passed to Illuminate\Database\Eloquent\Relations\BelongsToMany::save() must be an instance of Illuminate\Database\Eloquent\Model, instance of Gloudemans\Shoppingcart\CartItem given, called in C:\Users\Irsyad\Code\shopping\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Relations\BelongsToMany.php on line 727
```
Any help, really appreciate that 👍

**Comment by Crinsane** [comment]
Please give me more information (code) on what you're trying to achieve.

**Comment by IrsyadAdl** [comment]
No, this is has been solved. Now I wanna ask something about inheritance model. When I try to use decrement method. It's error.

My code like this.
```
foreach (Cart::content() as $item) {
    $item->decrement('stock', $item->qty);
}
```
Any solution ?

**Comment by Crinsane** [comment]
Your calling decrement on the CartItem, not on your model

**Comment by IrsyadAdl** [comment]
So. How to do that ?

I wanna decres the the product stock with the quantity of cart.

**Comment by Crinsane** [comment]
Get the model from the cart item and call decrement on the model.

**Comment by IrsyadAdl** [comment]
How to do that ?

**Comment by Crinsane** [comment]
It's in the readme

**Comment by IrsyadAdl** [comment]
No I don't see

**Comment by IrsyadAdl** [comment]
Can explain how ?

**Comment by IrsyadAdl** [comment]
You know what. I follow the tutorial, but this is not working like you do.

You said about the associate, but when I call, item->product->details, it doesn't return anything.
