### ISSUE TITLE
Fatal error: Allowed memory size of 134217728 bytes exhausted.

### ISSUE THREAD

**Issue by be-pranshu** [Crinsane/LaravelShoppingcart#290]
Hello,
I create a new setup with laravel 5.4 and install the package in wamp, I google and found some solution to increase the memory_limit in php.ini, and restart all services. I am using WAMP server with PHP Version 7.0.10. but it did not solve the problem.

```
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 262144 bytes) in G:\wamp64\www\webstore\vendor\laravel\framework\src\Illuminate\Container\Container.php on line 549
```
When I comment glodemans in app.php it work fine but when i comment out it gives error again.
```php

        // laravel cart
        Gloudemans\Shoppingcart\ShoppingcartServiceProvider::class
        
         // laravel cart
        'Cart' => Gloudemans\Shoppingcart\Facades\Cart::class,
```

**Comment by Crinsane** [comment]
Looks like a configuration problem on you system
