### ISSUE TITLE
rowId of last item added

### ISSUE THREAD

**Issue by warmwhisky** [Crinsane/LaravelShoppingcart#297]
Is it possible to get the rowId of the last added item?

**Comment by Crinsane** [comment]
The `add()` method returns a `Gloudemans\Shoppingcart\CartItem`.

**Comment by warmwhisky** [comment]
Thanks for clearing that up for me. I was trying to get the rowId so I can update it. Now I am getting "Trying to get property of non-object" when I execute the following to try and echo out the contents of the options to a form.

$cartItems = Cart::get($rowId);
        foreach ($cartItems as $cartItem) {}
        echo 'first_name = '.$cartItem->options->first_name;

**Comment by warmwhisky** [comment]
Hi. I have figured the last comment out. I didnt need the foreach loop.
