### ISSUE TITLE
Non-static method Gloudemans\Shoppingcart\Cart::total() should not be called statically

### ISSUE THREAD

**Issue by imperium2335** [Crinsane/LaravelShoppingcart#302]
Getting the above when I try to do any of the following:

\Gloudemans\Shoppingcart\Cart::total()
\Gloudemans\Shoppingcart\Cart::subtotal()
\Gloudemans\Shoppingcart\Cart::tax()

**Comment by Crinsane** [comment]
You should call those methods either on an instance of `Gloudemans\Shoppingcart\Cart` or use the Facade `Gloudemans\Shoppingcart\Facades\Cart`

**Comment by shahidkarimi** [comment]
@Crinsane please put running code in the document. 
Sine the Cart is the alias of
`'Cart' => Gloudemans\Shoppingcart\Facades\Cart::class,`

Still can't call ::add() method

**Comment by Crinsane** [comment]
@shahidkarimi Read my comment above, you've made a mistake in your code
