### ISSUE TITLE
Fail on calling associate after upgrading from 5.3  to 5.4

### ISSUE THREAD

**Issue by Payetus** [Crinsane/LaravelShoppingcart#304]
I have a product model in the namespace Tendee\Product

And I called the associate method on the Cart the following way:

`Cart::associate('Product', 'Tendee')->add($product->id, $product->name ,1, $product->price, array('size' => 'large'));`

After upgrading I get the following error:

UnknownModelException in Cart.php line 309:
The supplied model Tendee does not exist.

¿Is there a way I can make this work without implementing the buyable interface? I mean the associate mathod should still be working, right?

**Comment by Crinsane** [comment]
You can actually find the answer in the readme.

```php
// First we'll add the item to the cart.
$cartItem = Cart::add('293ad', 'Product 1', 1, 9.99, ['size' => 'large']);

// Next we associate a model with the item.
Cart::associate($cartItem->rowId, 'Product');

// Or even easier, call the associate method on the CartItem!
$cartItem->associate('Product');

// You can even make it a one-liner
Cart::add('293ad', 'Product 1', 1, 9.99, ['size' => 'large'])->associate('Product');
```

**Comment by Payetus** [comment]
What about maintaining backwards compatibility?

**Comment by Payetus** [comment]
Also i tried that and did not work cause can't specify the namespace

**Comment by Crinsane** [comment]
That's why there was a new major version (2.0.0)
