### ISSUE TITLE
Empty cart destroys stored database session?

### ISSUE THREAD

**Issue by warmwhisky** [Crinsane/LaravelShoppingcart#306]
When I empty the cart after restoring a cart it deletes it from the database... Is this normal?

I need to be able to restore carts after a client has paid. I store them using invoice_id as identifier. But Ideally I want a record of how the cart looked when they paid. Can I restore carts and then empty the cart without destroying the database stored version?

**Comment by warmwhisky** [comment]
Sorry about that. I didn't realise that the moment you restore the cart it gets destroyed from the database.
I am not sure of the implications, but I have managed to stop it doing it.
I found that if I comment out this line 
```
       $this->getConnection()->table($this->getTableName())
            ->where('identifier', $identifier)->delete();
```
 from vendor\gloudemans\shoppingcart\src\Cart.php

It keeps my stored session which is perfect for my needs right now.

Thanks for this great package!

**Comment by Crinsane** [comment]
@warmwhisky Yeah that's not really what the 'store/restore' functionality is written for. 
If you want to log/store the state of the cart when an order is made, I would suggest write your own logic for it (combination of Order & OrderLine, models/tables or something)
