### ISSUE TITLE
add a few items, and associate with the model

### ISSUE THREAD

**Issue by Batisska** [Crinsane/LaravelShoppingcart#308]
$request->all()
`array:3 [
  1 => array:4 [
    "id" => "94"
    "name" => "name"
    "price" => "554.83"
    "qty" => "1"
  ]
  2 => array:4 [
    "id" => "95"
    "name" => "name"
    "price" => "334.35"
    "qty" => "1"
  ]
  3 => array:4 [
    "id" => "96"
    "name" => "name"
    "price" => "298.35"
    "qty" => "1"
  ]
]`

`Cart::add($request->products)->associate('App/Product');`

`FatalErrorException in CartController.php line 192:
Call to a member function associate() on array`

How to associate with the model?

**Comment by Crinsane** [comment]
Well, as the error states, you get back an array (of CartItems). So just loop over the array and call associate on each CartItem

**Comment by Batisska** [comment]
Which makes sense to add an array of products, if then to connect all the same to make a loop?

**Comment by Crinsane** [comment]
Well that's the way to do it right now.  Nothing more I can do for you at the moment
