### ISSUE TITLE
Error when I increase or decrease product quantity from cart

### ISSUE THREAD

**Issue by emilsifu** [Crinsane/LaravelShoppingcart#309]
Hi!

I have the following code for cart :
```php
    public function cart() {
        //update/ add new item to cart
        if (Request::isMethod('post')) {
            $product_id = Request::get('product_id');
            $product = Product::find($product_id);
            Cart::add(array('id' => $product_id, 'name' => $product->name, 'qty' => 1, 'price' => $product->price));
        }

        //increment the quantity
        if (Request::get('product_id') && (Request::get('increment')) == 1) {
            //$rowId = Cart::search(array('id' => Request::get('product_id')));
            $rowId = Cart::search(function($key, $value) { return $key->id == Request::get('product_id'); });
            //$item = $rowId->first();
            Cart::update($rowId, $rowId->qty + 1);
        }

        //decrease the quantity
        if (Request::get('product_id') && (Request::get('decrease')) == 1) {
            //$rowId = Cart::search(array('id' => Request::get('product_id')));
            $rowId = Cart::search(function($key, $value) { return $key->id == Request::get('product_id'); });
            //$item = Cart::get($rowId->first());
            //$item = $rowId;
            //var_dump($rowId);
            Cart::update($rowId, $rowId->qty - 1);
        }
```

When I decrease or increase the quantity from cart, I get the following error:

> Exception in Collection.php line 1527: Property [qty] does not exist on this collection instance.

At var_dump($rowId) I get the following:

> object(Illuminate\Support\Collection)[229]
>   protected 'items' => 
>     array (size=1)
>       '027c91341fd5cf4d2579b49c4b6a90da' => 
>         object(Gloudemans\Shoppingcart\CartItem)[214]
>           public 'rowId' => string '027c91341fd5cf4d2579b49c4b6a90da' (length=32)
>           public 'id' => string '1' (length=1)
>           public 'qty' => int 1
>           public 'name' => string 'Mini skirt black edition' (length=24)
>           public 'price' => float 35
>           public 'options' => 
>             object(Gloudemans\Shoppingcart\CartItemOptions)[215]
>               ...
>           private 'associatedModel' => null
>           private 'taxRate' => int 21

Where am I wrong?

Thank you for answers!

**Comment by Crinsane** [comment]
Well, look at the error and look at the output of the var_dump.

You're trying to get the `qty` property from a Collection, and as you can see, you indeed are working with a Collection.
What I think you're missing here is the fact that `Cart::search()` returns you a Collection and not a CartItem.
