### ISSUE TITLE
How to lock rowId? the rowId will be changed when the option of item was modified

### ISSUE THREAD

**Issue by terrywamg** [Crinsane/LaravelShoppingcart#312]
/**
     * Generate a unique id for the cart item.
     *
     * @param string $id
     * @param array  $options
     * @return string
     */

    protected function generateRowId($id, array $options)
    {
        ksort($options);
        return md5($id . serialize($options));
    }

I noticed the rowId will be changed. but I hope the rowId is stable.  I hope the code like " return md5($id);"
Could you add a member for selection?
for example:

protected $rowIdStable=false;
    protected function generateRowId($id, array $options)
    {
    if($this->rowIdStable){
         return return md5($id);
      }else{
       ksort($options);
      return md5($id . serialize($options));
    }
}

**Comment by Crinsane** [comment]
This keeps returning, and I've often explained why the rowId changes when the options are changed. Please look at older issues about why this happens and why this won't change. :)
