### ISSUE TITLE
How does the `$item->subtotal` attribute work if not present in object? 

### ISSUE THREAD

**Issue by vedtam** [Crinsane/LaravelShoppingcart#317]
Hi,

Please forgive me if I am asking something obvious but I can't wrap my head around this.
When I loop trough my Cart object while getting: name, price, qty, etc, I can successfully get a value for '$row->subtotal' too, but when I check the object's blueprint there is no attribute for 'subtotal', so where does it come from? 

Thanks!

snippet:

```
@foreach($cart as $item)                  
{{dd($row)}}
  <tr>
    <td class="name"><a href="/product/{{ $item->id }}">{{ $item->name }}</a></td>
    <td>{{ $item->qty }} buc.</td>
    <td>{{ $item->subtotal }}</td>
  </tr>
 @endforeach
```

Output of the dd():

```
CartItem {#165 ▼
  +rowId: "4b1c5421e3cf96c0170d60222df7743f"
  +id: 165
  +qty: 2
  +name: "Smartphone XCDD"
  +price: 250.0
  +options: CartItemOptions {#166 ▶}
  -associatedModel: null
  -taxRate: 0
}
```

**Comment by Crinsane** [comment]
It is calculated on the fly by the CartItem object. Take a look at the source code, and especially the `__get` magic method. 
When the CartItem is transformed to an array, it will contain the subtotal btw.
