### ISSUE TITLE
I can't add more then 5 products in the cart

### ISSUE THREAD

**Issue by johnef** [Crinsane/LaravelShoppingcart#318]
I can't add more then 5 products in the cart Why??

**Comment by Crinsane** [comment]
I need more information to debug this. Give me steps on how to reproduce this.

**Comment by hastone** [comment]
I have the same issue, except that it's 8 products for me.
Everytime, when I add the 9th product, there is no error but my cart is empty.

**Comment by hastone** [comment]
Hi,
I still have the problem, have you found something about it ? It would really helped me.
Cordially.

**Comment by hastone** [comment]
Hi,
My issue is resolved. There was an issue with the database session driver. My sessions were destroyed when I added more than 8 products. I tried with the file session driver in my env file, and now it works.
