### ISSUE TITLE
Laravel can't convert the return value to JSON.

### ISSUE THREAD

**Issue by robertmylne** [Crinsane/LaravelShoppingcart#329]
UnexpectedValueException in Response.php line 450:
The Response content must be a string or object implementing __toString(), "object" given.

```
class CartController extends Controller
{
    public $cart;

    public function __construct(Cart $cart)
    {
        $this->cart = $cart;
    }

    public function addToCart()
    {
        return $this->cart->add('293ad', 'Product 1', 1, 9.99);
    }
}
```

I think the model needs to implement jsonable and have the method toJson.

This works btw.
```
$response = $this->cart->add('293ad', 'Product 1', 1, 9.99);
return response()->json($response);
```

**Comment by Braunson** [comment]
Put in a PR :) 

> https://github.com/illuminate/database/blob/master/Eloquent/Model.php

**Comment by Braunson** [comment]
Put in a PR :) 

_for reference_
> https://github.com/illuminate/database/blob/master/Eloquent/Model.php

**Comment by Crinsane** [comment]
I've added this in the latest commit, will tag new release soon.
