### ISSUE TITLE
How to get rowId

### ISSUE THREAD

**Issue by johnef** [Crinsane/LaravelShoppingcart#330]
I am try to remove item from the cart
Now in my view I try to do this
{!! Form::hidden('rowId', $row->rowid) !!}
and in the controller
```
public function remove(Request $request)
    {
        $rowId = $request->rowId;
        dd($rowId);
        Cart::remove($rowId);
        return Redirect::back();
    }
```

but I got empty value of `$rowId`

**Comment by Crinsane** [comment]
Please check the code in the form. Looks like you have `->rowid` instead of `->rowId`

**Comment by johnef** [comment]
@Crinsane 

Hay I just checked `->rowid` but the results of 
```
$rowId = $request->rowid;
dd($rowId);
```
was null

and the results of

```
$rowId = $request->rowId;
dd($rowId);
```
was "".

What I am doing wrong here
