### ISSUE TITLE
how to use funciton "store" and "restore" function.

### ISSUE THREAD

**Issue by linzi007** [Crinsane/LaravelShoppingcart#331]
I found there two function  "store" and "restore" in class Cart.php does not introduce in readme.  
May i ask you where to use this two function in order to persistent user's cart data into **DB** after Session expired. 
After that I can read user's cart data after a few weeks or session has expired.  
Expecting you reply!

**Comment by Crinsane** [comment]
New documentation was just added for this: https://github.com/Crinsane/LaravelShoppingcart#database

**Comment by JaviLopezM** [comment]
I have roblems when I create migrations.
