### ISSUE TITLE
Get  latest added item rowid of cart

### ISSUE THREAD

**Issue by sandipsanap** [Crinsane/LaravelShoppingcart#337]
If i added the item in the cart then i want to retrieve rowId of whatever item i have added into the cart lastly.

How can i get the rowId of recent added item?

**Comment by decadence** [comment]
`add` method returns `CartItem` so you can use:

```php
$item = Cart::add(1, 1, 1);
$item->rowId;
```

**Comment by sandipsanap** [comment]
yes it works i got the solution

Thank you so much
