### ISSUE TITLE
Price Column is too Small how to enlarge it from float to double?!

### ISSUE THREAD

**Issue by nouran77** [Crinsane/LaravelShoppingcart#339]
when i add price of a product equals to 2000. laravel give me this error 
SQLSTATE[01000]: Warning: 1265 Data truncated for column 'total' at row 1 (SQL: insert into `orders` (`total`, `delivered`, `user_id`, `updated_at`, `created_at`) values (2,000.00, 0, 2, 2017-06-03 16:48:32, 2017-06-03 16:48:32))

**Comment by errogaht** [comment]
i think you can create migration where you can change total column

**Comment by nouran77** [comment]
n
