### ISSUE TITLE
how to lock or check basket changes while user doing online payment

### ISSUE THREAD

**Issue by saeed-parsaee** [Crinsane/LaravelShoppingcart#342]
Is there any option to lock session basket or what is the best way to track basket changes while user is doing online payment.
As users have 15 minuets to complete online payments. if payments success i will store there session cart to database. but what if they change there session cart in this time?

**Comment by errogaht** [comment]
you can create separate model Order and OrderItem to handle orders and use cart only for cart - this my way

**Comment by Crinsane** [comment]
Exactly what @errogaht said
