### ISSUE TITLE
how to change credential name with own name

### ISSUE THREAD

**Issue by dianandria** [Crinsane/LaravelShoppingcart#343]
i have some problem when i try using `Cart::add()` with my own name, and it always returning 

> undefined index id, name, etc

i tried like this : 
`Cart::add('user_id'=>$data['user_id'], 'book_name'=> $data['book_name'])`

how to fix my case, besides changing in the vendor files

hope you guys can help me

thanks btw

**Comment by Crinsane** [comment]
Please see the readme on how to use this package.
