### ISSUE TITLE
Insert Cart::content() into multiple Row From View Using Eloquent Laravel 5.*

### ISSUE THREAD

**Issue by lampsoft** [Crinsane/LaravelShoppingcart#347]
How can I insert Multiple Row of Cart:: content() in Laravel 5.
I'm using Crinsane/LaravelShoppingcart for my cart, however, when you click on proceed to payment, I want the user to fill Customer details like (Terminal ID, sale date, and customer name. But I'm having issue with inserting Cart::(Content) into my database (I dont want to insert instance. I like to break the cart down to my database column. example, if someone pick like 2-5 items, I want it to be inserted to my db, with each item in each row. I've break the Cart::content down in my view, but I need to be able to use Laravel to insert multiple row based on the number of Items selected. **PLEASE NOTE: IF I ONLY ADD ONLY ONE ITEM TO CART, I'M ABLE TO INSERT TO DATABASE, IT'S ONLY WHEN THE ITEM IN CART IS MORE THAN ONE THAT I HAVE ISSUE WITH.**
Below is my Controller

```
public function store(SalesCreateRequest $request)
    {
$counter= $request['counter'];
    for ($i = 0; $i < count($counter); $i++) {
Sale::create([
             'terminal_id' => $request['terminal_id'],
             'customer_name' => $request['customer_name'],
             'unit_price' => $request['unit_price'],
             'total_price' => $request['total_price'],
             'tax' => $request['tax'],
             'quantity' => $request['quantity'],
             'product_name' => $request['product_name'],
             'sale_date' => $request['sale_date'],
             'rowId' => $request['rowId']
    ]);
    }
    return redirect('shop');
}

```
My CheckOut Page (View):

```
<div class="panel-heading">Customer Detail</div>
    <div class="panel-body">
       @if (sizeof(Cart::content()) > 0)
    {!! Form::open(['method'=>'POST', 'action'=> 'SalesController@store','files'=>true]) !!}
       {!! Form::text('counter', $counter=Cart::content()->groupBy('id')->count(),  ['class'=>'form-control'])!!}
        @foreach (Cart::content() as $item)
        <div class="form-group">
   {!! Form::label('product_name', 'Product Name:') !!}
  {!! Form::text('product_name', $item->name,  ['class'=>'form-control'])!!}                     </div>
          <div class="form-group">
    {!! Form::label('quantity', 'Quantity:') !!}
  {!! Form::text('quantity', $item->qty,  ['class'=>'form-control'])!!}
         </div>
       <div class="form-group">
  {!! Form::label('unit_price', 'Unit Price:') !!}
  {!! Form::text('unit_price', $item->price,  ['class'=>'form-control'])!!}
                     </div>
       <div class="form-group">
   {!! Form::label('rowId', 'Row ID:') !!}
   {!! Form::text('rowId', $item->rowId,  ['class'=>'form-control'])!!}
       </div>
    <div class="form-group">
           {!! Form::label('tax', 'Tax:') !!}
        {!! Form::text('tax', $item->tax,  ['class'=>'form-control'])!!}
           </div>
            <div class="form-group">
      {!! Form::label('total_price', 'Sub Total:') !!}
      {!! Form::text('total_price', $item->subtotal,  ['class'=>'form-control'])!!}
           </div>
          @endforeach

                     @endif
         <div class="form-group">
       {!! Form::label('terminal_id', 'Terminal ID:') !!}
       {!! Form::text('terminal_id', null, ['class'=>'form-control'])!!}
                       </div>
                       <div class="form-group">
       {!! Form::label('customer_name', 'Customer Name:') !!}
   {!! Form::text('customer_name', null,  ['class'=>'form-control'])!!}
                        </div>
                      <div class="form-group">
          {!! Form::label('sale_date', 'Sale Date:') !!}
         {!! Form::text('sale_date', null, ['class'=>'form-control'])!!}
                        </div>
                        <div class="form-group">
          {!! Form::submit('Check Out', ['class'=>'btn btn-primary']) !!}
                       </div>
         {!! Form::close() !!}
`

```

Please can anyone help me out.

**Comment by Crinsane** [comment]
@lampsoft In your view you use a foreach to loop over all items in the cart and you create input's for them.
But say you have 3 items in the cart, now you're creating 3 form inputs with the name 'product_name', and 3 inputs with the name 'quantity'.

When you post this form to your server, only the last set of inputs (of the last item in your cart) will be available in your controller.
So what you need to do is use an array for the name, so give all 'product_name' inputs: `name="product_name"` and in your controller you have to loop over those arrays of input values and add each row separately.

**Comment by lampsoft** [comment]
Thanks Crinsane,
I've corrected this but still gettting error ::
Below is my new view::
`<div class="panel-heading">Customer Detail</div>
<div class="panel-body">
@if (sizeof(Cart::content()) > 0)
{!! Form::open(['method'=>'POST', 'action'=> 'SalesController@store','files'=>true]) !!}
{!! Form::text('counter', $counter=Cart::content()->groupBy('id')->count(),  ['class'=>'form-control'])!!}
@foreach (Cart::content() as $idx => $item)
  <div class="form-group">
  {!! Form::label("product_name[$idx]", 'Product Name:') !!}
  {!! Form::text("product_name[$idx]", $item->name,  ['class'=>'form-control'])!!}
  </div>
  <div class="form-group">
  {!! Form::label("quantity[$idx]", 'Quantity:') !!}
  {!! Form::text("quantity[$idx]", $item->qty,  ['class'=>'form-control'])!!}
  </div>
  <div class="form-group">
  {!! Form::label("unit_price[idx]", 'Unit Price:') !!}
  {!! Form::text("unit_price[idx]", $item->price,  ['class'=>'form-control'])!!}
  </div>
  <div class="form-group">
  {!! Form::label("rowId[$idx]", 'Row ID:') !!}
  {!! Form::text("rowId[$idx]", $item->rowId,  ['class'=>'form-control'])!!}
  </div>
  <div class="form-group">
  {!! Form::label("tax[$idx]", 'Tax:') !!}
  {!! Form::text("tax[$idx]", $item->tax,  ['class'=>'form-control'])!!}
  </div>
  <div class="form-group">
  {!! Form::label("total_price[$idx]", 'Sub Total:') !!}
  {!! Form::text("total_price[$idx]", $item->subtotal,  ['class'=>'form-control'])!!}
  </div>
@endforeach
@endif
<div class="form-group">
  {!! Form::label('terminal_id', 'Terminal ID:') !!}
  {!! Form::text('terminal_id', null, ['class'=>'form-control'])!!}
</div>
<div class="form-group">
  {!! Form::label('customer_name', 'Customer Name:') !!}
  {!! Form::text('customer_name', null,  ['class'=>'form-control'])!!}
</div>
<div class="form-group">
  {!! Form::label('sale_date', 'Sale Date:') !!}
  {!! Form::text('sale_date', null, ['class'=>'form-control'])!!}
</div>
<div class="form-group">
  {!! Form::submit('Check Out', ['class'=>'btn btn-primary']) !!}
</div>
{!! Form::close() !!}`

And my new Controller::
`public function store(SalesCreateRequest $request)
    {
        \DB::transaction(function($request) {

            $counter = Input::get('counter');
            for ($i = 0; $i < count($counter); $i++) {
                Sale::insert([
                    'terminal_id' => $request["terminal_id[$i]"],
                    'customer_name' => $request["customer_name[$i]"],
                    'unit_price' => $request["unit_price[$i]"],
                    'total_price' => $request["total_price[$i]"],
                    'tax' => $request["tax[$i]"],
                    'discount' => $request["tax[$i]"],
                    'quantity' => $request["quantity[$i]"],
                    'product_name' => $request["product_name[$i]"],
                    'sale_date' => $request["sale_date[$i]"],
                    'rowId' => $request["rowId[$i]"]
                ]);
            }
       }); return redirect('shop');
    }`

But i'm getting::
**Cannot use object of type Illuminate\Database\MySqlConnection as array**

Please Help!
