### ISSUE TITLE
Shopping Cart wont ::destroy()

### ISSUE THREAD

**Issue by NicolasVanhecke** [Crinsane/LaravelShoppingcart#357]
I have had a strange bug lately (or I just noticed it lately), where the Cart wont `destroy()` properly. 
I cannot find out why or when, because it is completly random. When I try it it works, 5 or even 10 times in a row, but I still get double orders from people who order the same again because their cart is not empty yet.
When I was trying it on my client's computer it did not destroy the cart once, in 3 tries. When I am home and run the project locally it keeps destroying like it should. On the live site, at home on my computer, it is somewhat random. It destroy properly more then it doesn't..

Have you encountered this before? What can I do about this?

PS: I haven't wrote the source code myself, but I can tell where the Cart is being build, looped for the items and destroyed. The code looks fine. 
Also this is in Laravel 5.0

Thanks

**Comment by Crinsane** [comment]
I'm sorry, Laravel 5.0 isn't supported anymore

**Comment by NicolasVanhecke** [comment]
Still it should work with the older package, right? I havent update the Crinsane/LaravelShoppingcart either.
