### ISSUE TITLE
Cart not found error on server

### ISSUE THREAD

**Issue by sampat-rebelute** [Crinsane/LaravelShoppingcart#358]
Hello i am using this package in laravel 5.3. On Local server it is working fine but on server i am getting the error like Cart not found.

I am also facing the one more problem in local server i.e. Cart::destroy() not working properly sometime.i observed this many times.

What will be the issue?

**Comment by Crinsane** [comment]
Please give me more information on how to reproduce the problem.

**Comment by sampat-rebelute** [comment]
But problem is here cart package is working on local server (local machine) with 8Gig ram and ubuntu 16 nginx server, but when we uploaded source code on live environment at that time i am getting the issue "Cart not found". 

try {
            // search term for to fetch the related matching domains 
            $cartContent = [];
            foreach (Cart::content() as $content) {
                $cartContent[] = $content->name;
            }
            if (!empty($searchDomainTerm)) {
                // Some Logic
                }
            }
        } catch (Exception $e) {
            return response()->json(['message' => $e->getMessage()]);
        }

now it is handling exception stating => {"message":"Class cart does not exist"}

**Comment by Crinsane** [comment]
You must have a configuration error or maybe some old configuration cached or something, because I'm sure this isn't a problem with this package, because it works ok for thousands of people :)
