### ISSUE TITLE
Add to Cart without redirect Cart 

### ISSUE THREAD

**Issue by lampsoft** [Crinsane/LaravelShoppingcart#359]
Please How can I add to cart without redirecting to Cart. I just want my Product to be in cart if I click on Add to Cart instead of Redirecting me to cart?

**Comment by mohamad4j** [comment]
i think you can use ajax request to add or remove a record in your cart

**Comment by Crinsane** [comment]
Use an AJAX request

**Comment by gomesiago** [comment]
Can you give an example of how this AJAX request would work? I am also having problems with `return back ();` when the routes are `POST`.

**Comment by Crinsane** [comment]
There are enough resources online. Just make sure your route is in the web middleware and not the api middleware, because that last one is stateless, so has no session.
