### ISSUE TITLE
Gloudemans \ Shoppingcart \ Exceptions \ ShoppingcartInvalidRowIDException

### ISSUE THREAD

**Issue by lstables** [Crinsane/LaravelShoppingcart#36]
I'm getting the above message when trying to remove an item from my cart.

< a href="/cart/remove/{{ $cart_item->rowid }}">Remove</a>

Which is wrapped in a foreach that comes from:

$carts = Cart::content();

And i'm adding content like so:

$cartContents = Cart::add(array('id' => randomNumber(), 'name' => $input['product_name'], 'qty' => 1, 'price' => $price));

But when I do Cart::remove($cart_item->rowid) i get the above error?

Any idea's?

**Comment by hexencoded** [comment]
Try this:
Cart::destroy();

Then:
Cart::add(array('id' => randomNumber(), 'name' => $input['product_name'], 'qty' => 1, 'price' => $price, 'delivery' => $input['delivery']));

Finally:
Cart::remove($id);

**Comment by Crinsane** [comment]
@hexencoded Where dit the `$id` variable come from?

**Comment by hexencoded** [comment]
In my case: 
Cart controller - http://pastebin.com/MRZY9sqM

id getting from HTML:
<td><a href="#" data-loading-text="Удаление..." data-id="{{{ $row->id }}}" class="cart-remove"><i class="fa fa-trash"></i> Удалить</a></td>

Javascript:
$('.cart-remove').on('click', function () {
        var btn = $(this);
        btn.button('loading');

        var id = $(this).data('id');

        $.ajax({
            url: "/cart/" + id + "/remove",
            type: 'DELETE',
            success: function(data) {
                 $('#cart').text('Корзина (' + data.data.count + ')');
                btn.button('reset');
            }
        });
    });

Removing items does not working correctly.

**Comment by Crinsane** [comment]
@hexencoded 

Okay, I see your problem. What you're misunderstanding is the fact that `$row->id` is not the same as `$row->rowId`.

The `id` is just the ID you set yourself when you added the item to the cart. Usually the primary key of the item. The `rowId` is a unique ID, generated by the cart when you add an item. It's used to identify unique items in the cart. You can have multiple rows in the cart with the same `id` but their `rowId` will be different (because they have different options for instance)

What you want to do is in your HTML snippet:

```html
<td>
    <a href="#" data-loading-text="Удаление..." data-id="{{{ $row->rowId }}}" class="cart-remove"><i class="fa fa-trash"></i> Удалить</a>
</td>
```

**Comment by hexencoded** [comment]
Thanks! Now this work perfectly.

**Comment by elbakly** [comment]
Just an update here for those who are in development when you use Cart::destroy(); or Cart::remove(); or any of cart functions you cant follow that by dd(); and expect it to be updated in your session

**Comment by MicroDreamIT** [comment]
@Crinsane  cart remove is not working properly, http://46.101.177.93/cart, 
in here two plan or  two can not co-exist. i dont know why this is happening....

**Comment by joshuahadi** [comment]
Hi, I use integer for 'total' column in my database. I put **'total'=>Cart::subtotal()** in my controller  and what I get in my database for this 'total' column is only 1 digit of it`s front value (for example it should get 500000, but it only get 5). How to overcome this problem? what to change?thanks a lot

**Comment by bagmorgirish** [comment]
Error:- Class Gloudemans\Shoppingcart\Cart does not exist

I am already added "use cart;" in controller
and i am currently use laravel 5.4 version
@Crinsane please suggest me something for that

**Comment by zahidshuvo12** [comment]
Hi @Crinsane , I use integer for 'total' column in my database. I put 'total'=>Cart::subtotal() in my controller and what I get in my database for this 'total' column is only 1 digit of it`s front value (for example it should get 500000, but it only get 5). How to overcome this problem? what to change?thanks a lot

**Comment by TumiDebrah** [comment]
Hi @Crinsane,  it would be really awesome if you added conditions such as discounts,coupons.sales etc.

**Comment by inzi-niloy** [comment]
I'm getting this msg : Using version ^2.5 for gloudemans/shoppingcart
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for gloudemans/shoppingcart ^2.5 -> satisfiable by gloudemans/shoppingcart[2.5.0].
    - Conclusion: remove laravel/framework v5.7.3
    - Conclusion: don't install laravel/framework v5.7.3
.
.
.
 What should I do....

**Comment by nazmulhaquep** [comment]
@Crinsane I add shipping cost like: 
$delivery = 30;
$count = Cart::count();
        if($count==0){
        $data['options']['delivery'] = $delivery;
        }
        Cart::add($data);
When i print_r(Cart::content()); It shows delivery charge but delivery charge don't added with the Cart::total(); How can i add this? Need help!

**Comment by rahim3070** [comment]
I have face the same problem. Additional # will be added after row_id for first row of my Gloudemans Shopping cart on update. What can I do ?

My demo url is - http://localhost/magic_shop/cart?_token=De1K9HIxNXk7o9AqdxfeHQJGz2kCx8F0tURtAoFl&qty=1&row_id=f754bf78868fbd1a07e2607314283270#

**Comment by zakir7dipu** [comment]
Hi. I am facing a problem. I want to use this shopping cart in one restaurant business. But in this case, my product have my extra item, like I want to add cart a pizza but with this pizza I need  extra chis, extra chicken ect. Now how to add cart multiple extra item with one product item?

**Comment by sujilkumarkm** [comment]
${{ Session::get('coupon')['balance'] }} 

This is the correct use in blade file , before instead of "Session" I used "Cart" that's why it thrown error, now it's working perfect


Controller code given below for adding coupon.

public function Coupon(Request $request)
    {
        $coupon = $request->coupon;
        $check = DB::table('coupons')->where('coupon',$coupon)->first();
        if($check)
        {
            Session::put('coupon',[

                'name' => $check->coupon,
                'discount' => $check->discount,
                'balance' => Cart::Subtotal()-$check->discount,

                ]);

                $notification=array(
                'messege'=>'Coupon applied successfully',
                'alert-type'=>'success'
                 );
               return Redirect()->back()->with($notification);

            

        }
        else
        {
            $notification=array(
                'messege'=>'Invalid coupon',
                'alert-type'=>'warning'
                 );
               return Redirect()->back()->with($notification);
        }
    }
    
    
    Blade part.
    
    <ul class="list-group col-lg-4" style="float: right;">
							<li class="list-group-item">Subtotal : <span style="float: right;">${{ Session::get('coupon')['balance'] }}</span></li>
							<li class="list-group-item">Coupon : <span style="float: right;">525</span></li>
							<li class="list-group-item">Shipping Charge : <span style="float: right;">525</span></li>
							<li class="list-group-item">Vat : <span style="float: right;">525</span></li>
							<li class="list-group-item">Total : <span style="float: right;">525</span></li>
							
						</ul>
