### ISSUE TITLE
Add function

### ISSUE THREAD

**Issue by leonfather** [Crinsane/LaravelShoppingcart#360]
Hello i need one information, When i execute Cart::add($productId, 'teest',1,'98.43');
This information is saved in session ?

**Comment by leonfather** [comment]
6 days ago, Any help please?

**Comment by Crinsane** [comment]
Yes it is

**Comment by leonfather** [comment]
How Can i change session to redis?

**Comment by Crinsane** [comment]
This package uses the Laravel session. So if you change the Laravel configuration to use Redis, the data for this package is also saved in Redis.
