### ISSUE TITLE
Cart prices updating

### ISSUE THREAD

**Issue by fearrr** [Crinsane/LaravelShoppingcart#361]
What to do with the content of the basket? 
If the user added the item to the basket, and then the site owner updated the price of the goods, it will not be updated in the basket.

**Comment by Crinsane** [comment]
Well, that's something for you to handle. Personally I wouldn't really like a website where I put something in my cart for a certain price, and on the background the price will suddenly change. But this is something specific for you app to handle and not this package. :)

**Comment by fearrr** [comment]
In the country where I live the price is not the most stable amount, and it changes almost every day.

**Comment by Crinsane** [comment]
I understand. But I think this is just to app specific and should be implemented at the app level. 🙂
