### ISSUE TITLE
Cannot retrieve cart

### ISSUE THREAD

**Issue by gladis26** [Crinsane/LaravelShoppingcart#363]
Hi!
I have a problem in accessing the cart content with another function in my controller. The cart content was empty.
My code goes like this:

```php
function addToCart(){
      $data = $_GET;
      $cart = Cart::destroy();
     $objId = $data['data']['objDetails']['objectId'];
        foreach ($data['data'] as $key => $value) {
            switch ($key) {
                case 'photography':
                    $ids = explode(',', $value['id']);
                    foreach ($ids as $idKey => $idVal) {
                        $value['object_id'] = $objId;
                        $productDetails = $this->productRepo->getProductById($idVal);

                        $product = array(
                                'id' => $idVal,
                                'qty' => 1,
                                'price' => $productDetails['price'],
                                'name' => $productDetails['name'],
                                'details' => $value
                            );
                        Cart::add($idVal, $productDetails['name'], 1, $productDetails['price'], array('photoComment'=>$value['photoComment'],'objectId'=> $objId, 'preferenceDate'=> $value['preference_date']));    
                    break;
                    default:
                         # code...
                    break;
            }
        }
     echo $this->getHtml();
  };
```

```php
function getHtml(){
         $html = "";
        $cartItems = Cart::content();
        $html .= "<strong>No. of Products on Cart : ".Cart::count()."</strong> <hr><div class='table-responsive'>";
            $html .= "<table class='table table-striped table-hover'>";
                $html .= "<thead style='background-color:#edbfbf;'>";
                    $html .= "<tr>";
                        $html .= "<th>#</th>";
                        $html .= "<th>Product</th>";
                        $html .= "<th>Quantity</th>";
                        $html .= "<th>Price</th>";
                        $html .= "<th>Action</th>";
                    $html .= "</tr>";
                $html .= "</tr>";
                $html .= "</thead>";
                $html .= "<tbody>";
                foreach ($cartItems as $key => $value) {
                    $html .= "<tr id='".$key."'>";
                        $html .= "<td>".$count++."</td>";
                        $html .= "<td>".$value->name."</td>";
                        $html .= "<td>".$value->qty."</td>";
                        $html .= "<td>&#8369 ".$value->price()."</td>";
                        $html .= "<td><button class='btn btn-primary' onclick='removeItem(\"".$key."\")'><i class='fa fa-trash fa-lg'></button></td>";
                    $html .= "</tr>";
                }
                $html .= "</tbody>";
            $html .= "</table>";
        $html .= "</div>";
        
      return $html;
}
```

The cart contents can be displayed in my page but when I tried to delete the item using the row id, the cart was empty.

Script to remove:

```javascript
function removeItem(id) 
{
    $.ajax({
        url: '/remove-item', 
        type: 'POST', 
        data: { id: id },
        headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                },
        success: function(res) {
            if (res == 1) {
                alert('succes');
            }
            else {
                alert("Oops, there's an error in removing the item. Kindly contact the website admin.");
            }
        }
    });
}
```

```php
function removeItem(Request $request){

 //I printed here the Cart contents but it was empty. 
Cart::remove($request->all()[id]);
  echo 1; 
  exit;
}
```

**Comment by Crinsane** [comment]
Your code samples are missing the information I need to help you debug this.

**Comment by gladis26** [comment]
@Crinsane I updated my code.

**Comment by Crinsane** [comment]
I updated your comment a bit so I get some syntax highlighting if you don't mind :)

**Comment by gladis26** [comment]
@Crinsane , no problem, that's greatly appreciated

**Comment by Crinsane** [comment]
I can't really see what would cause this problem, and can't really replicate the problem.
Could you try with a fresh installation of Laravel, and just do a quick and dirty tryout of this situation and see if the problem persists. 

Because if I can't reproduce this, there's not really much I can do sadly.

**Comment by gladis26** [comment]
@Crinsane , does it have something to do with the session? When I print the contents, I'm wondering why it's empty if it was stored on the session.

**Comment by Crinsane** [comment]
@gladis26 It could, make sure you don't have any `die` or `dd()` calls in your code, because these will destroy your session.

**Comment by gladis26** [comment]
@Crinsane , I don't use those. I tried updating composer but nothing has to be updated.

**Comment by Crinsane** [comment]
@gladis26 Not really much I can do right now. Like I said before, you could try to get a fresh Laravel installation, pull in the cart package and build a quick sample app to see if the problem also persists on that app. I can't reproduce the problem at this point.

**Comment by gladis26** [comment]
I will try @Crinsane , thanks!

**Comment by gladis26** [comment]
@Crinsane , I tried to add temporary variable and store it to session.

    function addToCart(){
      $data = $_GET;
      $cart = Cart::destroy();
     $objId = $data['data']['objDetails']['objectId'];
        foreach ($data['data'] as $key => $value) {
            switch ($key) {
                case 'photography':
                    $ids = explode(',', $value['id']);
                    foreach ($ids as $idKey => $idVal) {
                        $value['object_id'] = $objId;
                        $productDetails = $this->productRepo->getProductById($idVal);

                        $product = array(
                                'id' => $idVal,
                                'qty' => 1,
                                'price' => $productDetails['price'],
                                'name' => $productDetails['name'],
                                'details' => $value
                            );
                        Cart::add($idVal, $productDetails['name'], 1, $productDetails['price'], array('photoComment'=>$value['photoComment'],'objectId'=> $objId, 'preferenceDate'=> $value['preference_date']));    
                    break;
                    default:
                         # code...
                    break;
            }
        }

     session(['sampleIndex', 1]);
     echo $this->getHtml();
  };

When I tried to print the session in the removeItem function, that temporary variable is also not included. Might be a session issue why the cart contents is empty? Is there some things I missed. The laravel I used is the current version.

**Comment by Crinsane** [comment]
It looks like something with the session on your end. I'm pretty sure it's not a problem in this package.

**Comment by gladis26** [comment]
I really don't know @Crinsane :(  I can't make the remove item work.

**Comment by Crinsane** [comment]
Have you tried making a sample app with a fresh Laravel installation?

**Comment by gladis26** [comment]
@Crinsane , I installed with fresh laravel installation and it works! I don't know why this happening in my application.

This is my composer:

    "require": {
        "php": ">=5.6.4",
        "gedmo/doctrine-extensions": "^2.4",
        "guzzlehttp/guzzle": "~5.3|~6.0",
        "intervention/image": "^2.3",
        "laravel-doctrine/extensions": "1.0.*",
        "laravel-doctrine/orm": "1.3.*",
        "laravel/framework": "5.4.*",
        "laravel/tinker": "~1.0"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~5.7"
    },

**Comment by gladis26** [comment]
Hi @Crinsane , it's already ok now! I just figured out I was using exit after rendering the html after adding the products to cart. I missed that when I add my code for this issue description.

    function addToCart(){
      $data = $_GET;
      $cart = Cart::destroy();
     $objId = $data['data']['objDetails']['objectId'];
        foreach ($data['data'] as $key => $value) {
            switch ($key) {
                case 'photography':
                    $ids = explode(',', $value['id']);
                    foreach ($ids as $idKey => $idVal) {
                        $value['object_id'] = $objId;
                        $productDetails = $this->productRepo->getProductById($idVal);

                        $product = array(
                                'id' => $idVal,
                                'qty' => 1,
                                'price' => $productDetails['price'],
                                'name' => $productDetails['name'],
                                'details' => $value
                            );
                        Cart::add($idVal, $productDetails['name'], 1, $productDetails['price'], array('photoComment'=>$value['photoComment'],'objectId'=> $objId, 'preferenceDate'=> $value['preference_date']));    
                    break;
                    default:
                         # code...
                    break;
            }
        }
     echo $this->getHtml();
   // I deleted this exit function and the cart contents are ok!
    exit;
  };


Thanks again!
