### ISSUE TITLE
groupBy options

### ISSUE THREAD

**Issue by coutinhoedu** [Crinsane/LaravelShoppingcart#371]
Hi there, I was wondering: is there any way to use the groupBy method using a 'options' attribute?

E.g.:

`Cart::add('293ad', 'Product 1', 1, 9.99, ['size' => 'large']);`

and then

`Cart::content()->groupBy('size')`

thanks in advance!

**Comment by sobhanattar** [comment]
Hi @coutinhoedu 

I'm not sure it's possible that way but you can iterate over `cart contents` and make something like this:

```
    private function getCartContentByGroup(Collection $cartContents, string $groupByName = 'size')
    {
        try {
            $groupedCartItems = [];
            foreach ($cartContents as $item) {
                $groupedCartItems["{$item->options->$groupByName}"][] = $item->toArray();
            }

            return $groupedCartItems;
            
        } catch (Exception $e) {
            throw new Exception($e->getMessage());
        }
    }
```

**Comment by coutinhoedu** [comment]
I guess it will be the way, then.

Thank you!

**Comment by johnef** [comment]
@coutinhoedu did you solve this issue? please describe how you done it.
Thanks

**Comment by bumbummen99** [comment]
Some more discussion on the case:
https://github.com/bumbummen99/LaravelShoppingcart/issues/42
