### ISSUE TITLE
is this package for Laravel 4.2?

### ISSUE THREAD

**Issue by mohammadlom** [Crinsane/LaravelShoppingcart#380]
Hi,
I'm using Laravel 4.2 for project and when I want to install this package I got the below error:
`Problem 1
    - Installation request for gloudemans/shoppingcart ^2.3 -> satisfiable by gloudemans/shoppingcart[2.3.0].
    - Conclusion: remove laravel/framework v4.2.22`
Is this package for Laravel 4.2?

**Comment by dcyar** [comment]
Currently I think it is available only for laravel 5. *

**Comment by Crinsane** [comment]
@mohammadlom Version 1.2.1 was the last version that supported Laravel 4.2
