### ISSUE TITLE
is this package for Laravel 5.5 ??

### ISSUE THREAD

**Issue by IQ-Coder** [Crinsane/LaravelShoppingcart#382]
Hi, I'm going to upgrade my existed project from Laravel 5.4 to Laravel 5.5, but I got this error because of LaravelShoppingcart:
__________________________________________
Problem 1
    - Conclusion: remove gloudemans/shoppingcart 2.3.0
    - Installation request for gloudemans/shoppingcart ^2.3 -> satisfiable by gloudemans/shoppingcart[2.3.0].
    - Conclusion: don't install laravel/framework v5.5.1
    - gloudemans/shoppingcart 2.3.0 requires illuminate/session 5.1.*|5.2.*|5.3.*|5.4.* -> satisfiable by laravel/framework[v5.4.30], illuminate/session
[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.
2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17
, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
___________________________________________
can you solve it please ???

**Comment by lanstar2** [comment]
Crinsane said in the development ...  and so on

**Comment by Crinsane** [comment]
Version 2.4.0 supports Laravel 5.5
