### ISSUE TITLE
vendor:publish not work

### ISSUE THREAD

**Issue by hatamiarash7** [Crinsane/LaravelShoppingcart#386]
hi, thank you for this useful lib

i have problem with vendor:publish command. there is a `Publishing complete.` message and nothing changed
i try these : 

`php artisan vendor:publish --provider="Gloudemans\Shoppingcart\ShoppingcartServiceProvider" --tag="config"
`
`php artisan vendor:publish --provider="Gloudemans\Shoppingcart\ShoppingcartServiceProvider" --tag="migrations"`
`php artisan vendor:publish`

laravel 5.4

is there any problem in lib ? or i have mistake somewhere ?
thank you

**Comment by Crinsane** [comment]
Did you add the service provider to the providers array in the configuration?

**Comment by hatamiarash7** [comment]
yes ... service provider class added in array

**Comment by jelmersmid** [comment]
`php artisan cache:clear` but especially `php artisan config:clear`.

**Comment by hatamiarash7** [comment]
thank you ... everything is good now
but what is wrong here ? why we `php artisan config:clear` fix everything ?

**Comment by jelmersmid** [comment]
There a whole bunch of possible reasons.
Just only `config:cache` in production. Test it, but clear after.

**Comment by Crinsane** [comment]
@hatamiarash7 well apparently you had you config cached. So at that point Laravel won't read your configuration files anymore and the newly added service provider will not be seen. Untip you clear the cache of course. 🙂
