### ISSUE TITLE
add product from another function of controller

### ISSUE THREAD

**Issue by hatamiarash7** [Crinsane/LaravelShoppingcart#390]
hello 

i have an issue
i add product in `index()` function of my controller and then return a view ( everything is OK ). but when i send an ajax POST request to add a product to cart ( from another function of controller without any return ) my code not work and there is old products

`Cart::add('293ad', 'Product 1', 1, 9.99);`

it's work very well in main function that return a view but in another functions it's not work
why ?

**Comment by Crinsane** [comment]
Is the route for the ajax request in the web middleware or the api middleware? The last one is stateless, so has no session.

**Comment by hatamiarash7** [comment]
thank you  ..... i didn't know that
