### ISSUE TITLE
Adding an extra parameter(s) to the Cart::Add

### ISSUE THREAD

**Issue by OoKamioO** [Crinsane/LaravelShoppingcart#392]
Hello everyone,

I'm looking for a way to add in extra string parameters to the shopping cart. I believe I need to modify the cart.php in the /src folder but cannot seem to find it in Laravel so I was wondering if anyone could assist?

- Thanks in advance.

**Comment by wluismartinez** [comment]
Vendor/Goudemans/shoppingcart/src
