### ISSUE TITLE
How do i fetch the content of my cart from the database to a readable format

### ISSUE THREAD

**Issue by mykoman** [Crinsane/LaravelShoppingcart#393]
Hello,
After saving a request cart session to the database, I will like to display order requests to site adminstrator. Fetching the content is the issue i am having. Kindly help me out with this.
Thanks

**Comment by Crinsane** [comment]
First I must say the main use case of the store method is not to save the cart “as an order” but to save the cart for the next time a user visits your shop. 

But that said, the cart content is serialized before storing it in the database, so you can just `unserialize()` the content after you’ve fetched it from the database
