### ISSUE TITLE
[QUESTION] is there any way to add a product that has two prices?

### ISSUE THREAD

**Issue by abr4xas** [Crinsane/LaravelShoppingcart#395]
For example:

CD Player
price one: 20
price two: 15

The intention is to be able to buy the two products, at this time only the price of the product is updated and indicates that I own 2 products with the same price.

Thanks :smile:

**Comment by Crinsane** [comment]
This is not possible in the way the package currently works. Possibily just store the actual price as an option for now? 

What’s the use case?

**Comment by abr4xas** [comment]
Okay, I'll give you an example: a baseball game.

You have tickets for:

* home
* center field
* left field
* right field

These tickets are associated with the same product (match) I want to have the ability to buy multiple tickets.

**Comment by Crinsane** [comment]
Hmm okay. In a way it does sound a lot like “options” to me. Not that different from buying the same shirt in different colors or sizes.

**Comment by abr4xas** [comment]
Yes, I certainly think that is the alternative but I still do not know how to update the total price of the shopping cart

**Comment by Crinsane** [comment]
Why would you want to update the price? Just add the item with the price for each option?

**Comment by abr4xas** [comment]
Each ticket has a price

center field = 20
left field = 15

Total cart = 35

This is what I am talking about

**Comment by Crinsane** [comment]
`Cart::add(‘id1’, ‘Ticket Center Field’, 1, 25.99, [‘location’ => ‘center-field’])`

And

`Cart::add(‘id1’, ‘Ticket Left Field’, 1, 36.99, [‘location’ => ‘left-field’])`

Something like that?

**Comment by abr4xas** [comment]
I'm talking about something like this:

![image](https://user-images.githubusercontent.com/405484/30939519-ab1e6e58-a3ab-11e7-9325-6fcc239f617f.png)
If I intend to buy a ticket I can do it
using the same section that I put as an example in the image.

**Comment by Crinsane** [comment]
And why would my example not work for you?

**Comment by abr4xas** [comment]
Let me test :smiley:

**Comment by mahdi7abash** [comment]
@abr4xas @Crinsane  i'm working now on this nice project and i need put for some items two price any help ?? i would appreciated

**Comment by abr4xas** [comment]
@mahdi7abash Retrieve the current cart instance, search and update the product price

**Comment by mahdi7abash** [comment]
@abr4xas  thanks for your reply but i didn't get what you mean .
