### ISSUE TITLE
Need DB SQL file

### ISSUE THREAD

**Issue by Harrrrry** [Crinsane/LaravelShoppingcart#398]
Hello,

please provide me the SQL file so I set up your code.

Thanks

**Comment by Harrrrry** [comment]
Hello,

What is **add options to buyable methods** 
Should I buy this option because I didn't find a **Contracts** folder.
?
Please help

**Comment by Crinsane** [comment]
I'm sorry but I'm not sure what you mean. You don't need any SQL file to setup this package.
