### ISSUE TITLE
Get last insert item raw id

### ISSUE THREAD

**Issue by Harrrrry** [Crinsane/LaravelShoppingcart#399]
Hello,

Is there any to get last insert cart item raw id or complete data ? 

Thanks,

**Comment by Crinsane** [comment]
`Cart::add()` returns the inserted cart item, which has the rowid, if that's what you mean.

**Comment by Harrrrry** [comment]
@Crinsane thanks for reply,
I using ajax to add cart and below is my code to add cart

$cartdata = Cart::add(['id' => $card_id, 'name' => $name, 'qty' => $quantity, 'price' => $netprice, 'options' => ['cardinfo'=>$retailersearchdata,'retailerinfo'=>$retailerinfo]]);
echo '<pre>'; print_r($cartdata); exit;

but getting nothing in ajax response
Please help

**Comment by Crinsane** [comment]
I’m sorry, version 1.3 is not supported anymore

**Comment by Harrrrry** [comment]
laravel 5.0 compatible version?
In which I get this functionality.
