### ISSUE TITLE
Cart contents disappearing

### ISSUE THREAD

**Issue by longestdrive** [Crinsane/LaravelShoppingcart#40]
Hi
I've been using this package for a while now but have a problem.

I add items to my cart, I can see the items there if I dump the cart and do a couple of tests. However If I then try to retrieve the cart contents from another function the cart is empty.

Products are added to the cart from an ajax call. 

```
try {

        Cart::instance('main')->add( 
        $product->id, 
        $product->name, 
        $people, 
        $salePerHead, 
        array( 
            'cost'=>$costValue, 
            'type'=>$product->type, 
            'mealQty'=>$mealQuantity
            ) 
        );

    } catch (Exception $e) {

        return "Error P002: Failed to Add Item";

    }
```

This works 

Once added another jquery ajax call from the page gets the cart content to display on the page:

`$cart = Cart::content();
$cartCount = Cart::count();
$cartTotal = Cart::total();`

These calls don't work - all returning an empty cart. I dont empty the cart between calls.

I'm confused - I've had this working. 

I've recently upgraded my project to 4.1 but convinced it was working. I've just done a composer update to make sure I have the latest build

**Comment by neochief** [comment]
Same problem here. Posted new issue: https://github.com/Crinsane/LaravelShoppingcart/issues/93
