### ISSUE TITLE
Displaying cartItems with @foreach in view from DB

### ISSUE THREAD

**Issue by ellgibug** [Crinsane/LaravelShoppingcart#400]
If I use "add" method and I write `dd(Cart::instance('shopping')->content());` in the conroller I get for example this:

```
Collection {#214 ▼
  #items: array:1 [▼
    "172d72e8190a3e89d40f74ebd2ba985e" => CartItem {#205 ▼
      +rowId: "172d72e8190a3e89d40f74ebd2ba985e"
      +id: "451"
      +qty: 1
      +name: "sORJHfdw6s"
      +price: 191.0
      +options: CartItemOptions {#217 ▶}
      -associatedModel: null
      -taxRate: 21
    }
  ]
}
```
and I can display it with @foreach as in the example in the documentation.
But if I want to dispaly cart items from DB I have an error _Invalid argument supplied for foreach()_ . And if I write for example `dd(DB::table('shoppingcart')->first()->content);` I get this:

`"O:29:"Illuminate\Support\Collection":1:{s:8:"\x00*\x00items";a:3:{s:32:"172d72e8190a3e89d40f74ebd2ba985e";O:32:"Gloudemans\Shoppingcart\CartItem":8:{s:5:"rowId";s:32:"172d72e8190a3e89d40f74ebd2ba985e";s:2:"id";s:3:"451";s:3:"qty";i:1;s:4:"name";s:10:"sORJHfdw6s";s:5:"price";d:191;s:7:"options";O:39:"Gloudemans\Shoppingcart\CartItemOptions":1:{s:8:"\x00*\x00items";a:0:{}}s:49:"\x00Gloudemans\Shoppingcart\CartItem\x00associatedModel";N;s:41:"\x00Gloudemans\Shoppingcart\CartItem\x00taxRate";i:21;}s:32:"f037ee8486bcef6c4c7dfbb5e018c85f";O:32:"Gloudemans\Shoppingcart\CartItem":8:{s:5:"rowId";s:32:"f037ee8486bcef6c4c7dfbb5e018c85f";s:2:"id";s:3:"178";s:3:"qty";i:1;s:4:"name";s:10:"6jVzNeFLc8";s:5:"price";d:166;s:7:"options";O:39:"Gloudemans\Shoppingcart\CartItemOptions":1:{s:8:"\x00*\x00items";a:0:{}}s:49:"\x00Gloudemans\Shoppingcart\CartItem\x00associatedModel";N;s:41:"\x00Gloudemans\Shoppingcart\CartItem\x00taxRate";i:21;}s:32:"2457ff33e78780b5a9fedc32023f0df1";O:32:"Gloudemans\Shoppingcart\CartItem":8:{s:5:"rowId";s:32:"2457ff33e78780b5a9fedc32023f0df1";s:2:"id";s:3:"139";s:3:"qty";i:1;s:4:"name";s:10:"8MXYBMTeJt";s:5:"price";d:51;s:7:"options";O:39:"Gloudemans\Shoppingcart\CartItemOptions":1:{s:8:"\x00*\x00items";a:0:{}}s:49:"\x00Gloudemans\Shoppingcart\CartItem\x00associatedModel";N;s:41:"\x00Gloudemans\Shoppingcart\CartItem\x00taxRate";i:21;}}} ◀"`

Are there any methods that allows to make content from DB available in @foreach?

**Comment by Crinsane** [comment]
The content is serialized before string, so you’ll have to `unserialize` it first

**Comment by Crinsane** [comment]
string = storing

**Comment by agusesetiyono** [comment]
how to unserialize?

**Comment by ellgibug** [comment]
@agusesetiyono 

 $storedCartItems = \unserialize($storedCartItems);
