### ISSUE TITLE
Call to a member function on null

### ISSUE THREAD

**Issue by zhsolutions** [Crinsane/LaravelShoppingcart#401]
This is an interesting issue I am facing....

So I have multiple products available to be bought and used through your shopping cart... Everything works great except

When I create a record using say ban_type = 1, the cart works.

When I create a record using say ban_type = 2, the cart returns a call to a member function on null..

I check, Everything included in the working records, EXISTS in the second record, the same, except a category ID, which is 2 not 2.

Any idea how to fix this

**Comment by Crinsane** [comment]
I really need more information to help you. What does you code look like, which version are you using, what are the records you're talking about, what is 'ban_type', etc.

**Comment by zhsolutions** [comment]
Hey

I think I figured it out, after some sleep I was able to clear me head and adjust the code. The issue was unrelated to this plugin so I am going to close it. thanks
