### ISSUE TITLE
Get total quantity of cart

### ISSUE THREAD

**Issue by Harrrrry** [Crinsane/LaravelShoppingcart#404]
Hello,

Can I get the total quantity of cart like we get total amount with below code?

`Cart::total()`

Thanks

**Comment by Crinsane** [comment]
`Cart::count()`

**Comment by Harrrrry** [comment]
@Crinsane Thanks for the reply but `Cart:: count()` this gives the count of the cart I need to get total quantity in the cart. 
Below example
item1 have 2 quantity, item2 have 1 quantity in a cart.
so total is 3.
How can I get this 3?
Please tell.

Thanks,

**Comment by Crinsane** [comment]
I think you’re mistaking. It should return the sum of the quantities in the cart. Did you try it?

**Comment by Harrrrry** [comment]
Ohh sorry, 
This for total number of item `Cart::content()->count()` and `Cart::count()` this for quantity toatal
Thanks
