### ISSUE TITLE
How to search/get a cart values/item with its id not rowId

### ISSUE THREAD

**Issue by wasid** [Crinsane/LaravelShoppingcart#408]
public function addCart($id)
    {
        $products = MarketProduct::find($id);
        
        $cartproduct = Cart::search(array('id' => $id, 'options' => array('available_quantity' => ?)));
      
         return  $cart_available_quantity = $cartproduct->options->available_quantity; 

        $available_quantity = $products->product->available_quantity;

        then compare $cart_available_quantity and $available_quantity before adding more qty

        $result = Cart::add([
            'id' => $id,
            'name' => $products->title,
            'qty' => 1,
            'price' => $products->mrp(),
            'options' => [
                'image' => $products->thumbnail(),
                'available_quantity' => $available_quantity
                ]
            ]);
            
        return redirect()->back();
        

    }

**Comment by Crinsane** [comment]
Use the search method

**Comment by wasid** [comment]
Sir your answer is not clear to me. I already used the search method. Have close look on the code
$cartproduct = Cart::search(array('id' => $id, 'options' => array('available_quantity' => ?)));

**Comment by wasid** [comment]
Cart::content()->where('id', $id); this code did the tricks for me...

**Comment by A7medHub** [comment]
@wasid you saved my day man very thanks

**Comment by frikishaan** [comment]
I also can't understand how the `search` function works here.
But the @wasid 's solution also works for me. Thanks man.👏

**Comment by rahim3070** [comment]
> Cart::content()->where('id', $id); this code did the tricks for me...

Output :

Illuminate\Support\Collection Object
(
    [items:protected] => Array
        (
            [52301c99fa63b03bd5c487d5643a4b70] => Gloudemans\Shoppingcart\CartItem Object
                (
                    [rowId] => 52301c99fa63b03bd5c487d5643a4b70
                    [id] => 15
                    [qty] => 14
                    [name] => a
                    [price] => 17
                    [options] => Gloudemans\Shoppingcart\CartItemOptions Object
                        (
                            [items:protected] => Array
                                (
                                    [image] => images/product_image/150.jpg
                                )
                        )
                    [associatedModel:Gloudemans\Shoppingcart\CartItem:private] => 
                    [taxRate:Gloudemans\Shoppingcart\CartItem:private] => 0
                )
        )
)

@wasid But how to get the qty ?

**Comment by bumbummen99** [comment]
Sorry if i misunderstand the topic but using the search method is just [Collection::filter](https://laravel.com/docs/7.x/collections#method-filter), you should be able to iterate the returning collection or use first() and then be able to access the quantity as it is a public property of the CartItem class like this: `$item->qty`
https://github.com/Crinsane/LaravelShoppingcart/blob/f460ab7312cce32cb428cf39a500a2d16600b1d6/src/CartItem.php#L30

So out of my head something like that should work:
```
$cart->search(function($value, $key){
  return $value->id === $id;
})->first()->qty;
```

**Comment by rahim3070** [comment]
@bumbummen99, Its very simple ..................

$asd = Cart::content()->where('id', $request->product_id);
$cart_indqty = 0;

foreach ($asd as $row) {
    $cart_indqty = $row->qty;
}
