### ISSUE TITLE
Object into search method

### ISSUE THREAD

**Issue by joooseb** [Crinsane/LaravelShoppingcart#409]
I can't put a object as Id in foreach method.
i.e: 
@foreach ($candidates as $candidate)
 $item = $cart->search(function ($cartItem, $rowId) {
            return $cartItem->id === $candidate->id;
        });
@endforeach
can you help me?
thx.

**Comment by Crinsane** [comment]
```
@foreach ($candidates as $candidate)
    $item = $cart->search(function ($cartItem, $rowId) use ($candidate) {
        return $cartItem->id === $candidate->id;
    });
@endforeach
```
