### ISSUE TITLE
Redefine Variables

### ISSUE THREAD

**Issue by spoccobeech** [Crinsane/LaravelShoppingcart#413]
Good Day!

I just want to ask about changing variable names in the shopping cart. I noticed that only id, price, and name are present and i wanted to replace them and add another variables in it. How am I suppose to access it?

Thanks!

**Comment by topsub** [comment]
Add these items within the options. you can add unlimited amount of data to that last variable

**Comment by spoccobeech** [comment]
Thanks!
I just figured out that they're on the last 'options' variable to be assigned as many as you need to assign.
