### ISSUE TITLE
data.length and data[i] not working and how do i work with ajax to show cart item

### ISSUE THREAD

**Issue by shofin-islam** [Crinsane/LaravelShoppingcart#418]
how do i get the index. here is my code below. can anyone help to out this ... 

$.ajax({
            type: 'GET',
            url: '/cart/cartData',
            dataType:'json',
            data: {},
            success: function (data) {
                var len = data.length;
                console.log(len);
 for (var i = 0; i < len; i++) {
           data[i].rowId;
       data[i].name;
       }
}
});

in controller---->
public function cartDat() {
        $cartProducts = Cart::content();
      return response()->json($cartProducts);
 }

**Comment by Crinsane** [comment]
Is the route inside the web or api route group? The last doesn’t have a session by default, so the cart is always empty

**Comment by shofin-islam** [comment]
web route. why its need session again. cart already using this. and i getting result when hit the url "/cart/cartData" in json formate but the index is showing as the rowId.

**Comment by Crinsane** [comment]
Api routes are stateless, so there is no session (so no cart) available. 
But if it’s in the web.php route file that should not be the problem. 

I’m not sure if I really understand the problem you have I think.

**Comment by shofin-islam** [comment]
May be i did not understand you, 
i solved my problem as below --
$cartContent=[];
        foreach (Cart::content() as $c){
            $cartContent[]= array(
            'rowId' => $c->rowId,
            'productId' => $c->id,
             ); 
        }
$data = array(
            'cartContents' => $cartContent,
            'cartTotal' => Cart::subtotal()
        );
        return response()->json($data);

Thank you.
