### ISSUE TITLE
How can I retrieve cart content from shoppingcart table?

### ISSUE THREAD

**Issue by freesultan** [Crinsane/LaravelShoppingcart#423]
Hi, 
I stored user carts with this identifier = email.time ,

          $key = auth()->user()->email . now();
         Cart::store($key);
Then I pulled the carts which had this email in them. Now I have an array of Carts. I wanna show the user his Cart's history (his buying history). The problem is I don't know how to restore Content field of the Cart as a Collection and use all items. this is my code:
 

        $theEmail = auth()->user()->email;

        $carts = DB::table('shoppingcart')
            ->where('identifier','LIKE', $theEmail . '%')
            ->get();

        return view('Home.panel.book.history', compact('carts'))
 
and in view:
 
    @foreach($carts as $cart)

      @foreach($cart as $item)
        {{ $item->name }}  // but the $item here is nonobject or null 
       @endforeach
    @endforeach

Should I store user buying history in another table or I can use Shoppingcart table??

**Comment by Crinsane** [comment]
The store and restore functionality are just for saving the cart content for a later date. I don't recommend using it to store buy history or something. You should really store that in a separate table using your own logic. :)
