### ISSUE TITLE
Laravel 5.6 released - please add support

### ISSUE THREAD

**Issue by divdax** [Crinsane/LaravelShoppingcart#424]
see subject

**Comment by AGhasemzadeh** [comment]
Yes,
I need it.

**Comment by mufasa747** [comment]
That will be great if you can provide support for 5.6.3, thanks

**Comment by AGhasemzadeh** [comment]
hello @mufasa747
please try composer require shirazsoft/shoppingcart

**Comment by Crinsane** [comment]
Version 2.5 now supports Laravel 5.6 https://github.com/Crinsane/LaravelShoppingcart/releases/tag/2.5.0

**Comment by mufasa747** [comment]
Thanks very much Crinsane.
