### ISSUE TITLE
Abstract Method error.

### ISSUE THREAD

**Issue by d35k** [Crinsane/LaravelShoppingcart#427]
Hi all,
when i try to implement the Buyable interface to my Model, i got this errors: 

```
Class Modules\Product\Entities\Product contains 3 abstract methods and must therefore be declared abstract or implement the remaining methods
(Gloudemans\Shoppingcart\Contracts\Buyable::getBuyableIdentifier,
Gloudemans\Shoppingcart\Contracts\Buyable::getBuyableDescription,
Gloudemans\Shoppingcart\Contracts\Buyable::getBuyablePrice)
```

My Model:
```
<?php

namespace Modules\Product\Entities;
use Gloudemans\Shoppingcart\Contracts\Buyable;
use Illuminate\Database\Eloquent\Model;

class Product extends Model implements Buyable{
...
}
```

I have a little fix, when i add this methods to my model, im not getting any error.
```
public function getBuyableIdentifier($options = null){ return $this->id; }
public function getBuyableDescription($options = null){ return $this->id; }
public function getBuyablePrice($options = null){ return $this->id; }
```

but i dont think thats the right way to fix it.

Best Regards,

**Comment by Anlamas** [comment]
Its only way to fix. 
[http://php.net/manual/en/language.oop5.interfaces.php](url)
All methods in the interface **must be** implemented within a class.

**Comment by d35k** [comment]
> Its only way to "fix".
> [http://php.net/manual/en/language.oop5.interfaces.php](url)
> All methods in the interface **must be** implemented within a class.

Thx, I fixed that. Issue was not a real issue

**Comment by bumbummen99** [comment]
@d35k As said it is intended, it basically enforces that your model implements functions and they return the value you desire. If you want the package to lookup these values by itself you can use the CanBeBought Trait which uses hardcoded fields of your model.
https://github.com/Crinsane/LaravelShoppingcart/blob/master/src/CanBeBought.php

Maybe interesting for you:
http://php.net/manual/en/language.oop5.traits.php
https://laravel.com/docs/5.7/contracts
✌️

**Comment by d35k** [comment]
> @d35k As said it is intended, it basically enforces that your model implements functions and they return the value you desire. If you want the package to lookup these values by itself you can use the CanBeBought Trait which uses hardcoded fields of your model.
> https://github.com/Crinsane/LaravelShoppingcart/blob/master/src/CanBeBought.php
> 
> Maybe interesting for you:
> http://php.net/manual/en/language.oop5.traits.php
> https://laravel.com/docs/5.7/contracts
> ✌️

✌️✌️ Thank you for informing me, as like I said, it was a little mistake. 🤣 

I didn't see anything about CanBeBought trait in the documentation, maybe we should add this to documentation?

**Comment by bumbummen99** [comment]
> 
> ✌️✌️ Thank you for informing me, as like I said, it was a little mistake. 🤣
> 
> I didn't see anything about CanBeBought trait in the documentation, maybe we should add this to documentation?

Yes that would be awesome, but this repository is pretty inactive so i do not think it will be added to the readme soon. I have added it to my fork's readme, maybe i am going to create a pr if that would help further.
