### ISSUE TITLE
update same item twice but get error

### ISSUE THREAD

**Issue by liz-in** [Crinsane/LaravelShoppingcart#435]
Hi,

I use Ajax to update the cart items.
The same item update twice:
The first time is fine. Updated correctly.
But the second time throw the exception: InvalidRowIDException
The error message shows: The cart does not contain rowId: 06d6d6456f0b47114e385c7f3af44840.

I search my cart item and the rowId is exist.
I don't know how to solve the problem, would you help me.

**Comment by infinity-webdesigns** [comment]
I had the same problem today and found the solution. 
For the first update you should set a variable like so:
`$cartItem = Cart::update($rowID, $array);`

Now you can update the second time like so:
`Cart::update($cartItem->rowId, $array);`

Hope this helps

**Comment by liz-in** [comment]
It works! Thanks

**Comment by liz-in** [comment]
Hey, I found the solution!

When update the cartItem by ajax, it will return a temporary rowId. And you should use the temporary rowId to update the cartItem. 
Why I called it is a **temporary rowId**?
Because when Refresh the page, the rowId is still the original rowId, not temporary rowId.

_Example_:
At first time, your cartItem rowId is:
d88bf75698e6303b383e5349795bac52

after update the qty of the cartItem by ajax, the rowId will change to:
06d6d6456f0b47114e385c7f3af44840

then, refresh the page, rowId is:
d88bf75698e6303b383e5349795bac52

It's weird...
I always thought the rowId was the same all the time...

**Comment by Crinsane** [comment]
@liz-in Are you sure your ajax routes have the session enabled? This is one of the things that I most often see going wrong. If you're ajax routes are stateless, all sorts of things can go wrong.
