### ISSUE TITLE
The cart does not contain rowId

### ISSUE THREAD

**Issue by RomanGorkunenko** [Crinsane/LaravelShoppingcart#447]
Hello!
Help me, plz.
Here is my controller:
    public function update(Request $request){
        //dd($request->all());
        Cart::update($request->rowId, $request->qty);
        return redirect('/showcart');
}

**Comment by ssheduardo** [comment]
What is the solution your problem?

**Comment by fureszk** [comment]
@ssheduardo this the message of
InvalidRowIDException | When the rowId that got passed doesn't exists in the current cart instance

in my case, I used $row->rowid instead of $row->rowId to reference a row

**Comment by Grald** [comment]
same here i got the same problem.

**Comment by fureszk** [comment]
@Grald check if you refer **rowid** or **rowId**

**Comment by Grald** [comment]
I changed from rowid to rowId but the error is in the Cart.php

**Comment by surtaeff** [comment]
faced a similar problem,  item was not added to the cart

helped:   
in Cart controller __construct function 
add the first line:  \Artisan::call('view:clear'); 
crutch but it works:)

**Comment by yanikkumar** [comment]
you've to remove item from the cart first and then save it. `Cart::remove($id);`
