### ISSUE TITLE
Please, add support Laravel 5.7

### ISSUE THREAD

**Issue by rariteth** [Crinsane/LaravelShoppingcart#488]
https://github.com/Crinsane/LaravelShoppingcart/pull/494
https://github.com/Crinsane/LaravelShoppingcart/pull/491

**Comment by viacheslavpleshkov** [comment]
Hi, I tried to update using composer your lib, but composer won't due to compatibility to Laravel 5.7

**Comment by rebornishard** [comment]
@rariteth make a new package , @Crinsane seems busy

**Comment by rariteth** [comment]
> @rariteth make a new package , @Crinsane seems busy

https://github.com/rariteth/laravel-cart

**Comment by hardevine** [comment]
#520

**Comment by rikiless** [comment]
Seems it's already updated. 

https://github.com/Crinsane/LaravelShoppingcart/releases/tag/2.6.0

Issue duplicates #488, #498, #510, #520.
