### ISSUE TITLE
Cart::associate

### ISSUE THREAD

**Issue by amilajack** [Crinsane/LaravelShoppingcart#49]
I'm having an issue with storing the cart items to the DB. I data dumped the cart and the object is set but when I check the DB the item is not inserted. Here is a snippet of my code:

```
    $item = array(
        'id' => '293ad',
        'name' => $this->input['condition'],
        'qty' => 1,
        'price' => 24
    );
    //Add item ID to cart
    Cart::associate('cart')->add($item);

    $content = Cart::content();

    dd($content);
```

 and here is my my DB migration

```
   <?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateCartTable extends Migration {

/**
 * Run the migrations.
 *
 * @return void
 */
public function up()
{
    Schema::create('cart', function($t) {
        $t->string('id');
        $t->string('qty');
        $t->string('name');
        $t->string('price');
    });
}

/**
 * Reverse the migrations.
 *
 * @return void
 */
public function down()
{
    Schema::drop('cart');
}

}
```

![screen shot 2014-07-18 at 4 48 28 pm](https://cloud.githubusercontent.com/assets/6374832/3633101/16f9b20e-0ed6-11e4-90b0-9f864f980bee.png)

**Comment by lyagami2** [comment]
@Crinsane : Consider a case : "A user logs into his account, adds products to his cart and then he access it from another system (i.e. mobile or laptop) there will be nothing in his cart". Is there any solution for it?

**Comment by kodescience** [comment]
If your going to store the cart in a database it doesn't make sense to use this package. it defeats the purpose of sessions.

**Comment by lyagami2** [comment]
It is required to store unfinished cart when user logins but dont complete order. Do u know is there is any laravel package that allows it?

**Comment by lukepolo** [comment]
If you are using redis you can re-grab the session but you would have to store that session id somewhere.

**Comment by kodescience** [comment]
Im not aware of any package with laravel but i would imagine it would be pretty quick to program.

**Comment by lukepolo** [comment]
Im working on doing it in my cart package right now hopefully to have that feature up soon.

**Comment by kodescience** [comment]
Sweet

**Comment by lukepolo** [comment]
Feel free to use this branch : https://github.com/lukepolo/laracart/tree/user_cart_db
