### ISSUE TITLE
Class 'Product' not found

### ISSUE THREAD

**Issue by GordanaP** [Crinsane/LaravelShoppingcart#490]
I'm using Laravel 5.6.34 and am not able to associate cart item with the model App\Product.

class CartController extends Controller
{
        $cartItem = Cart::add('293ad', 'Product 1', 1, 9.99)->associate('App\Product');
}

ErrorException (E_ERROR)
Class 'Product' not found

I tried to associate 'Product', App\Product::class but neither works.

**Comment by spectre-dt** [comment]
Hey,
Have you got 
use Gloudemans\Shoppingcart\Facades\Cart; 
at the top of your web.php? I had the same issue and it fixed it for me.

Hope this helps

**Comment by GordanaP** [comment]
My fault. Everything works perfectly when using ('App\Product');
Thank you for such a great package!

**Comment by DanTurner97** [comment]
What was your issue? I've got the same problem.

**Comment by GordanaP** [comment]
The cartItem and the model were properly associated as suggested by the docs, but I had a code error in my  view page. However, this association resulted in duplicate queries when displaying the cart content. So I removed it and refactored the code.  (https://github.com/Crinsane/LaravelShoppingcart/issues/96)
