### ISSUE TITLE
laravel 5.7 support

### ISSUE THREAD

**Issue by ghost** [Crinsane/LaravelShoppingcart#498]
Does not support laravel 5.7

**Comment by MiticJovan** [comment]
And l am looking for that...
All you need to do if you want to continue with project is to get back to old 5.6 version. my code is working like this, make changes in composer.json file:
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": "^7.1.3",
        "doctrine/dbal": "^2.8",
        "fideloper/proxy": "^4.0",
        "gloudemans/shoppingcart": "^2.5",
        "illuminate/support": "5.6",
        "laravel/framework": "5.6",
        "laravel/tinker": "^1.0",
        "laravelcollective/html": "^5.4.0"
    },

The most important is to manually set illuminate/support to 5.6 and laravel framework to 5.6 and update composer via terminal composer update and done, you can continue with the project...

**Comment by MoogyG** [comment]
#metoo

**Comment by hardevine** [comment]
come on

**Comment by grimxd** [comment]
Yes please

**Comment by ghost** [comment]
Yes, definitely need 5.7 support, please!

**Comment by asartz** [comment]
+1

**Comment by greatsami** [comment]
21 days not updated yet?

**Comment by hardevine** [comment]
it seems its abandoned, fork it and update

**Comment by divdax** [comment]
@Crinsane please update

**Comment by t-k-c** [comment]
please update!!!!

**Comment by t-k-c** [comment]
Im forced to use this as an alternative https://github.com/darryldecode/laravelshoppingcart

**Comment by hardevine** [comment]
5.7 supported :)
https://github.com/hardevine/LaravelShoppingcart

**Comment by t-k-c** [comment]
Perfect!!!

**Comment by jordantsap** [comment]
Thanks man

Λήψη του Outlook για Android<https://aka.ms/ghei36>

________________________________

**Comment by aliqasemzadeh** [comment]
@Crinsane 
Hello,
Please merge 5.7 support.

**Comment by jordantsap** [comment]
https://github.com/bumbummen99/LaravelShoppingcart
this is much better than everything i see before and it has new features as well!!

**Comment by MichaelBelgium** [comment]
Nobody made a fork which adds like shipping costs and transaction costs so i had to make one myself: https://github.com/MichaelBelgium/LaravelShoppingcart - didnt had much time to improve it further yet

**Comment by rikiless** [comment]
Seems it's already updated. 

https://github.com/Crinsane/LaravelShoppingcart/releases/tag/2.6.0

Issue duplicates #488, #498, #510, #520.
