### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by chrisvidal** [Crinsane/LaravelShoppingcart#500]
Is there any real example code out there please?

I am playing with the cart and I am quite unsuccessful so far.
I am developing an API for a project that will use the cart.
So let's say we have 2 routes. One GET to get the cart content and POST to add product in the cart.
When I do this consecutively, the cart is empty:

`POST /api/cart`

which does use an example from the doc

````php
        $this->cart->add('293ad', 'Product 1', 1, 9.99);
       return Response::Json(
            $this->cart->content(),
            200,
            []
        );
````

return

```json
{
    "8cbf215baa3b757e910e5305ab981172": {
        "rowId": "8cbf215baa3b757e910e5305ab981172",
        "id": "293ad",
        "name": "Product 1",
        "qty": 1,
        "price": 9.99,
        "options": [],
        "tax": 0.6993,
        "subtotal": 9.99
    }
}
```

then I use the route GET
`GET /api/cart`

which code is

```php
   return Response::Json(
            $this->cart->content(),
            200,
            []
        );
```

it returns

```json
[]
```

**Comment by chrisvidal** [comment]
ok i figured out that one needs to use store the cart
```php
Cart::store('username');
```

unfortunately, it raises an exception. It seems that the cart does not find the db connection, which I already setup to 'mysql'

```
Unresolvable dependency resolving [Parameter #0 [ &lt;required&gt; $app ]] in class Illuminate\Database\DatabaseManager</div>
                <p>/Users/christophevidal/Sites/oc-vodka/vendor/laravel/framework/src/Illuminate/Container/Container.php 
                    <span>line</span> 933
                </p>
            </div>
            <ul class="indicators">
                <li>
                    <h3>Type</h3>
                    <p>Undefined</p>
                </li>
                <li>
                    <h3>Exception</h3>
                    <p>Illuminate\Contracts\Container\BindingResolutionException</p>
                </li>
```

**Comment by abdolrhman** [comment]
@chrisvidal  how did u solve this bro , am tring to do the same thing , i can store it , and restore ,but when i close the postman then open it again the restore method return empty array ,

also can u post the snipest of code for implementing the pakcage for api , 
thanks in advance ^^

**Comment by chrisvidal** [comment]
you need to add the middleware 'web' in your api routes, then you will be able to to retrieve the session of your cart even after closing postman

**Comment by javasprogrammer** [comment]
thanks
