### ISSUE TITLE
Please update for Laravel 5.7

### ISSUE THREAD

**Issue by darkperis** [Crinsane/LaravelShoppingcart#510]
_Originally posted by @darkperis in https://github.com/Crinsane/LaravelShoppingcart/commit/7ff157b7e1ef10d27cd2759d5151aae2cc6b1b9a#commitcomment-30625834_

**Comment by core45** [comment]
Yes, please update to 5.7

**Comment by ghost** [comment]
How long wait update to 5.7 ?

**Comment by edwinricaurte** [comment]
Any update?

**Comment by mgsmus** [comment]
I don't know when will be the update but you can fork it and use your own fork while waiting:

- Fork it.
- Create your branch, ie. laravel57
- Update the composer.json:
```
"require": {
    "illuminate/support": "5.1.* || 5.2.* || 5.3.* || 5.4.* || 5.5.*|| 5.6.* || 5.7.*",
    "illuminate/session": "5.1.* || 5.2.* || 5.3.* || 5.4.* || 5.5.*|| 5.6.* || 5.7.*",
    "illuminate/events": "5.1.* || 5.2.* || 5.3.* || 5.4.* || 5.5.*|| 5.6.* || 5.7.*"
},
"require-dev": {
    "phpunit/phpunit": "~5.0|~6.0|~7.0",
    "phpunit/phpunit": "~5.0 || ~6.0 || ~7.0",
    "mockery/mockery": "~0.9.0",
    "orchestra/testbench": "~3.1"
},
```
- Update your project's composer.json:
```
"repositories": [
    {
        "type": "vcs",
        "url": "https://github.com/your_username/LaravelShoppingcart"
    }
],
"require": {
    ...
    "gloudemans/shoppingcart": "dev-laravel57",
    ...
},
```
- Note that you have to prefix your branch name with `dev-` in your composer.json. If your branch name is dev-laravel57, it should be `dev-dev-laravel57`

- Then `composer update`

**Comment by rariteth** [comment]
i just created my own cart repository, https://github.com/rariteth/laravel-cart

**Comment by hardevine** [comment]
#520

**Comment by rikiless** [comment]
Seems it's already updated. 

https://github.com/Crinsane/LaravelShoppingcart/releases/tag/2.6.0

Issue duplicates #488, #498, #510, #520.
