### ISSUE TITLE
Hello boys

### ISSUE THREAD

**Issue by PierreAlainKouakou** [Crinsane/LaravelShoppingcart#516]
i use gloudemans shoppingcart package on one e-commerce project. My shopping cart is integrate clearly but, when i try to add one product with same id in the cart, it adding two times with differents rowId. it embarrasses me a lot now because the project is almost complete and I run towards the delivery of the project. please help me guys.

Pierre Alain KOUAKOU

**Comment by mrdigitalau** [comment]
Mate the only reason why it would do that is if something is different.. Eg maybe an option is different? I am pretty sure the script checks if the product is EXACTLY the same, if it isn't, it will add it as a new line. Are you adding anything to the product differently each time?

**Comment by PierreAlainKouakou** [comment]
Yes @mrdigitalau you're absolutely right because actually I was updating a column "more seen" with int property on my product table which made the package believe that the product was new. Thank you very much for the answer, I rectified the error and everything rolls on wheels now thank you again dude!
