### ISSUE TITLE
Installation on Laravel 5.7

### ISSUE THREAD

**Issue by gathuku** [Crinsane/LaravelShoppingcart#520]
hello coders am getting this error when i try installing the package

 Installation request for laravel/framework (locked at v5.7.9, required as 5.7.*) -> satisfiable by laravel/framework[v5.7.9].

**Comment by sadekd** [comment]
Duplicate https://github.com/Crinsane/LaravelShoppingcart/issues/498

**Comment by ThomasVeld** [comment]
Please fix this for 5.7!

**Comment by MichaelBelgium** [comment]
This is the best fork with 5.7 support https://github.com/hardevine/LaravelShoppingcart

Or mine, where i already added some functionality: https://github.com/MichaelBelgium/LaravelShoppingcart

**Comment by rikiless** [comment]
Seems it's already updated. 

https://github.com/Crinsane/LaravelShoppingcart/releases/tag/2.6.0

Issue duplicates #488, #498, #510, #520.
