### ISSUE TITLE
when removing a cart when i double click fast the delete button the row id does not found is showing

### ISSUE THREAD

**Issue by prokarm19** [Crinsane/LaravelShoppingcart#522]

**Comment by manojo123** [comment]
Your delete button triggers what? a url, ajax, post a form?

**Comment by tpw1314** [comment]
I think what he meant was 'Removing an item in the cart throws an error. [Further elaboration] A ```row id does not found``` error message is shown when I instantly double click the delete button.'

I guess ajax return too slow and that the 'ids' unable to populate to the cart table ?

**Comment by prokarm19** [comment]
its a  url

**Comment by bumbummen99** [comment]
@prokarm19 Does this issue still persist?

**Comment by tpw1314** [comment]
> 
> 
> its a url

Do you mean 'Row id does not found' is in url content ?
