### ISSUE TITLE
cant install it on laravel V5.7.9

### ISSUE THREAD

**Issue by abdullahkaamil** [Crinsane/LaravelShoppingcart#527]

**Comment by shadrackkip** [comment]
i am facing the same proble too

![image](https://user-images.githubusercontent.com/15233982/49693885-233f1800-fb90-11e8-9de5-4e028957d42b.png)

**Comment by abdullahkaamil** [comment]
the only solution is to downgrade laravel to 5.6

________________________________

**Comment by bumbummen99** [comment]
#520
