### ISSUE TITLE
can you please check why cant install it 

### ISSUE THREAD

**Issue by abdullahkaamil** [Crinsane/LaravelShoppingcart#528]
Using version ^2.5 for gloudemans/shoppingcart
./composer.json has been updated
Loading composer repositories with package information

Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for gloudemans/shoppingcart ^2.5 -> satisfiable by gl                                                    oudemans/shoppingcart[2.5.0].
    - Conclusion: remove laravel/framework v5.7.13
    - Conclusion: don't install laravel/framework v5.7.13
    - gloudemans/shoppingcart 2.5.0 requires illuminate/events 5.1.*|5.2.*|5.3.*                                                    |5.4.*|5.5.*|5.6.* -> satisfiable by laravel/framework[5.1.x-dev, 5.2.x-dev, 5.3                                                    .x-dev, 5.4.x-dev, 5.5.x-dev, 5.6.x-dev], illuminate/events[5.1.x-dev, 5.2.x-dev                                                    , 5.3.x-dev, 5.4.x-dev, 5.5.x-dev, 5.6.x-dev, v5.1.1, v5.1.13, v5.1.16, v5.1.2,                                                     v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v                                                    5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v                                                    5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.                                                    3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.1                                                    6, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.3                                                    9, v5.5.40, v5.5.41, v5.5.43, v5.5.44, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12                                                    , v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21                                                    , v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3                                                    , v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.3                                                    8, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
    - Can only install one of: laravel/framework[5.6.x-dev, v5.7.13].
    - laravel/framework 5.2.x-dev conflicts with laravel/framework[v5.7.13].
    - laravel/framework 5.3.x-dev conflicts with laravel/framework[v5.7.13].
    - laravel/framework 5.4.x-dev conflicts with laravel/framework[v5.7.13].
    - laravel/framework 5.5.x-dev conflicts with laravel/framework[v5.7.13].
    - Can only install one of: laravel/framework[5.1.x-dev, v5.7.13].
    - don't install illuminate/events 5.1.x-dev|don't install laravel/framework                                                     v5.7.13
    - don't install illuminate/events 5.2.x-dev|don't install laravel/framework                                                     v5.7.13
    - don't install illuminate/events 5.3.x-dev|don't install laravel/framework                                                     v5.7.13
    - don't install illuminate/events 5.4.x-dev|don't install laravel/framework                                                     v5.7.13
    - don't install illuminate/events 5.5.x-dev|don't install laravel/framework                                                     v5.7.13
    - don't install illuminate/events 5.6.x-dev|don't install laravel/framework                                                     v5.7.13
    - don't install illuminate/events v5.1.1|don't install laravel/framework v5.                                                    7.13
    - don't install illuminate/events v5.1.13|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.1.16|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.1.2|don't install laravel/framework v5.                                                    7.13
    - don't install illuminate/events v5.1.20|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.1.22|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.1.25|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.1.28|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.1.30|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.1.31|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.1.41|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.1.6|don't install laravel/framework v5.                                                    7.13
    - don't install illuminate/events v5.1.8|don't install laravel/framework v5.                                                    7.13
    - don't install illuminate/events v5.2.0|don't install laravel/framework v5.                                                    7.13
    - don't install illuminate/events v5.2.19|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.2.21|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.2.24|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.2.25|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.2.26|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.2.27|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.2.28|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.2.31|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.2.32|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.2.37|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.2.43|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.2.45|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.2.6|don't install laravel/framework v5.                                                    7.13
    - don't install illuminate/events v5.2.7|don't install laravel/framework v5.                                                    7.13
    - don't install illuminate/events v5.3.0|don't install laravel/framework v5.                                                    7.13
    - don't install illuminate/events v5.3.16|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.3.23|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.3.4|don't install laravel/framework v5.                                                    7.13
    - don't install illuminate/events v5.4.0|don't install laravel/framework v5.                                                    7.13
    - don't install illuminate/events v5.4.13|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.4.17|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.4.19|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.4.27|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.4.36|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.4.9|don't install laravel/framework v5.                                                    7.13
    - don't install illuminate/events v5.5.0|don't install laravel/framework v5.                                                    7.13
    - don't install illuminate/events v5.5.16|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.5.17|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.5.2|don't install laravel/framework v5.                                                    7.13
    - don't install illuminate/events v5.5.28|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.5.33|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.5.34|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.5.35|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.5.36|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.5.37|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.5.39|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.5.40|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.5.41|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.5.43|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.5.44|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.6.0|don't install laravel/framework v5.                                                    7.13
    - don't install illuminate/events v5.6.1|don't install laravel/framework v5.                                                    7.13
    - don't install illuminate/events v5.6.10|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.6.11|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.6.12|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.6.13|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.6.14|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.6.15|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.6.16|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.6.17|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.6.19|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.6.2|don't install laravel/framework v5.                                                    7.13
    - don't install illuminate/events v5.6.20|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.6.21|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.6.22|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.6.23|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.6.24|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.6.25|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.6.26|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.6.27|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.6.28|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.6.29|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.6.3|don't install laravel/framework v5.                                                    7.13
    - don't install illuminate/events v5.6.30|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.6.31|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.6.32|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.6.33|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.6.34|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.6.35|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.6.36|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.6.37|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.6.38|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.6.39|don't install laravel/framework v5                                                    .7.13
    - don't install illuminate/events v5.6.4|don't install laravel/framework v5.                                                    7.13
    - don't install illuminate/events v5.6.5|don't install laravel/framework v5.                                                    7.13
    - don't install illuminate/events v5.6.6|don't install laravel/framework v5.                                                    7.13
    - don't install illuminate/events v5.6.7|don't install laravel/framework v5.                                                    7.13
    - don't install illuminate/events v5.6.8|don't install laravel/framework v5.                                                    7.13
    - don't install illuminate/events v5.6.9|don't install laravel/framework v5.                                                    7.13
    - Installation request for laravel/framework (locked at v5.7.13, required as                                                     5.7.*) -> satisfiable by laravel/framework[v5.7.13].

Installation failed, reverting ./composer.json to its original content.

**Comment by dangermark** [comment]
This package does not yet have Laravel 5.7 support. It seems this package is dead. You can either use Laravel 5.6 or check the comments for a compatible fork.

**Comment by jordantsap** [comment]
https://github.com/rariteth/laravel-cart

**Comment by MichaelBelgium** [comment]
This is the best fork with 5.7 support: https://github.com/hardevine/LaravelShoppingcart
