### ISSUE TITLE
Laravel 5.8 compatibility?

### ISSUE THREAD

**Issue by lloricode** [Crinsane/LaravelShoppingcart#548]
@Crinsane

**Comment by Crinsane** [comment]
Feel free to send in a PR

**Comment by aliqasemzadeh** [comment]
@hardevine
Please update to 5.8

**Comment by lloricode** [comment]
https://github.com/Crinsane/LaravelShoppingcart/pull/550 waiting to merge this

**Comment by muhammetsait** [comment]
Any news on this? @Crinsane

**Comment by hardevine** [comment]
@alighasemzadeh done

**Comment by reina3596** [comment]
Up

**Comment by VPetar** [comment]
Meanwhile... https://packagist.org/packages/bumbummen99/shoppingcart
Please merge #550 so we can all get back to this awesome package. ^_^

**Comment by edsonrodsilva** [comment]
Congratulations on the fabulous package, please merge this: https://github.com/Crinsane/LaravelShoppingcart/pull/550

**Comment by jesseqli** [comment]
Any updates on this?

**Comment by VPetar** [comment]
> Any updates on this?

Don't think it's maintained anymore, you can use https://packagist.org/packages/bumbummen99/shoppingcart

**Comment by Iconbanderas** [comment]
Hi guys, I tried installing but it couldn't, I don't think there's compatibility for laravel5.8. any instructions?

**Comment by Iconbanderas** [comment]
![image](https://user-images.githubusercontent.com/32135282/62475112-4613e180-b79c-11e9-85fc-dbd1a6955666.png)

**Comment by edsonrodsilva** [comment]
Hi,
Use this even when we wait for a PR.
https://github.com/bumbummen99/LaravelShoppingcart
---------------------------------------
*Edson Rodrigues*


Em seg, 5 de ago de 2019 às 12:16, Iconbanderas <notifications@github.com>
escreveu:

**Comment by bumbummen99** [comment]
For learning purpose, if you encounter console output like that you should always check the 'requires' section in the composer.json file of the package you are trying to install. In the case of a laravel package it should state something like `"illuminate/XYZ": "5.7.*"` or even `laravel/Laravel` alongside other packages or versions. If that section does not include 5.8 the package will not be compatible with Laravel 5.8+. This will also be the same for 5.9.

[Composer Versions and constraints](https://getcomposer.org/doc/articles/versions.md)
[Crisane/LaravelShoppingcart composer.json](https://github.com/Crinsane/LaravelShoppingcart/blob/master/composer.json#L12)

**Comment by bomshteyn** [comment]
Hi, just wanted to let you know that we used to use this cart and ran into this issue as well so we have created our own open source version for Laravel v6. Please try it out https://github.com/treeStoneIT/shopping-cart

**Comment by lloricode** [comment]
its been a year

**Comment by lloricode** [comment]
this nothing works for now
