### ISSUE TITLE
How do I save cart items to db and show it in admin panel?

### ISSUE THREAD

**Issue by shivajigree** [Crinsane/LaravelShoppingcart#551]
How do I save cart items to db and show it in admin panel with only name of product and price? I cant seem to workaround with the unserialize method. please help.

**Comment by mdeprezzo** [comment]
#391 maybe this old issue, could be useful for your purpose.

**Comment by shivajigree** [comment]
This worked for me.
In controller
` $cart = Cart::content();
        $order->contents = serialize($cart);
$order->save();`

In blade
`@foreach ($orders as $item)`
   `      @foreach (unserialize($item['contents']) as $single_item)`
           `       {{ $single_item->name }} {{ $single_item->price }}`
 `         @endforeach`
`  @endforeach`
