### ISSUE TITLE
How display count of items in view?

### ISSUE THREAD

**Issue by mreduar** [Crinsane/LaravelShoppingcart#557]
As this [issue ](https://github.com/Crinsane/LaravelShoppingcart/issues/220) says, I would like to show the item count added to the cart in almost all my frontent, as it is displayed in the header a cart icon with a number and would like to show that number depending on how many items are in the cart.

This count only works in the index method of the controller I created for the cart but not in the rest of the views such as home.

http://prntscr.com/na8wk1

**Comment by bumbummen99** [comment]
Try to load the instance first by calling Cart::instance() before count()

**Comment by mreduar** [comment]
> Try to load the instance first by calling Cart::instance() before count()

It was indeed that, what a fool I was. Thanks you very much

**Comment by bumbummen99** [comment]
@Zontir Hehe no problem, i was suprised too when it did not show on my end.
