### ISSUE TITLE
Delete stored cart from the DB once the cart is destroyed

### ISSUE THREAD

**Issue by miguejarias** [Crinsane/LaravelShoppingcart#558]

**Comment by miguejarias** [comment]
This may be stupid butr after you store a cart, how do you delete it from the DB once the cart is destroyed? Does it do it automatically?

**Comment by bumbummen99** [comment]
After saving it by calling store you can use the restore method to restore the given instance from the db and delete the entry from the db.
https://github.com/Crinsane/LaravelShoppingcart/blob/f460ab7312cce32cb428cf39a500a2d16600b1d6/src/Cart.php#L399
https://github.com/Crinsane/LaravelShoppingcart/blob/f460ab7312cce32cb428cf39a500a2d16600b1d6/src/Cart.php#L400

**Comment by miguejarias** [comment]
Thanks @bumbummen99.
