### ISSUE TITLE
Model association not working as expected

### ISSUE THREAD

**Issue by Power50015** [Crinsane/LaravelShoppingcart#559]
![2019-05-01 (1)](https://user-images.githubusercontent.com/42242552/57022543-bc4df880-6c2f-11e9-8b36-a8100ccb21e1.png)
![2019-05-01 (2)](https://user-images.githubusercontent.com/42242552/57022544-bc4df880-6c2f-11e9-9dde-ba4cef9053a0.png)
![2019-05-01 (3)](https://user-images.githubusercontent.com/42242552/57022545-bc4df880-6c2f-11e9-9564-86cb630fcef4.png)
![2019-05-01 (4)](https://user-images.githubusercontent.com/42242552/57022547-bce68f00-6c2f-11e9-874b-9545a901acd7.png)
![2019-05-01 (5)](https://user-images.githubusercontent.com/42242552/57022548-bce68f00-6c2f-11e9-8cc5-141ca501e8ee.png)
![2019-05-01](https://user-images.githubusercontent.com/42242552/57022549-bce68f00-6c2f-11e9-9bec-b715e0856b9e.png)
Using laravel 5.8
Please help

**Comment by taha7** [comment]
May be you are using find method or getting a relation from a model like $item->model .... they are automatically search by (id) column but your primary key is product_id .... In my mind you can
1- Change your primary key in your product model protected $primaryKey = 'product_id';
2- Change your primary key in products migration table

**Comment by Power50015** [comment]
@taha7 
Thank's man 
I try That but it gives  me a new error
![2019-05-01 (7)](https://user-images.githubusercontent.com/42242552/57038274-da305300-6c59-11e9-9ba3-0b0edaff0b60.png)
![2019-05-01 (8)](https://user-images.githubusercontent.com/42242552/57038275-dac8e980-6c59-11e9-931a-9851e4f4f122.png)

**Comment by bumbummen99** [comment]
Please keep this in mind (as already mentioned) :
https://laravel.com/docs/5.8/eloquent#eloquent-model-conventions

**Comment by Power50015** [comment]
@bumbummen99 I hope if I can understand you or understand what to do?

**Comment by bumbummen99** [comment]
@Power50015 I just left the link to the eloquent model conventions. By looking at your migration i can see that you are not holding to the default naming by eloquent, therefore you have to overwrite them manually, as @taha7 mentioned. Hope it helps in the future 👍 

As for your second issue, are you sure that product_name is not null for this instance?

**Comment by Power50015** [comment]
@bumbummen99 yes my friend it isn't null.

**Comment by bumbummen99** [comment]
@Power50015 Ahh, i think i have found the answer ^^
https://github.com/Crinsane/LaravelShoppingcart#models
It says that the Model has to implement the Buyable interface for the association to work.

```
if ($id instanceof Buyable) {
    $cartItem = CartItem::fromBuyable($id, $qty ?: []);
    $cartItem->setQuantity($name ?: 1);
    $cartItem->associate($id);
} elseif (is_array($id)) {
```
https://github.com/Crinsane/LaravelShoppingcart/blob/f460ab7312cce32cb428cf39a500a2d16600b1d6/src/Cart.php#L452

**Comment by Power50015** [comment]
@taha7 @bumbummen99 
Can you please take a look at my Code and Tell me exactly what I need to do because of  I completely new in larval and in need some help, please 
https://github.com/Power50015/fup

**Comment by bumbummen99** [comment]
Hehe i think i won't need the whole code ^^ I think this Product model should do the trick:

``` php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Gloudemans\Shoppingcart\Contracts\Buyable;

class Product extends Model implements Buyable
{
    public function presentPrice()
    {
        $price = $this->product_price;
        return "$" . $price;
    }

    /**
     * Get the identifier of the Buyable item.
     *
     * @return int|string
     */
    public function getBuyableIdentifier($options = null) {
        return $this->product_id;
    }

    /**
     * Get the description or title of the Buyable item.
     *
     * @return string
     */
    public function getBuyableDescription($options = null) {
        return $this->product_name;
    }

    /**
     * Get the price of the Buyable item.
     *
     * @return float
     */
    public function getBuyablePrice($options = null) {
        return $this->product_price;
    }
}
```

**Comment by Power50015** [comment]
@bumbummen99  
Why Code hate  me so much 
![2019-05-02](https://user-images.githubusercontent.com/42242552/57091003-7add4c00-6d08-11e9-9a40-ed22e3519a23.png)

**Comment by bumbummen99** [comment]
Don't worry you are close 👍  I tought you are using the official version of the package. Assuming you are using my fork you have to also define a getter method for the product weight. If you do not need any weight calculations (for shipping) you can just 0 everything as it will not affect the other calculations. 
``` php
/**
 * Get the weight of the Buyable item.
 *
 * @return float
 */
public function getBuyableWeight($options = null) {
    return 0; //return $this->weight;
}
```

By writing `class Product extends Model implements Buyable` you say that your Product implements the [Buyable](https://github.com/bumbummen99/LaravelShoppingcart/blob/master/src/Contracts/Buyable.php) [Interface](https://www.php.net/manual/en/language.oop5.interfaces.php) (It's called a [Contract](https://laravel.com/docs/5.8/contracts) in Laravel) and it's abstract methods. Also if you do not already have one i suggest to install an extension for [intellisense and php](https://marketplace.visualstudio.com/items?itemName=felixfbecker.php-intellisense), this has saved me hours already.

**Comment by taha7** [comment]
@Power50015  Did you solve the problem ?

**Comment by Power50015** [comment]
first of all, I already use a bumbummen99 fork.
I fix it by only Two lines of code in product model 
`    protected $primaryKey = 'product_id';
    public $incrementing = false; `
Now I have a 
![2019-05-03 (1)](https://user-images.githubusercontent.com/42242552/57152910-3075d100-6dd5-11e9-8df4-763d9e38ce6a.png)
![2019-05-03](https://user-images.githubusercontent.com/42242552/57152912-310e6780-6dd5-11e9-8bd3-9a9d54663e7c.png)

compleatly new error when I try to remove.

**Comment by Power50015** [comment]
actually I fix it too by this line of code 
`<form action="{{ route('cart.destroy', $item->rowId)}}" method="POST">`
thanks guys
