### ISSUE TITLE
Cart::store('identifier') doesn't store timestamps

### ISSUE THREAD

**Issue by cobraprojects** [Crinsane/LaravelShoppingcart#585]
When I store the Cart into database every thing is good but `created_at` and `updated_at` is `null`
Is there somthing to fix that?

I user `Cart::Store('identifier');` to store the cart into database.

please help
thanks

**Comment by jordantsap** [comment]
you have to specify with in the cart or order model

**Comment by bumbummen99** [comment]
I have already fixed that but i have had no time to write any tests yet.
https://github.com/bumbummen99/LaravelShoppingcart/pull/3
