### ISSUE TITLE
Failed to install on Laravel 6.4

### ISSUE THREAD

**Issue by saroven** [Crinsane/LaravelShoppingcart#593]
composer require gloudemans/shoppingcart
Using version ^2.6 for gloudemans/shoppingcart
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for gloudemans/shoppingcart ^2.6 -> satisfiable by gloudemans/shoppingcart[2.6.0].
    - Conclusion: remove laravel/framework v6.4.0
    - Conclusion: don't install laravel/framework v6.4.0
    - gloudemans/shoppingcart 2.6.0 requires illuminate/events 5.1.* || 5.2.* || 5.3.* || 5.4.* || 5.5.*|| 5.6.* || 5.7.* -> satisfiable by illuminate/events[5.1.x-dev, 5.2.x-dev, 5.3.x-dev, 5.4.x-dev, 5.5.x-dev, 5.6.x-dev, 5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9].
    - don't install illuminate/events 5.1.x-dev|don't install laravel/framework v6.4.0
    - don't install illuminate/events 5.2.x-dev|don't install laravel/framework v6.4.0
    - don't install illuminate/events 5.3.x-dev|don't install laravel/framework v6.4.0
    - don't install illuminate/events 5.4.x-dev|don't install laravel/framework v6.4.0
  
    - don't install illuminate/events v5.7.9|don't install laravel/framework v6.4.0 install illuminate/events v5.7.26|don't install laravel/framework v6.4.0
    - don't install illuminate/events v5.7.27|don't install laravel/framework v6.4.0
    - don't install illuminate/events v5.7.28|don't install laravel/framework v6.4.0
    - don't install illuminate/events v5.7.3|don't install laravel/framework v6.4.0
    - don't install illuminate/events v5.7.4|don't install laravel/framework v6.4.0
    - don't install illuminate/events v5.7.5|don't install laravel/framework v6.4.0
    - don't install illuminate/events v5.7.6|don't install laravel/framework v6.4.0
    - don't install illuminate/events v5.7.7|don't install laravel/framework v6.4.0
    - don't install illuminate/events v5.7.8|don't install laravel/framework v6.4.0
    - don't install illuminate/events v5.7.9|don't install laravel/framework v6.4.0
    - Installation request for laravel/framework (locked at v6.4.0, required as ^6.0) -> satisfiable by laravel/framework[v6.4.0].

Installation failed, reverting ./composer.json to its original content.

**Comment by Azaznr** [comment]
for laravel 6 you can use [https://github.com/darryldecode/laravelshoppingcart](https://github.com/darryldecode/laravelshoppingcart) 
or 
[https://github.com/hardevine/LaravelShoppingcart](https://github.com/hardevine/LaravelShoppingcart)

**Comment by bumbummen99** [comment]
#575
#581
#589
#569
#556
#548
#521

#587
#579
#573
#572
#571
#568

**Comment by olimortimer** [comment]
I'm working on a fork that's compatible with Laravel 7 - everything seems to be working at the moment, but please submit a pull request if not;

https://github.com/olimortimer/LaravelShoppingcart

**Comment by olimortimer** [comment]
I'm working on a fork that's compatible with Laravel 7 - everything seems to be working at the moment, but please submit a pull request if not;

https://github.com/olimortimer/LaravelShoppingcart
