### ISSUE TITLE
Get rowid of last added item

### ISSUE THREAD

**Issue by longestdrive** [Crinsane/LaravelShoppingcart#60]
Hi
I'm trying to get the rowid of the last inserted item but not having much luck. I've tried checking the return value of Cart::add() but this returns a null value.

I need to use the rowid in an associated cart instance - a bit like a one to many relationship but can't see a method or way of obtaining.

I thought Cart::add() would return a row collection?

Is this intended behaviour to return null after an add?

**Comment by morsaPT** [comment]
+1
Array of rowids looks good to me!

**Comment by cchacholiades** [comment]
Well, is it possible to get the quantity for any item added to the cart without having the row id for the last inserted item?

**Comment by joeserg** [comment]
I was also looking for this functionality and have come up with a (potentially hacky) workaround. This line of code appears directly after I call the `add()` method:

`$row = Cart::search(['id' => $product_id ]);`

Because I store a product ID against each item, I'm able to reliably query the cart for the last added (or updated) row.

**Comment by Crinsane** [comment]
Added in new release.

**Comment by Harrrrry** [comment]
I am using this "gloudemans/shoppingcart": "~1.3"
Can I get the last insert cart row id?

`$cartdata = Cart::add(['id' => $card_id, 'name' => $name, 'qty' => $quantity, 'price' => $netprice, 'options' => ['cardinfo'=>$retailersearchdata,'retailerinfo'=>$retailerinfo]]);
echo '<pre>'; print_r($cartdata); exit;`

I getting nothing right now.
Please help

**Comment by Crinsane** [comment]
I’m sorry, version 1.3 is not supported anymore.

**Comment by Harrrrry** [comment]
is there any way to do this in 1.3 version

**Comment by Harrrrry** [comment]
Hi i got it
I change below code
`	protected function addRow($id, $name, $qty, $price, array $options = [])
	{
		if(empty($id) || empty($name) || empty($qty) || ! isset($price))
		{
			throw new Exceptions\ShoppingcartInvalidItemException;
		}

		if( ! is_numeric($qty))
		{
			throw new Exceptions\ShoppingcartInvalidQtyException;
		}

		if( ! is_numeric($price))
		{
			throw new Exceptions\ShoppingcartInvalidPriceException;
		}

		$cart = $this->getContent();

		$rowId = $this->generateRowId($id, $options);

		if($cart->has($rowId))
		{
			$row = $cart->get($rowId);
			$cart = $this->updateRow($rowId, ['qty' => $row->qty + $qty]);
		}
		else
		{
			$cart = $this->createRow($rowId, $id, $name, $qty, $price, $options);
		}

		**$this->updateCart($cart);
		return $rowId;**
	}`

**Comment by Harrrrry** [comment]
Hi i got it
I change below code
`	protected function addRow($id, $name, $qty, $price, array $options = [])
	{
		if(empty($id) || empty($name) || empty($qty) || ! isset($price))
		{
			throw new Exceptions\ShoppingcartInvalidItemException;
		}

		if( ! is_numeric($qty))
		{
			throw new Exceptions\ShoppingcartInvalidQtyException;
		}

		if( ! is_numeric($price))
		{
			throw new Exceptions\ShoppingcartInvalidPriceException;
		}

		$cart = $this->getContent();

		$rowId = $this->generateRowId($id, $options);

		if($cart->has($rowId))
		{
			$row = $cart->get($rowId);
			$cart = $this->updateRow($rowId, ['qty' => $row->qty + $qty]);
		}
		else
		{
			$cart = $this->createRow($rowId, $id, $name, $qty, $price, $options);
		}
/*  I change here */
		$this->updateCart($cart);
		return $rowId;
	}`

Is it right way to do ?
