### ISSUE TITLE
Missing feature, or not working as expected 

### ISSUE THREAD

**Issue by marwan2** [Crinsane/LaravelShoppingcart#607]
You should enable search using the id inserted beside rowId

**Comment by itxshakil** [comment]
You should see [https://github.com/hardevine/LaravelShoppingcart](https://github.com/hardevine/LaravelShoppingcart)

**Comment by bumbummen99** [comment]
The name of this issue is really disrespectful towards the creator and community of this package and i wish you will take a moment to think about that ✌️ 

You can find a list of maintained forks here https://github.com/Crinsane/LaravelShoppingcart/wiki/Maintained-Forks

**Comment by itxshakil** [comment]
> The name of this issue is really disrespectful towards the creator and community of this package and i wish you will take a moment to think about that ✌️ 
> 
> You can find a list of maintained forks here https://github.com/Crinsane/LaravelShoppingcart/wiki/Maintained-Forks

Very true bro.

**Comment by marwan2** [comment]
Sorry
