### ISSUE TITLE
How to use it using ajax ?

### ISSUE THREAD

**Issue by kapil-gupta** [Crinsane/LaravelShoppingcart#63]
Please Help
How to use it using ajax ,is there any documentation ?

**Comment by Crinsane** [comment]
It work's the same, you just have to use AJAX calls to get your cart content from the session.

**Comment by Gameonn** [comment]
`$.ajax({
              type: 'post',
              url: action-url,
              data: data,              
              success: function(response) {
                console.log("{{Cart::subtotal()}}");
                console.log("{{Cart::content()->count()}}");
              }
            });`

Using Crinsane in ajax but the Cart::subtotal and cart count remains zero even after I add items in the cart.
After I reload the page it shows the correct value.

**What can be the problem??**

**Comment by Crinsane** [comment]
Because what you're trying to do doesn't work. Blade will render before the JavaScript, so you're actually just console.log -ing the subtotal and count on page load. Your ajax call should return the subtotal and content

**Comment by Gameonn** [comment]
@Crinsane So how can I get the value of subtotal and count?
In ajax success response I am getting object of `Cart::content()`.

**Comment by Crinsane** [comment]
Either calculate them yourself from the response you get, or you return all of those from you controller.


```php
return response()->json(
   'content' => Cart::content(),
   'subtotal' => Cart::subtotal(),
   'count' => Cart::content()->count()
);
```

Loads of ways to solve this, just google around a bit.

**Comment by Gameonn** [comment]
Thanks @Crinsane

**Comment by jshprz** [comment]
@Crinsane  why i'm always get emty when passing into json but there's a data on my cart?
