### ISSUE TITLE
Missing typehints makes DI impossible

### ISSUE THREAD

**Issue by viirre** [Crinsane/LaravelShoppingcart#66]
The constructor of the Cart class doesn't typehint the Event and Session dependencies.

Because of this, a developer can't typehint this class in a constructor to get an instance nor can he use App::make(). Eg. the code:

```php
App::make('Gloudemans\Shoppingcart\Cart');
```
will result in a exception like: `Unresolvable dependency resolving [Parameter #0 [ <required> $session ]] in class Gloudemans\Shoppingcart\Cart`

To solve this, it should only be to add typehints to the session and event classes, eg:

```php
public function __construct(\Illuminate\Session\SessionManager $session, \Illuminate\Events\Dispatcher $event)
```

Since this is a really simple fix, I can write a Pull Request for this, but I don't really know how to write the unit test for this kind of change..

**Comment by Crinsane** [comment]
Thanks for the request. I know of this, but i'm unsure if I'll change it on this version, or only update the newer version. I'll look into it. :-)

For now you could use App::make('cart'); to get it out of the IoC container.

**Comment by viirre** [comment]
Ah cool, didn't think of that. Is there any particular reason for the
absence of type hints (just curious!)?
Den 19 jan 2015 19:48 skrev "Rob Gloudemans" <notifications@github.com>:

**Comment by Crinsane** [comment]
To be honest, I think it was because at first, I only used the Session and didn't want to couple to much with Laravel, but didn't know what typehint instead, which interface or something. ;-) 
That's the only reason I can think of. :-p

**Comment by mikenolimits** [comment]
Yo.

If anyone else is having problems with this you can create an instance like so w/o modifying any source code or forking.
``` $c = app('Gloudemans\Shoppingcart\Cart',[app('session'),app('events')]);
 ````

**Comment by Crinsane** [comment]
Fixed in new version.
