### ISSUE TITLE
Model find

### ISSUE THREAD

**Issue by stechnique** [Crinsane/LaravelShoppingcart#67]
Hi, I have an issue with the model association feature. My models are not eloquent models, and it is harder for me to implement a local ->find($id) on them, but they do (like Eloquent) implement the static::find($id) method and return a new instance if found. Is there a reason you are using this form now?

    $model = new $modelInstance;
    return $model->find($this->id);

Seems to me using the static method is better documented and more frequently seen in Eloquent:

    return $modelInstance::find($this->id);

It would also happen to fix my problem using non-eloquent models :)

**Comment by stechnique** [comment]
I would personally also prefer to see :

    if($arg == camel_case($this->associatedModel))

instead of :

    if($arg == strtolower($this->associatedModel))

Which is more in line with how Laravel handles model case in general, and makes pretty calls for multi-word class names (also my case).

**Comment by Crinsane** [comment]
I'm going to improve the way associated models work in the next version, so I'll keep your input in mind :)
