### ISSUE TITLE
Store associated model in session

### ISSUE THREAD

**Issue by fogine** [Crinsane/LaravelShoppingcart#68]
Would it be possible to change "associate model" logic so model would be instantiated just within first call and stored as object property?

The problem is that in current version I can not change internal state of the associated object...

Something in this direction:

    if($arg == strtolower($this->associatedModel))
    {
            if(!isset($this->model)) {
                $modelInstance = $this->associatedModelNamespace ? $this->associatedModelNamespace . '\\' .$this->associatedModel : $this->associatedModel;
                $this->model = new $modelInstance;
                $this->model->find($this->id);
            }

			return $this->model;
    }

Even more better would be to have option to choose if associated model is stored in session or not.

**Comment by Crinsane** [comment]
The reason those are not stored in the session is the fact that it would mean the entire Model should be serialized and saved in the session. If someone would, for instance use the cookie sessions, this could give all kinds of errors.

I'm thinking about another way to handle this, but haven't found a clean way yet.

**Comment by fogine** [comment]
That's why I suggested the another option to choose if model will be stored in session or not...
But I understand that it's not "clean" way.

Could I ask what way you're thinking about in order to solve the issue?

**Comment by Crinsane** [comment]
Nothing concrete actually. I just don't think there's really a way to store the entire cart (models and all) in session. At least not while supporting all session drivers.
So the best way, I think, is to improve the way models are handled, maybe let people override/write there own, logic to retrieve the models.

**Comment by runningjack** [comment]
i think it'll be great if Cart::add(...) is sessioned so it could be accessible any where
