### ISSUE TITLE
maintaining a cart instance for a current user

### ISSUE THREAD

**Issue by Bulmer** [Crinsane/LaravelShoppingcart#7]
This is a great package, thanks. I would have asked this on the L4 forum but couldn't find any mention of your package there..
It seems I can only maintain a logged-in users cart instance (by using their id) within a single script. What would be the best way to keep their cart instance current whenever they are logged-in? I have tried an event listener, but couldn't get it  to work. Any ideas?
Thanks.

**Comment by samjoyce777** [comment]
great package!! I am looking to save the cart, in db using just serialize, but the only way I can see is to serialize Cart::content(). But this does not store the models/namespaces, so when I go the backend of my app, I lose the relationships. Is there anything implemented for this?

**Comment by salvisb** [comment]
How about cart expiration time? After how long session is expired, it can be configured?
