### ISSUE TITLE
Using this Cart::add 

### ISSUE THREAD

**Issue by rahul7777yadav** [Crinsane/LaravelShoppingcart#70]
When we use Cart::add(array('id' => '293ad', 'name' => 'Product 1', 'qty' => 1, 'price' => 9.99, 'options' => array('size' => 'large')));
This type of error were found :
 production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Using $this when not in object context' in /opt/lampp/htdocs/laravel/vendor/gloudemans/shoppingcart/src/Gloudemans/Shoppingcart/Cart.php:128

**Comment by Crinsane** [comment]
Are you sure you're using the `Cart` Facade, and not calling the method statically on the `Cart` class?
