### ISSUE TITLE
Cart add only 3 items

### ISSUE THREAD

**Issue by yasir1** [Crinsane/LaravelShoppingcart#71]
I am using shopping cart with L5. The problem is cart only add three items not more then 3. I dont now where problem is.
````
Cart::destroy();
        //Add Items to Cart

            foreach($request->service_id as $row):
                $detail = explode('-', $row);
                Cart::instance('shopping')->add($detail[0], $detail[2], '1', $detail[1]);
            endforeach;
````

**Comment by Crinsane** [comment]
I can't reproduce this problem, everything seems to work fine. Please check your setup, or supply me with more data to reproduce your problem.
