### ISSUE TITLE
Need better hash for checking if item is already in cart.

### ISSUE THREAD

**Issue by rduchnik** [Crinsane/LaravelShoppingcart#76]
1. Add item1 to the cart (a unique rowid is generated).
2. Update item1 option (the rowid is not updated, since it was already generated).
3. Add item2 to the cart (whoops same unique rowid as item1 again).

Say I want to order a large and a small sweater in one purchase. I can't do this if the option is set AFTER the item is added to the cart. Say I have an ajax app that let's me change an items option after it's already been added. This will cause problems.

Seems there should be a unique rowid as well as an internal hashid that get's updated each time there is an update to the cart (options, price, etc).

**Comment by Crinsane** [comment]
Thanks for reporting. I'll look into this asap.

**Comment by stackoverflows** [comment]
Any updates on this issue?

**Comment by Crinsane** [comment]
No not yet, have been feeling sick last week, so haven't been out of bed much.
I was thinking, won't this problem be solved if the rowId is regenerated after an option changes?

**Comment by rduchnik** [comment]
This will pose problems for an ajax application. It can be done of course,
but it's additional work for the developer. Probably should be tucked away
in the item object. IMHO

**Comment by Crinsane** [comment]
Yes, well I'll look into it, but I'm not sure if want to go that way, I think it's nice that the package just has a simple hash (the rowId) to track everything. 
I'll get back to this.

**Comment by rduchnik** [comment]
Well for now it would be great if it does at least regenerate the rowid
after an option change. So it would be great if you can implement that. :-)

**Comment by hunterg325** [comment]
@rduchnik  Created a pull request that solves this issue.

**Comment by argb** [comment]
haven't solve the bug?

**Comment by hunterg325** [comment]
The pending pull request solves the bug. It just has to be merged.

**Comment by lukepolo** [comment]
:+1: , please merge!

**Comment by henriquebremenkanp** [comment]
@Crinsane Do you have plans to merge these PRs? 
If not, how can we help to solve this issue?

**Comment by Crinsane** [comment]
Long overdue, but this issue is fixed in the next release. Current version is in the master branch, will be tagged soon.
