### ISSUE TITLE
Admin changed the product detail while the product is in the cart of the user

### ISSUE THREAD

**Issue by jsdecena** [Crinsane/LaravelShoppingcart#78]
When the admin change the details of the product (ie. price) while this product is in the cart of the user, the details remains unchanged unless the customer add it again to their cart.

**Comment by iaroel** [comment]
That approach may get your customers upset

On 22/03/2015 2:36 pm, "Jeff Simons Decena" <notifications@github.com>
wrote:
>
> When the admin change the details of the product (ie. price) while this
product is in the cart of the user, the details remains unchanged unless
the customer add it again to their cart.

**Comment by Crinsane** [comment]
As said above, I think that would be a very bad practice, changing the price of an item while it's in you're shoppingcart. If you really want to do something in these situation, recalculate the cart on checkout or something.

**Comment by jsdecena** [comment]
Thanks for replying. In real life scenario, the admin would not know if any of his product is in someone's cart. I am trying to come up a solution and will post here if successful.
