### ISSUE TITLE
cannot get the remove item work

### ISSUE THREAD

**Issue by ekophe** [Crinsane/LaravelShoppingcart#81]
i cannot get the controller works for my remove item.

here's my controller code for removing item:
public function getRemoveitem($id){
        $product = Product::whereId($id)->first();
        Cart::remove($product->rowid);
        return Redirect::to('store/cart');
    }

and this is my link to delete the product in the view:
a href="/store/removeitem/{{$product->rowId}}">{!!Html::image('img/remove.gif', 'Remove product')!!}

the error said "Missing argument 1 for App\Http\Controllers\StoreController::getRemoveitem()"

if i dd($product->rowid) it gave me some value. but i cant seem to put the rowid of product in my controller so that i can remove it from my shopping cart. 

Can someone gave a hint to this matter?

**Comment by ekophe** [comment]
My bad. It should be $product->rowid instead of $product->rowId. Now its working fine. 

Great plugin.

**Comment by Crinsane** [comment]
Glad you got it to work!
