### ISSUE TITLE
Associate not working

### ISSUE THREAD

**Issue by notflip** [Crinsane/LaravelShoppingcart#82]
I'm trying to associate the Cart to my products model

    Cart::associate('Product')->add($id, $product->name, $quantity, 4.50);

I'm getting the unknown model exception.. The name of my model is 'Product'
Any idea what I might be doing wrong here?

( Great plugin by the way! )

**Comment by cuongduc** [comment]
+1 I also have this problem in Laravel 5. At first, I thought it was because I didn't set the app namesepace. However, even after setting namespace, the issue still retains

**Comment by Crinsane** [comment]
Thanks for reporting this. Will look into it asap, just very busy lately.

**Comment by damienIN** [comment]
Associate is working as expected in my installation of L5. Associate takes two parameters, "ModelName" and "Namespace." The default namespace for L4 was null, but should be "App" for L5.

If you're using L5, but want to use associate, just pass in parameters like...

    Cart::associate('Product','App\Ecommerce')

**Comment by sevealecks** [comment]
I'm using L5 and it's work almost fine but...
In my case, instead to get product name with $row->product->name, I use $row->product['name']
Try this

**Comment by MikkyX** [comment]
I'm on Laravel 5.1 and am getting this error, even when using
    Cart::associate('Product','App\Product')-

as suggested above.

**Comment by stevethomas** [comment]
+1 @MikkyX, I initially hit this exception as well, is the correct usage. I'm going to submit a PR with an update to the docs as it was not self-explanatory. 
```
Cart:associate('Product','App')
```

**Comment by mateusjatenee** [comment]
Just upping this so other people can see!

**Comment by cjmling** [comment]
+1 @MikkyX   Thanks thats work :)

**Comment by martindelahorra** [comment]
Hi, i have a question with the associate(), Can i Associate Two models in Cart??
