### ISSUE TITLE
Cart::update() 

### ISSUE THREAD

**Issue by juan-sp-si** [Crinsane/LaravelShoppingcart#87]
Hi I am trying to update the Quantity of a item in the cart when I use Cart::update($rowId,$qty)

I get this in the cart content
```
CartCollection {#235 ▼
  #items: array:1 [▼
    "c287c01b76942b7b09df2614b6bd8e4f" => CartRowCollection {#236 ▼
      #associatedModel: null
      #associatedModelNamespace: null
      #items: array:7 [▼
        "rowid" => "c287c01b76942b7b09df2614b6bd8e4f"
        "id" => 11
        "name" => "Prueba"
        "qty" => 2
        "price" => "567.99"
        "options" => CartRowOptionsCollection {#237 ▶}
        "subtotal" => 567.99
      ]
      +"qty": 1
    }
  ]
}
```
my new value is in the array of item but I also see  qty set as 1 outside of that array and that 1 is the value I get as the qty of the row...

**Comment by Crinsane** [comment]
Please supply me the code you're using, because I can't reproduce this.

**Comment by juan-sp-si** [comment]
Sure here is the function
a form is submited and 
id = c287c01b76942b7b09df2614b6bd8e4f
qty = 2

	public function updateCart()
	{
		$rowId = Input::get('id');
		$qty = Input::get('qty');
		Cart::update($rowId, $qty );
		return redirect('/carrito');	
		return $id;
	}


Ive also tried instead of using a variable for $qty  setting the number manually with the same results.

**Comment by giapfpt** [comment]
I want update multiple row with POST method, please help me, thanks :)

**Comment by huyle2607** [comment]
I hope this one will help you. Here is my code that I used in my eCommerce project.
```
public function updateCart()
    {
    	$new_quantity = Input::get('quantity'); //Get the new quantity in Input tag names 'quantity'
    	$rowid = Input::get('rowid');                 //Get the specific product rowId to update the quantity
    	Cart::update($rowid, array(                 // Let's update cart!
    		'qty' => $new_quantity
    		));

    	return redirect()->route('mycart'); //Return to the 'mycart' view
    }
```
In cart form, all you need to do is give the action this url <form action="{{ url('/cart/update') }}" method="POST"....
This url will call the updateCart function in the Controller that you have the updateCart funciton written in.

Hope this will help you!
