### ISSUE TITLE
Load cart-content from Cache.

### ISSUE THREAD

**Issue by agrandin** [Crinsane/LaravelShoppingcart#88]
Hi,
I have stored a carts content in the cache like this using Laravel 4.2. Cache::put('CART_<id>',Cart::instance('wscart')->content(),$expiresAt);

Now when I want to load the content of the cart from the cache instead of whats currently in it. IS it possible? I want to do something like this, Cart::instance('wscart')->content = Cache::pull('CART_<id>');
which obviously does not work. But is there a way to do this?

**Comment by Crinsane** [comment]
There's indeed no build in way to import old cart content.
I guess the best way to do this right now is just take the old content from your cache, loop over it and re-add all items. So something like:

```php
$cacheContent = Cache::get('cart');

foreach($cacheContent as $row)
{
	Cart::add($row->id, $row->name, $row->qty, $row->price, $row->options);
}
```
