### ISSUE TITLE
Foreach Cart::content(), not working

### ISSUE THREAD

**Issue by AndreasLyngholm** [Crinsane/LaravelShoppingcart#90]
When ever I try to run the Cart::content() through a foreach loop I get a blank page. Please help.

Code:
<img width="1176" alt="skaermbillede 2015-07-25 kl 20 41 58" src="https://cloud.githubusercontent.com/assets/10391836/8890791/a557a00e-330d-11e5-813d-b12562a83c70.png">

Output:
<img width="1920" alt="skaermbillede 2015-07-25 kl 20 43 00" src="https://cloud.githubusercontent.com/assets/10391836/8890792/c5a39aa2-330d-11e5-8124-0812300013a2.png">

**Comment by amirmasoud** [comment]
I did that like this:
on the controller:

    /**
     * Get the cart content
     *
     * @return CartCollection
     */
    public function cartContent()
    {
        $content = Cart::content();

        return view('carts.content', compact('content'));
    }

on the view:

		@foreach( $content as $item )
			<tbody>
				<tr class="text-center">
					<td>{{ $item->name }}</td>
					<td>{{ $item->price }}</td>
					<td>× {{ $item->qty }}</td>
				</tr>
			</tbody>
		@endforeach

**Comment by bebnev** [comment]
In the beginnig of your code you have "if" check:
```php
@if(Cart::content() == null)
```
and "if true" you loop through your content.
Probably the check should be !=
Frankly speaking if your are looping through "forelse" loop with "empty" part, why do you need "if" check ?

And the way that @amirmasoud suggested is much more cleaner.

**Comment by InfiniteDevelopment** [comment]
We should close this one. :) ;)
