### ISSUE TITLE
duplicating rows instead of updating

### ISSUE THREAD

**Issue by ddjikic** [Crinsane/LaravelShoppingcart#97]
Hi , i have 2 ways to add a product to the cart
1) on products list ( quick add to cart using ajax, post method)
2) on product details ( simple form post method )
both send to the same method in the controller.

i have the same item that i want to add to the cart if i use any of the method alone they work as they should, but if i have already the product added using the first method and i want to add it using the second method instead of updating it creates a new record then i have 2 times the same product which is weird. any suggestions ?

**Comment by Crinsane** [comment]
I some sample code to be of any help. Are you setting any options? What is the output of `Cart::content();`?

**Comment by ddjikic** [comment]
i did not see why until i pasted here and saw the formatted output.  I found the issue in some cases option value had a white space

**Comment by Crinsane** [comment]
Ok, glad to see the problem is solved!
