### ISSUE TITLE
RowID

### ISSUE THREAD

**Issue by InfiniteDevelopment** [Crinsane/LaravelShoppingcart#99]
How do we find the row ID to update a instance of the cart?

**Comment by InfiniteDevelopment** [comment]
![screen shot 2015-08-12 at 4 40 14 pm](https://cloud.githubusercontent.com/assets/1442229/9236117/da288d0a-4110-11e5-82c7-73b34f529ad9.png)
![screen shot 2015-08-12 at 4 40 20 pm](https://cloud.githubusercontent.com/assets/1442229/9236121/de923cce-4110-11e5-88ca-0bbb66d13b54.png)


These two show that I can indeed get to the ID attr of that cart object. But I need to have the row ID first. 

See below....
![screen shot 2015-08-12 at 4 41 53 pm](https://cloud.githubusercontent.com/assets/1442229/9236153/101e02d2-4111-11e5-827e-2d181cdcc119.png)
![screen shot 2015-08-12 at 4 41 42 pm](https://cloud.githubusercontent.com/assets/1442229/9236155/13de11be-4111-11e5-8f49-1e7d2f11d8d0.png)

**Comment by Crinsane** [comment]
`$row->rowid`

**Comment by InfiniteDevelopment** [comment]
Where do you get the $row from? Using my screenshots would that be $cartContent->rowid

**Comment by Crinsane** [comment]
`Cart::content()` returns a collection. So you have to get a certain item in it '`$content->first()` or something. Or you loop over all items in the cart.

**Comment by InfiniteDevelopment** [comment]
I still dont get it. I am just trying to find the item ID I have added to make sure I dont add a dupe. You get what I mean?

**Comment by InfiniteDevelopment** [comment]
Look at my code and screenshots. That should show you my delima.

**Comment by Crinsane** [comment]
You mean `Cart::search(['id' => 'your-id'])`?

**Comment by InfiniteDevelopment** [comment]
Will that work? I should do a if(Cart::search(['id' => 'your-id'])){}else {}?

**Comment by Crinsane** [comment]
That methods returns an array of rowids that match your search credentials.

**Comment by InfiniteDevelopment** [comment]
not sure thats what I am looking for but I will hack around and see if it works.

**Comment by InfiniteDevelopment** [comment]
So I am looking to get into that object to get the item ID so that I can make sure no more than one will be able to get added. Maybe you can help me out logically understand how to get the Row ID back that contains that item ID. from there i can do some conditional logic that stops it from occurring.

**Comment by Crinsane** [comment]
@InfiniteDevelopment If you have a `rowId` you can simply use `Cart::get($yourRowId);` to get the row out of the cart and then `$row->id` to get the Id... is that what you mean?
